manifoldmarkets/manifold

functions/src/create-contract.ts, web/components/feed-create.tsx, web/components/nav/sidebar.tsx, web/hooks/use-has-created-contract-today.ts, web/lib/firebase/contracts.ts, web/package.json, web/pages/[username]/[contractSlug].tsx, web/pages/create.tsx, yarn.lock
Users get a free daily market and confetti when they create new markets! The confetti works for ALL owned, newly created markets - not just the free ones.
=> Free daily market

web/components/charity/charity-card.tsx, web/components/charity/feed-items.tsx, web/components/feed/feed-items.tsx, web/pages/charity/[charitySlug].tsx
=> CPM simple feed

web/pages/charity/index.tsx
https://manifold.markets/Sinclair/which-charities-should-manifold-add
=> Replace email with free response market for charities

web/components/feed/feed-items.tsx
this reduces comment input logic complexity, only one component handles comment logic now.
=> condense comment logic in one component

web/components/answers/answer-item.tsx, web/components/answers/answers-panel.tsx
This improves the post resolution free response UX, hiding the number of the answer, and showing options that weren't chosen while keeping the highlighted chosen answer visible.
=> Improve free response answer ux

web/components/avatar.tsx, web/components/nav/nav-bar.tsx, web/components/nav/profile-menu.tsx
I was looking through the components that get rendered all over the place, and I noticed this one had a bunch of unnecessary cruft in the DOM, so I simplified it. No visible change.
=> Cleanup avatar component rendering

web/tsconfig.json
Sorry, I accidentally messed this up in #147! Now it's fixed.
=> Fix up target in web tsconfig

web/components/avatar.tsx, web/components/feed/feed-items.tsx, web/components/nav/nav-bar.tsx
This is #130, but addresses a bug mentioned on Discord where avatars attached to answers in the activity feed would be taller than they were wide.
=> Cleanup avatar again

web/components/bet-row.tsx, web/components/feed/feed-items.tsx
Just some ones that were really easy to toast. I'm just glancing through the components that we use a lot (e.g. they appear over and over in the feed) to see if there are obvious ways to clean them up.
=> Remove some random unnecessary wrapper divs

web/components/feed/activity-feed.tsx
=> restyle home page (separation between markets)

web/components/bet-panel.tsx, web/components/bet-row.tsx, web/components/contract/contract-overview.tsx, web/components/yes-no-selector.tsx
Someday I am going to stop finding random chunks of markup and CSS to delete, but today is not that day. No user-visible changes.
=> Clean up extra wrapper and CSS on BetRow

web/components/feed/activity-items.ts, web/components/feed/feed-items.tsx
FR answer replies are sorted as all other replies (oldest on top). General comments are sorted newest on top.  Added back in outcome text for FR bets. Restored submit button for comments and removed enter as submission trigger.
=> FR ux changes, restore submit button for comments

web/components/share-market.tsx, web/pages/create.tsx
This fixes some stuff that React was screaming about, but which probably doesn't matter except for spamming the console.
=> Fix random errors

web/components/nav/nav-bar.tsx, web/components/nav/sidebar.tsx, web/components/page.tsx, web/pages/home.tsx
Killing more unnecessary wrapper divs, no user-visible changes again.
(Soon I might fix up some of the visual bugs related to sidebar resizing and padding, but I am just simplifying first before I think about getting into any of that.)
=> Clean up some markup around the top of the page

web/components/nav/profile-menu.tsx, web/components/nav/sidebar.tsx
Clean up clean up everybody everywhere
Clean up clean up everybody do your share
Should be no user-visible changes.
=> Clean up some markup in the sidebar

common/util/random.ts
Saves two lines and a variable.
Also, a desperate attempt to save my Mana in https://manifold.markets/ManifoldMarkets/if-we-open-source-our-frontend-code
=> Swap values with structured assignment rather than temporary

common/util/random.ts, functions/src/create-user.ts
- Generate random strings in a cryptographically safe way
- Ensure there are no collisions when using only few bits of randomness
=> Better random

web/components/bet-panel.tsx
Trivial cleanup that I just did because I was poking around in there anyway. No user-visible changes.
=> Clean up some bet panel markup and CSS

web/components/contract/contract-card.tsx, web/components/contract/contract-details.tsx, web/components/outcome-label.tsx, web/components/tags-list.tsx
=> Redesign the contract card

functions/src/api.ts, functions/src/create-contract.ts, functions/src/place-bet.ts, web/components/numeric-resolution-panel.tsx, web/lib/firebase/api-call.ts, web/pages/create.tsx, web/pages/make-predictions.tsx
_**Function status: Not yet deployed to dev or prod. The function changes and client changes must be deployed together.**_
Simple changes to make the public API more fit for actual public consumption. Since the changes are very simple and there's little risk of serious complication, there's no upgrade strategy; once I have tested it on dev, I am just gonna break the site for a couple minutes while I deploy the functions and client and they match again.
=> Public API improvements

.github/workflows/check.yml
No idea if this is gonna work yet, let's just try it and see.
=> Add GitHub 'check' workflow to do static analysis

.github/workflows/check.yml
I'm creating this PR so that I can see how the GitHub actions UI works on PRs and play around with it.
=> Rename static analysis job

web/pages/leaderboards.tsx
Reverts manifoldmarkets/manifold#314
=> Revert "Update leaderboards.tsx"

web/components/choices-toggle-group.tsx, web/components/contract/contract-details.tsx, web/pages/create.tsx
I added the liklihoods with unsure first as that's what most people use and I like the default options being leftmost but I'm open to other opinions.
=> Move to tailwindui for create market page

common/.eslintrc.js, common/calculate-dpm.ts, common/envs/constants.ts, common/new-contract.ts, common/scoring.ts, common/tsconfig.json, common/util/object.ts, common/util/random.ts, functions/.eslintrc.js, web/pages/fold/[...slugs]/index.tsx
Just gradually turning on more checks when it's easy and fixing up trivial issues.
There are lots of interesting typing problems related to "contracts that have some properties" which I don't know how to solve yet, so I am not attempting to turn on `no-explicit-any` until I am a better Typescript programmer and I understand the best solution to these problems.
=> Add tsconfig, more linting to `common` package

common/.eslintrc.js, common/contract.ts, common/new-bet.ts, common/new-contract.ts, functions/.eslintrc.js, functions/package.json, functions/src/api.ts, functions/src/create-answer.ts, functions/src/create-contract.ts, functions/src/place-bet.ts, web/components/numeric-bet-panel.tsx, web/components/tags-input.tsx, web/pages/create.tsx, yarn.lock
_**Function status: Deployed on dev for testing. Not yet deployed on prod.**_
- Dug up a good validation library ([`zod`](https://github.com/colinhacks/zod)) which will be useful in the future for validating API inputs.
- Applied it to `createContract` and `placeBet`, thereby implementing a variety of input validation that was sort of only mostly-implemented before (and making it work with Typescript properly.)
- Got rid of some unused code and made other refactors that shouldn't affect any behavior.
I still need to test all the different error cases to make sure this validation is working and produces acceptable error messages to API consumers, but I'm putting this out there to get eyes on it.
=> Serious business API validation & big cleanup of `createContract`, `placeBet`

web/.eslintrc.js, web/components/amount-input.tsx, web/components/client-render.tsx, web/components/contract/quick-bet.tsx, web/components/datetime-tooltip.tsx, web/components/feed/activity-items.ts, web/components/feed/copy-link-date-time.tsx, web/components/join-spans.tsx, web/components/layout/modal.tsx, web/components/layout/tabs.tsx, web/components/linkify.tsx, web/components/nav/nav-bar.tsx, web/components/nav/sidebar.tsx, web/components/number-input.tsx, web/components/outcome-label.tsx, web/components/page.tsx, web/components/site-link.tsx, web/lib/api/proxy.ts, web/lib/firebase/init.ts, web/lib/util/copy.ts, web/pages/_app.tsx, web/pages/admin.tsx, web/pages/charity/[charitySlug].tsx, web/pages/folds.tsx, web/pages/profile.tsx
Just really normal stuff, importing `React` when we didn't import it, changing a lot of `let`s to `const`s, fixing up typing when we were lazy, etc. Should be no visible changes.
=> Add more linting to `web` package

docs/.prettierignore, docs/docs/binary-markets.md, docs/docs/faq.md, docs/docusaurus.config.js
=> Fix up formatting in the docs package to use Prettier correctly

web/components/bets-list.tsx
Commit a84014399 is in main and fails lint because a dependency of `useEffect` in `BetsList` changed but what actually gets passed to the `useEffect` didn't.
This fixes it.
=> Fix dependency of useEffect in BetsList

common/charity.ts
Adding some suggested charities
=> Add charities: EA Funds and Founders Pledge funds

common/package.json, functions/package.json, package.json, web/package.json
Basically the same static analysis as the github workflow, but in the form of a yarn script for more convenient local use.
If there's already an easy way to do this let me know, but I didn't see anything along these lines in the README or package.json.
=> Add `yarn verify` script

common/.eslintrc.js, common/util/types.ts, web/pages/[username]/[contractSlug].tsx, web/pages/embed/analytics.tsx
Just fixing up little things I see.
=> Small cleanup to some `common` code

functions/README.md, functions/package.json, functions/src/create-answer.ts, functions/src/create-user.ts, functions/src/on-create-comment.ts, functions/src/resolve-market.ts, functions/src/send-email.ts, functions/src/stripe.ts, yarn.lock
***Deploy status: Secrets are moved over on dev and prod. Functions redeployed on dev but not prod.***
This is important because v2 Cloud Functions doesn't support our old config stuff. So we need to do this switch before we can make any of our functions be v2.
=> Switch to Google Secret Manager for function secrets

common/envs/dev.ts, common/envs/prod.ts, common/envs/theoremone.ts, web/components/bet-panel.tsx, web/lib/api/proxy.ts, web/lib/firebase/api-call.ts, web/pages/api/v0/bets/index.ts, web/pages/api/v0/market/index.ts, web/pages/create.tsx, web/pages/make-predictions.tsx
=> Point client at new v2 versions of `createmarket` and `placebet`

common/envs/dev.ts, common/envs/prod.ts, common/envs/theoremone.ts, common/sell-bet.ts, functions/src/sell-shares.ts, web/components/bet-panel.tsx, web/components/contract/quick-bet.tsx, web/lib/firebase/api-call.ts, web/lib/firebase/fn-call.ts
Pretty mechanical. See #438. Same deployment steps apply.
=> Migrate `sellShares` cloud function to v2 `sellshares`

common/contract.ts, functions/src/place-bet.ts
Fix pool overflow bug by enforcing minimum share quantity in liquidity pool.
=> Fix overflow

functions/src/update-user-metrics.ts
Similar to #476, I don't know whether this is moving the needle, but it's common sense to not do a thousand database queries when we could do one.
It's possible this will blow the memory budget but we can bump the memory on the instances if so.
=> Optimize `updateUserMetrics`

functions/src/create-contract.ts
I accidentally broke this while cleaning up a bunch of obsolete variable-ante code in #302. Now it's fixed.
=> Validate that user can pay for market

web/pages/index.tsx
Updated the fixed list of trending markets on the landing page. Chose ones which are slightly more friendly to new users and mainstream.
=> Update Trending Markets

docs/docusaurus.config.js
=> Update docs link to point to new repo

docs/docs/api.md, web/lib/firebase/contracts.ts, web/pages/api/v0/_types.ts, web/pages/api/v0/market/[id].ts, web/pages/api/v0/slug/[slug].ts
Resolves https://github.com/manifoldmarkets/manifold/issues/515
Adds "free response" market answers to the FullMarket responses in API routes
=> Include free response answers in FullMarket API response

docs/docs/binary-markets.md
Does the market creator get their M$100 back after the market resolves like liquidity providers do, or does it go to the market winner?
=> Update Binary Markets Docs

docs/README.md, docs/docs/awesome-manifold.md
Per Austin's [idea](https://discord.com/channels/915138780216823849/943628693958459462/986759035334312006) in the Discord.
I skimmed the previous couple newsletters for initial ideas, but there are probably things that I've missed
=> Create initial 'Awesome Manifold' docs page

web/components/answers/answers-graph.tsx, web/components/contract/contract-prob-graph.tsx
Step charts accurately represent the price at each point in time. And they look better too!
Additional photos: https://imgur.com/a/priJVgt
=> Step charts

functions/package.json, functions/src/api.ts, functions/src/place-bet.ts
After this, we should be able to start getting some idea for what is taking all the time in `placeBet`.
=> Clean some API stuff up and instrument `placeBet` with a bunch of logging

functions/src/on-create-bet.ts
I just happened across this and it looks to me like there's no value in doing this check, so let's not do it.
=> Don't unnecessarily query contract in `onCreateBet`

web/lib/firebase/contracts.ts, web/pages/api/v0/_types.ts, web/pages/api/v0/market/[id].ts, web/pages/api/v0/slug/[slug].ts
Followup to https://github.com/manifoldmarkets/manifold/pull/519
Example:
```
$ curl localhost:3000/api/v0/slug/frq2 | jq ".answers[0:3]"
[
{
"avatarUrl": "https://lh3.googleusercontent.com/a-/AOh14GhGa0Vhb3LTBXbd2fGfekbG5clPQSVe59Xh35CrKw=s96-c",
"username": "IanPhilips",
"id": "1",
"number": 1,
"createdTime": 1654610507026,
"text": "hihi",
"name": "Ian Philips",
"contractId": "uicBorB8PVrNBAVmSBRB",
"userId": "6hHpzvRG0pMq8PNJs7RZj2qlZGn2",
"probability": 0.2013730018015957
},
{
"avatarUrl": "https://lh3.googleusercontent.com/a-/AOh14GhGa0Vhb3LTBXbd2fGfekbG5clPQSVe59Xh35CrKw=s96-c",
"id": "2",
"username": "IanPhilips",
"text": "jojo",
"contractId": "uicBorB8PVrNBAVmSBRB",
"createdTime": 1654618989239,
"name": "Ian Philips",
"number": 2,
"userId": "6hHpzvRG0pMq8PNJs7RZj2qlZGn2", …
```
=> Include answer probabilities in FreeResponse API results

docs/docs/api.md
Thanks to Zian on Discord for pointing this out.
=> `http` -> `https` in documentation

web/components/user-page.tsx
It seems to me like it's been an appropriate length of time that we should kill this box, which is pretty obtrusive.
Chime in if you disagree!
=> Remove notification box about public/hidden bets

docs/docs/api.md
Reformatting the API docs page to fix some whitespace issues
=> Fix API docs formatting

web/components/contract/contract-prob-graph.tsx
Made an off-by-one error in #529
=> Fix line off the right of closed markets

web/next.config.js
Since we had a lot of bets today this is literally required to build our software at all.
=> Greatly extend static page generation timeout

web/components/tipper.tsx
No UI changes. Reverse (-5) arrow is simply disabled except in the 1.5 second window, and you can't reverse lower than your already saved tip.
=> Comment tips v1.1: Remove undo. Show full tip amount. Scale linear

.github/workflows/check.yml, common/.gitignore, common/tsconfig.json, firebase.json, functions/.gitignore, functions/package.json, functions/tsconfig.json, web/tsconfig.json
OK, here are the changes from #575, except not the ones for the web project, so maybe if the problem was just with `tsc --watch` there will be no problem anymore. Unless @jahooma can tell me more information, I am just going to make PRs with less and less stuff until he doesn't revert them.
=> Typescript project references take 2

common/charity.ts
Added CES charity to the charity page.
=> Add CES charity

web/components/groups/group-selector.tsx, web/components/groups/groups-button.tsx, web/components/nav/sidebar.tsx, web/components/user-page.tsx, web/hooks/use-group.ts, web/lib/firebase/groups.ts, web/pages/groups.tsx
=> Show groups on user page, allow to join/leave

web/lib/firebase/api-call.ts
James noticed this didn't work. I feel like I did this earlier but I guess I must have screwed it up somehow. Anyway, let's fix it.
=> Point v2 functions @ localhost during emulation

docs/docs/api.md
They may not be right, but they are certainly less wrong.
=> Make the resolve API docs not obviously wrong

functions/src/backup-db.ts, functions/src/scripts/backup-db.ts, functions/src/scripts/script-init.ts
Pretty self-explanatory. I haven't tested yet whether there is a better way to do this export that saves us writing the collections here. I am skeptical of the comment that says the obvious thing that's supposed to work won't work.
=> Fix backup DB job to actually backup most things, refactor

firestore.indexes.json
It's missing, we need it, therefore, add it.
=> Add a missing index

common/new-bet.ts, common/redeem.ts, functions/src/redeem-shares.ts
Making some changes here so that it's easier to understand this code and move things around further.
Right now, it still does exactly the same thing it used to do, just tidier looking and easier to inspect. But after this, I'm probably going to do another change where I merge this work into the "main transaction" for the various functions that use it, like `placebet`. That will probably save about four round trips that won't be necessary anymore (one for starting the transaction, two for looking up contract and user data, and one for committing the transaction), so 100-150ms per call. So that's where this is going.
=> Redemption refactoring

common/antes.ts, common/notification.ts, functions/src/create-notification.ts, functions/src/get-daily-bonuses.ts, functions/src/index.ts, functions/src/on-create-txn.ts, web/components/avatar.tsx, web/components/feed/feed-comments.tsx, web/hooks/use-notifications.ts, web/pages/notifications.tsx
=> Show tip notifications

web/components/nav/sidebar.tsx, web/components/notifications-icon.tsx, web/hooks/use-notifications.ts, web/lib/firebase/notifications.ts, web/lib/firebase/utils.ts, web/pages/notifications.tsx
Speeds up the notifications page quite a bit.
=> Use react-query to cache notifications

common/txn.ts, functions/src/create-notification.ts, functions/src/on-create-txn.ts, functions/src/utils.ts, web/components/groups/group-chat.tsx, web/components/tipper.tsx, web/hooks/use-tip-txns.ts, web/lib/firebase/txns.ts, web/pages/[username]/[contractSlug].tsx, web/pages/group/[...slugs]/index.tsx, web/pages/notifications.tsx
=> Enable tipping on group chats w/ notif

functions/src/change-user-info.ts, functions/src/index.ts, web/lib/firebase/api-call.ts, web/lib/firebase/fn-call.ts, web/pages/profile.tsx
Straightforward, the only visible change should be fixing error handling on avatar URL uploads.
(Background: I want to migrate our remaining v1 `onCall` functions to v2 because there is no reason not to and because it will be easier to then do further general backend changes, like deploying them in a single express app and making hot reloading of server code work.)
=> Migrate changeUserInfo function to v2

common/util/parse.ts, web/components/filter-select-users.tsx, web/components/groups/group-selector.tsx, web/hooks/use-sort-and-query-params.tsx, web/pages/charity/index.tsx, web/pages/contract-search-firestore.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/groups.tsx
cleans up some logic, and makes it easier to have fuzzy string matching later
=> refactor string matching for search

web/components/contract/contract-description.tsx, web/components/editor.tsx
- Users can now edit their descriptions using rich editor
- Users can now change their own question
Which then appends a change message in the description
- Whitelisted admins can now do all of the above
=> Let users edit descriptions and questions

web/components/portfolio/portfolio-value-section.tsx
=> Label "Since June" for users who had an account prior to 2022-06-20

web/components/contract-search.tsx
Now React will shut up about it.
=> Add React key prop to homepage filter widget

web/lib/firebase/server-auth.ts
Since the ID token cookie expires at a similar time as the token itself, this control flow was broken. Now it will correctly handle the case where the ID token cookie is not present and there is only a refresh token cookie. So it fixes the behavior where you would come back to the site and it wouldn't know you were logged in on first load because you had an expired cookie.
=> Properly handle expired ID token cookie, be robust to errors

web/pages/index.tsx
I was going to get this done as part of another pass of improving auth more generally, but the lack of this redirect annoys James, so I'm just going to put in this little hack to fix it for now.
=> Make it so that if you sign in on / you get redirected to /home

functions/src/create-notification.ts, functions/src/market-close-notifications.ts, functions/src/on-create-answer.ts, functions/src/on-create-bet.ts, functions/src/on-create-comment-on-contract.ts, functions/src/on-create-contract.ts, functions/src/on-create-group.ts, functions/src/on-create-liquidity-provision.ts, functions/src/on-follow-user.ts, functions/src/on-update-contract.ts
This way you don't need a bunch of `undefined` and you don't have to remember the order of optional params.
I'm doing this because I want to let this function accept a list of recipients, but I found adding/changing params annoying
=> refactor createNotif - put optional args in one param

common/contract.ts, common/group.ts, firestore.rules, functions/src/on-delete-group.ts, functions/src/scripts/convert-categories.ts, functions/src/scripts/link-contracts-to-groups.ts, web/components/contract/contract-details.tsx, web/components/groups/contract-groups-list.tsx, web/components/groups/groups-button.tsx, web/hooks/use-group.ts, web/lib/firebase/contracts.ts, web/lib/firebase/groups.ts, web/pages/create.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/groups.tsx
So we can see the group on the contract card!
=> Backfill and forward fill contracts with group info

functions/src/cancel-bet.ts, functions/src/create-contract.ts, functions/src/on-create-answer.ts, functions/src/on-create-liquidity-provision.ts, functions/src/on-update-user.ts, functions/src/update-metrics.ts
Just some tiny random fixes I noticed when I was reading some cloud functions code.
=> Small backend cleanups

common/charity.ts
Added Founder's Pledge Global Health and Development Fund.
Made new logos for all the Founder's Pledge charities to help distinguish between them.
=> Add Global Health Charity

web/components/comments-list.tsx
I really don't know how the markup ends up with so much literally useless HTML and CSS in it, but this list is a rendering bottleneck on the user profile page, so let's try to clean it up somewhat.
=> Clean up comments list rendering

docs/docs/api.md, web/pages/api/v0/group/[slug].ts, web/pages/api/v0/group/by-id/[id].ts, web/pages/api/v0/groups.ts
This is common sense but specifically supports functionality on the Twitch bot.
=> Add some API endpoints for reading group info

web/lib/firebase/users.ts, web/pages/create.tsx, web/pages/links.tsx, web/pages/notifications.tsx, web/pages/profile.tsx
These are pages where previously we were doing a bunch of `if (user == null)` stuff to render something ridiculous if the user wasn't loaded yet, so this should be a solid improvement to the UX and also clean up the code. (The profile page was especially egregious.)
=> Fix up several pages to load user data on the server

web/components/editor.tsx
=> Remove top/bottom margin from indented list items

web/components/avatar.tsx, web/components/feed/feed-bets.tsx, web/pages/[username]/[contractSlug].tsx
I was looking at this code to try to check out what the deal with performance is, and these are just some random not big deal things I found to improve along the way. (The big deal things will be harder.)
The deal with `useRef` is that `useState` is going to force a re-render when the ref is set, but `useRef` doesn't. So it's better to use `useRef` when possible (i.e. when the ref is only going to be used after rendering, which I am almost sure is the case here...)
=> Random contract page fixups

web/components/tipper.tsx
It's not the change Manifold asked for...but is it the change Manifold deserved?
This isn't important, I was just randomly reading this code and I couldn't help but try to clean it up a little. Also, I think this code was totally broken if the tipper was re-rendered with a different comment than what it started with, but that doesn't happen.
=> Refactor tipper

web/components/user-page.tsx
Both cleaner and more efficient (since the `yourFollows` state is no longer at the top level of the user page.)
=> Use `UserFollowButton` instead of `FollowButton` in `UserPage`

web/lib/firebase/server-auth.ts
I mostly just want to get this in so that I can see some timestamps next to these log entries (production logging should add the timestamps) and see if anything is taking more time than I expect.
=> Add a shitload of logging to the server auth code

web/components/contract-search.tsx, web/components/contract/contracts-grid.tsx, web/components/editor/market-modal.tsx, web/pages/group/[...slugs]/index.tsx
=> Tile contract cards in masonry layout

functions/src/analytics.ts, functions/src/emails.ts, functions/src/send-email.ts, functions/src/utils.ts
It makes way more sense to log if these things fail rather than to blow up whatever they were in the middle of.
=> Backend robustness to email sending or analytics tracking failures

common/charity.ts
works on staging -- https://dev-git-fork-bgila-bgila-add-more-charities-mantic.vercel.app/charity/carla
this is timely -- EA / YIMBY crossover is tomorrow
thanks
=> add YIMBY Law and CaRLA as charities

web/components/amount-input.tsx, web/components/bet-button.tsx, web/components/bet-inline.tsx, web/components/button.tsx, web/components/contract/contract-card.tsx, web/components/contract/contract-overview.tsx, web/components/feed/feed-items.tsx, web/components/sign-up-prompt.tsx, web/components/yes-no-selector.tsx, web/pages/embed/[username]/[contractSlug].tsx
=> Simple bet interface in embeds

common/notification.ts, common/numeric-constants.ts, common/txn.ts, common/user.ts, functions/src/create-notification.ts, functions/src/index.ts, functions/src/on-create-bet.ts, functions/src/reset-betting-streaks.ts, web/components/profile/betting-streak-modal.tsx, web/components/user-page.tsx, web/hooks/use-notifications.ts, web/pages/notifications.tsx
- every time a user places a bet the on-create-bet function checks if it's a new one since the past 9am UTC. If it's new, add one to their streak and send them a bonus + notification. 
- Every day at 9am UTC, the reset-betting-streaks function checks if the user has made a bet since a day ago. If not, their streak is set to 0.
- I'll probably add a fire emoji on someone's profile picture in the navbar/sidebar too
=> betting streaks

web/components/editor.tsx
I think with this, we can fix one of the football markets by admin-edit, ctrl a, ctrl x, ctrl v, save, and then it should be able to duplicate
=> Fix link classes appending on paste

web/components/bet-inline.tsx
=> Fix bet modal probability sticking

web/components/nav/sidebar.tsx
About button name change and now directs to "Help and About Center" super.so
=> Change about button

common/group.ts, firestore.rules, web/components/groups/group-about-post.tsx, web/components/groups/group-dashboard.tsx, web/hooks/use-post.ts, web/lib/firebase/groups.ts, web/lib/firebase/posts.ts, web/pages/group/[...slugs]/index.tsx
This PR adds a Dashboard to a group's about page.
=> Post in a group about page.

firestore.indexes.json, web/components/contract/contract-overview.tsx, web/components/feed/feed-liquidity.tsx, web/components/user-link.tsx, web/lib/firebase/bets.ts, web/lib/firebase/comments.ts, web/pages/[username]/[contractSlug].tsx, web/pages/embed/[username]/[contractSlug].tsx
Nothing important, just some small things I happened to notice.
=> Tidying some feed code up

firestore.rules, web/components/groups/group-about-post.tsx, web/pages/group/[...slugs]/index.tsx
- show add post UI to admins
- change firebase permissions
=> Let admins add and edit posts to any group

web/lib/firebase/init.ts
Can anyone with an android phone test this branch to see if it works fine for y'all? This fixes the crashes on ios but I left my android phone at home!
=> Fix ios bug

common/util/tiptap-iframe.ts, web/components/contract/contracts-grid.tsx, web/components/editor/market-modal.tsx, web/components/share-embed-button.tsx, web/pages/create-post.tsx, web/pages/embed/grid/[...slugs]/index.tsx
Added embedded grids of contract cards to Posts:
https://user-images.githubusercontent.com/6242616/187686727-930a69ff-9196-484b-a408-b73b8c0c4560.mov
=> Add embedded ContractGrid to Posts

web/components/create-question-button.tsx, web/components/nav/menu.tsx, web/components/nav/profile-menu.tsx, web/components/nav/sidebar.tsx, web/components/notifications-icon.tsx
Not anything important, just noticing some stuff here I could clean up.
=> Tidy up some dead code and markup in sidebar

functions/src/update-metrics.ts
If the portfolio didn't change since the cached one, that means all-time profit is the same, but not daily, weekly, or monthly.
=> Leaderboard calc: update profit even when portfolio didn't change 

web/pages/groups.tsx
When loading a user via SSR, it's good to load the user and private user and put them in the `auth` prop, because [the `AuthContext` code will look at that prop to load up its initial state](https://github.com/manifoldmarkets/manifold/blob/main/web/pages/_app.tsx#L79). So passing it via the `auth` prop will make stuff using `useUser` outside your page component, like the sidebar, render correctly on the server, and save your component a re-render later on, because `useUser` will start out with the right thing in it, instead of starting out with e.g. the local storage cache and later loading the up-to-date user doc from the DB.
(Loading the user and private user in parallel is basically equally fast as loading just the user, and every page is eventually going to want the private user in …
=> Use the magic `auth` prop for groups SSR

web/pages/post/[...slugs]/index.tsx
Added an edit button to posts. Merging without review as It's affecting a feature that users can't access, and i'd like to try it out today with a post I just created.
=> Edit posts

web/components/bet-button.tsx, web/components/contract/contract-card.tsx, web/components/contract/contract-overview.tsx, web/components/contract/quick-bet-arrows.tsx, web/components/contract/quick-bet-button.tsx
for some reason this isn't working on ios local dev, going to test this branch
=> Yes and no buttons on contract page

common/group.ts, functions/src/update-metrics.ts, web/lib/firebase/groups.ts, web/pages/group/[...slugs]/index.tsx
This is a new PR for the 500 internal error. I had to revert the previous merge, as the updateMetrics function is throwing an error. 
@jahooma How can I test this in the dev instance? I've tested on localhost of course, by using yarn start and calling updateMetrics() manually. But there seems to be some difference between the behaviour there and in production, as I get no errors locally. 
Should I deploy this to dev instead and test there? 
Logs for updateMetrics are here: 
https://console.cloud.google.com/functions/details/us-central1/updateMetrics?project=mantic-markets&authuser=1&hl=es&tab=logs
=> "Fix "500 internal error" in large groups

common/util/parse.ts, web/components/editor.tsx, web/lib/icons/bold-icon.tsx, web/lib/icons/italic-icon.tsx, web/lib/icons/link-icon.tsx
Add a medium-style highlight menu for formatting text and adding links
=> Add floating menu (bold, italic, link)

web/components/contract-search.tsx, web/components/contract-select-modal.tsx, web/components/editor/market-modal.tsx, web/pages/group/[...slugs]/index.tsx
- Refactor so that add markets on groups page and add market embeds have similar style
- Fix bug where search bar doesn't stick
=> Adjust market modal styles

web/components/contract/contract-details.tsx
=> market close fix oopsies

web/components/contract/contract-details.tsx, web/hooks/use-is-mobile.ts
=> Adjust market header style

common/envs/dev.ts, common/envs/prod.ts, web/lib/twitch/link-twitch-account.ts
WIP. Stuff related to getting the Twitch bot running on our Google Cloud deployment will go here.
=> Twitch bot deployment work

web/components/contract/contract-tabs.tsx, web/components/feed/contract-activity.tsx
This is making progress towards the "we don't require all the bets in the universe to render the contract page" world.
=> Render free response comment threads more simply without bets

web/components/liquidity-panel.tsx
Feel free to merge this in if subsidies become a problem.
=> Hide liquidity panel

web/pages/[username]/[contractSlug].tsx
More or less self-explanatory, I am factoring this out so that it doesn't cause a re-render on "the big guy" when the recommended contracts come in.
=> Move recommended contracts to own widget

web/components/contract/contract-tabs.tsx, web/pages/[username]/[contractSlug].tsx
This is just a cleaner place to put it.
=> Extract signup UI from contract tabs component

web/components/answers/answers-panel.tsx
Just fixing things I noticed when I was reading this code.
=> Clean up some stuff in `AnswersPanel`

web/components/contract-search.tsx
=> cleaning up search bar for mobile

web/components/contract/contract-prob-graph.tsx
=> simplify binary graphs

web/components/comment-input.tsx, web/components/feed/feed-answer-comment-group.tsx, web/components/feed/feed-comments.tsx, web/posts/post-comments.tsx
It's nice to clean this up since invalid states should be unrepresentable.
=> Eliminate redundant showReply/replyTo state in comment threads

web/components/answers/answers-panel.tsx
This is more straightforward and fixes at least three small bugs:
1. It handles the case where the winning answer has no bets (weird but possible.)
2. It correctly prints "No answers yet" iff there are no answers (it previously also printed this if there was just one answer, which makes no sense.)
3. It correctly doesn't print the winning answer twice when there is exactly one answer which is winning and no other losing answers.
See https://manifold.markets/AnselFreniere/what-is-the-best-data-source-for-th for an example of a market that demonstrates both bugs 2 and 3.
=> Clean up and fix stuff on answers panel

web/components/charts/generic-charts.tsx
Self-explanatory. A good market to test this on is https://manifold.markets/FRCassarino/what-will-i-build-in-the-manifold-h.
=> Limit max width of FR legend tooltip labels

web/components/avatar.tsx, web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/numeric.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx
This seems like a cool and helpful thing to put in the tooltip, it's easy to do, so let's put it in and see if people like it.
I was going to put in probability changes too, but I think there could be something weird about the `probBefore` data in the DB, so I am not going to do that until I know the data is actually right.
=> Refactor chart tooltip stuff, add bet avatar to tooltips

web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx
These are things I accidentally recently broke, but now they are fixed.
=> Fix a couple small chart bugs

web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/numeric.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx
This was a little hairy and now it's better.
=> Improve typing for chart tooltip stuff

common/util/parse.ts, common/util/tiptap-spoiler.ts, web/components/editor.tsx
=> Add ||spoilers||

web/components/charts/helpers.tsx
Now in the left and bottom three quarters of the chart, the tooltip will be above and to the right of the pointer, which seems like the most "natural" place for it to appear, and near the right and top edges, it will migrate to the other side of the pointer.
It's possible that a "fancy" implementation where we carefully measure the displayed tooltip size and then animate the tooltip movement when it gets near the edges would be very nice, but this is a quick fix to the status quo where it sloppily goes out of the charts.
FYI @ingawei
=> Keep tooltip within bounds of chart

web/components/amount-input.tsx, web/components/bet-panel.tsx
Stop doing this, it's no good, resizing should be fast.
=> Don't render stuff whenever window size changes

web/components/charts/helpers.tsx
Now the chart tooltips seriously won't make scrollbars on embeds, even small crappy embeds.
=> Size-aware chart tooltip positioning

common/group.ts, firestore.rules, functions/src/create-group.ts, functions/src/scripts/convert-tag-to-group.ts, web/components/contract-search.tsx, web/components/contract-select-modal.tsx, web/components/contract/contracts-grid.tsx, web/components/groups/group-overview-post.tsx, web/components/groups/group-overview.tsx, web/components/pinned-select-modal.tsx, web/components/post-card.tsx, web/pages/group/[...slugs]/index.tsx
=> Overview page on groups

web/components/analytics/charts.tsx, web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx, web/components/charts/stats.tsx, web/components/contract/contract-overview.tsx, web/components/sized-container.tsx, web/pages/stats.tsx
Now the stats page uses the new graphs, so we remove the Nivo dependency, we get consistent look and feel, tooltips, zooming, speed, etc.
=> Rewrite stats graphs using new machinery

common/notification.ts, common/user-notification-preferences.ts, common/util/format.ts, functions/src/scripts/add-new-notification-preference.ts, functions/src/unsubscribe.ts, web/components/bet-button.tsx, web/components/notification-settings.tsx, web/components/play-money-disclaimer.tsx, web/components/scroll-to-top-button.tsx, web/components/switch-setting.tsx, web/pages/[username]/[contractSlug].tsx
Users can opt out of all notifications except market closure notifications. I added a link when unsubscribing to an email type to unsubscribe to all unnecessary email notifications.
=> Allow user to opt out of all unnecessary notifications

web/components/groups/group-overview.tsx
Adds loading indicator to "Pinned items" in group overview.
=> Add spinner

web/components/onboarding/welcome.tsx
=> added mana cannot be traded for real money disclaimer in welcome modal

web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx
Now there's a little white and blue marker that follows the mouse on the graph.
The code for this is super hacky right now, intentionally so because probably we are gonna change some other stuff. I want to get this out there so Inga and I can wave the mouse around and think about how the tooltip and slice marker should interact.
=> Implement basic graph tooltip slice marker thingy

web/components/charts/helpers.tsx
=> made slice skinnier

web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/numeric.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx, web/components/charts/stats.tsx, web/components/portfolio/portfolio-value-graph.tsx
This may not be the final state, we are trying stuff out.
=> Tooltip follows marker on charts with marker

web/components/charts/generic-charts.tsx
=> Fix graph area to invert at 0

common/post.ts, functions/src/create-post.ts, web/components/create-post.tsx, web/components/groups/group-overview-post.tsx, web/components/groups/group-overview.tsx, web/components/pinned-select-modal.tsx, web/components/post-card.tsx, web/pages/date-docs/create.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/post/[...slugs]/index.tsx
- Moved the post tab into a section in the overview tab.
- Changed the post creation component into a modal.
- Added a required subtitle for posts which is now shown in the Post card and Post page.
- Added a "Post" badge for post cards.
=> Posts changes

web/components/contract/contract-mention.tsx, web/components/editor/contract-mention.tsx
=> Make %mentions actually look like mentions

web/components/bet-panel.tsx
=> getting rid of daisy for limit order button

web/components/create-post.tsx
=> made create a post button not daisy

web/components/answers/answers-panel.tsx, web/components/charts/contract/choice.tsx
Self-explanatory. Now we show the top 7 as of today, using nice colors Inga picked, and everything else becomes gray "other".
=> Update FR colors, consolidate non-top answers into "Other"

web/.gitignore, web/components/editor.tsx, web/components/editor/image-modal.tsx, web/package.json, web/pages/api/v0/dream.ts, yarn.lock
A subset of the changes in https://github.com/manifoldmarkets/manifold/pull/946, but excluding the /createcomment stuff
=> Generate images from StableDiffusion

web/components/contract/contract-details.tsx, web/components/contract/contract-mention.tsx, web/components/feed/copy-link-date-time.tsx, web/components/relative-timestamp.tsx, web/hooks/use-is-client.ts
I don't know if it matters very much, but I sure as heck am not gonna work on the contract page with the console spewing errors at me about it.
=> Fix some hydration issues

common/like.ts, web/components/button.tsx, web/components/contract/like-market-button.tsx, web/components/contract/tip-button.tsx, web/components/tipper.tsx, web/public/custom-components/coin.tsx, web/tailwind.config.js
=> added cancelling tipping and lil coin

web/components/groups/edit-group-button.tsx, web/components/groups/groups-button.tsx, web/hooks/use-group.ts, web/pages/group/[...slugs]/index.tsx
=> Put add markets/follow button above all group tabs

web/components/feed/feed-comments.tsx
Just tidying up and fixing the performance here to avoid re-rendering comments on subscription load. (See similar #1000.)
=> Clean up contract comment stuff

common/user.ts, firestore.rules, functions/src/change-user-info.ts, web/lib/firebase/users.ts, web/pages/[username]/index.tsx, web/pages/profile.tsx
=> Adds option to delete your account.

web/components/posts/post-card.tsx, web/hooks/use-post.ts, web/pages/home/index.tsx, web/pages/latestposts.tsx
=> Latest posts section on home

common/post.ts, functions/src/index.ts, functions/src/on-create-comment-on-post.ts, web/components/posts/post-card.tsx
=> Add comment count and amount tipped to Post Cards

web/components/contract/contract-info-dialog.tsx
This is my first contribution, I'm trying something small, to meet you guys and better understand how things work. 24 hour volume is something that I'm curious about often, so I think it would be a nice addition to this modal.
=> added 24 hour volume to the Market details Modal

web/components/comments/comment-input.tsx, web/components/feed/feed-answer-comment-group.tsx, web/components/feed/feed-comments.tsx, web/components/widgets/editor.tsx
=> comment changes

web/components/bet/bet-panel.tsx, web/components/widgets/amount-input.tsx
=> made the sliders color matched

common/envs/constants.ts
Yes, I'm just making this pull request so I can resolve https://manifold.markets/Yev/will-i-submit-at-least-1-pull-reque :sweat_smile:
=> Add ManifoldBugs and ACXBot to the list of bots

common/envs/constants.ts
Added a few more bots, some outdated.
=> More bots for the list

web/components/groups/group-about.tsx, web/components/posts/post-card.tsx, web/components/user-page.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/home/index.tsx
https://linear.app/manifoldmarkets/issue/MAN-101/group-overview-simplification
=> Changes to Group Overview

functions/src/update-user-metrics.ts
It's going to be a slog to make this actually efficient, but we can easily do some small things.
1. We don't need to reload contracts for each user, we already loaded them up front.
2. Firestore's `BulkWriter` seems more effective at getting updates out over the wire than making `WriteBatch`es directly. (Doing all the writes actually takes a small majority of the time of the current version, so it's worth optimizing.)
=> Some easy cleanups on `updateUserMetrics`

web/components/portfolio/portfolio-value-section.tsx, web/lib/icons/placeholder-graph.tsx
=> made buttons for graph

functions/src/update-user-metrics.ts
This was introduced in https://github.com/manifoldmarkets/manifold/commit/54b9fca5a078fefd0af9b18a8c71fa56a657e8a0 and got left out of the update metrics split, so our leaderboard was showing up weird.
=> Restore cached profit rank computation

web/components/contract/contract-card.tsx, web/components/feed/feed-comments.tsx
This is desirable because it makes it easy for people who don't like these to use their browser to hide them or change the display.
=> Add unique classes to dream comments, image contract cards

web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/numeric.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx, web/components/charts/stats.tsx, web/components/contract/contract-details.tsx, web/components/portfolio/portfolio-value-graph.tsx, web/components/portfolio/portfolio-value-section.tsx
=> move y axis on right side of graph

docs/docs/api.md, functions/src/create-comment.ts, functions/src/create-market.ts
=> Support markdown and html in Create Market API

web/pages/midterms.tsx
I made markets for the untracked governors races
=> Add governor markets to the midterm page

common/calculate-cpmm-multi.ts, common/contract.ts, web/hooks/use-global-config.ts, web/pages/frv2.tsx
https://www.notion.so/manifoldmarkets/Multi-CPMM-62fe5b99013c4d5a87dfa84e0b8fa642
=> Multi-CPMM mechanism

web/components/editor/emoji/emoji-suggestion.ts, web/tailwind.config.js
Now sort is emoticon -> starts with query (case insensitive) -> popularity
=> Fix emoji sort

web/components/leaderboard.tsx
=> Add bot tags in leaderboards

functions/src/update-contract-metrics.ts, functions/src/update-group-metrics.ts
This is definitely much better than the previous approach, so let's do it.
I would have changed `updateLoans` too but it's a whole other ball of wax to be tackled later.
=> Use `BulkWriter` in other metrics update functions

common/calculate-metrics.ts, functions/src/update-contract-metrics.ts
Now this only has to look at bets for the window of time it's computing probability changes for (one month atm), and unfilled limit bets for the purposes of computing elasticity.
=> Make `updateContractMetrics` only look at recent bets

web/pages/swipe/index.tsx
Removes the confusing 3 probability layout. Now the preview is shown while swiping left/right. This also gives user feedback that their swipe does something!
=> Show prob change & direction while swiping

functions/src/update-stats.ts
I don't think this is a big deal (although for testing stats computation locally it may be) but it's free so let's fix it.
=> Don't fetch unnecessary fields for stats computation

web/pages/[username]/[contractSlug].tsx
Yesterday James wrote https://github.com/manifoldmarkets/manifold/commit/c1f2dff1a813f3a32da0345d08e3341bf03a9ff0, the intent of which was to only establish a subscription to new bets, rather than re-subscribe to all the bets already in the static props.
Unfortunately, this fix wasn't working, because `listAllBets` doesn't return bets in sorted order. (`useBets` does.) So it was still loading some random, probably large subset of the old bets. Now the fix should be actually working.
=> Make contract bet loading actually efficient

web/components/landing-page-panel.tsx, web/pages/index.tsx
centers the homepage cards on tablet
=> Simplify homepage css

docs/docs/api.md, web/lib/firebase/users.ts, web/pages/api/v0/users.ts
Analogous to `/markets` API. We hit the Vercel size limit so this was absolutely necessary.
=> Implement paging in `/users` API

common/util/object.ts, functions/src/update-contract-metrics.ts, functions/src/update-user-metrics.ts
Not sure this is a big deal, but it kind of sucks to update stuff that doesn't need updating because it fires off people's subscription handlers, runs triggers, etc. etc.
=> Don't write unchanged docs in `updateContractMetrics`

common/envs/prod.ts, common/user.ts
Minor text fix, PAST_BET now uses the past tense "traded" instead of "trade".
=> Fix grammar on Notification Settings page

common/antes.ts, common/bet.ts, common/new-bet.ts, common/redeem.ts, common/sell-bet.ts, functions/src/accept-challenge.ts, functions/src/scripts/backfill-bet-flags.ts, functions/src/utils.ts, web/hooks/use-bets.ts, web/lib/firebase/bets.ts, web/pages/[username]/[contractSlug].tsx, web/pages/embed/[username]/[contractSlug].tsx
Pretty self-explanatory. There are certainly lots of redemptions in particular so this is reasonably valuable.
=> Backfill bet flags into DB so that we can use them in queries

functions/src/on-create-comment-on-contract.ts
Like #1187, I am not sure if this is super important, but if I want to find something missing, and it's hard to find, I start cleaning my house and see if it turns up.
=> Make `onCreateCommentOnContract` trigger more efficient

functions/src/redeem-shares.ts
What thou needest not, thou shalt not load.
=> Don't load user doc in `redeemShares`

web/components/bet/quick-bet.tsx
=> fixed multiple choice weirdness

docs/docs/api.md
This seems useful. Sorry if this is not wanted.
=> Update API changelog

common/calculate-metrics.ts, common/user.ts, docs/docs/api.md, functions/src/create-user.ts, functions/src/scripts/clean-local-firestore-db.ts, functions/src/update-user-metrics.ts, twitch-bot/common/types/manifold-api-types.ts, twitch-bot/common/types/manifold-internal-types.ts, web/pages/api/v0/_types.ts
I believe this was left over from when we used to have leaderboards ranking this, but after we removed them we forgot to clean it up.
=> Remove unnecessary creator volume computation

web/components/contract/contract-tabs.tsx, web/components/widgets/collapsible-content.tsx, web/lib/firebase/contract-metrics.ts, web/pages/[username]/[contractSlug].tsx
=> Show positions on top of trades in contract tabs

web/components/contract-search.tsx, web/components/contract-select-modal.tsx, web/components/contract/contract-card.tsx, web/components/contract/contract-details.tsx, web/components/contract/contracts-grid.tsx, web/components/editor/tiptap-grid-cards.tsx, web/components/pinned-select-modal.tsx, web/components/posts/post-card.tsx, web/components/user-page.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/groups.tsx, web/pages/search.tsx
This was supposed to be just a fix to the avatar/group link regression but man, soo many tiny style issues
Fixes MAN-215
=> Contract card UI Fixes

web/pages/worldcup.tsx
=> Fix weird markup on World Cup page

functions/src/serve.ts, web/pages/api/v0/market/[id]/add-liquidity.ts
This was broken in #1020. Now it's not.
=> Fix `/v0/market/[id]/add-liquidity` to work

package.json, yarn.lock
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/.
=> Typescript 4.9.3

common/package.json, common/util/parse.ts, functions/src/create-comment.ts, functions/src/create-market.ts, functions/src/utils.ts, web/package.json
This is a large package and there is no reason for it to be bundled with our website.
=> Don't depend on @tiptap/html in common

web/pages/api/v0/bet/cancel/[betId].ts, web/pages/api/v0/bet/index.ts, web/pages/api/v0/comment.ts, web/pages/api/v0/market/[id]/add-liquidity.ts, web/pages/api/v0/market/[id]/close.ts, web/pages/api/v0/market/[id]/resolve.ts, web/pages/api/v0/market/[id]/sell.ts, web/pages/api/v0/me.ts
Self-explanatory. It's nice to be able to make a local web UI for doing this stuff, and if people make good ones we can whitelist their website.
=> Whitelist Authorization header for CORS access on write API

web/components/buttons/copy-link-button.tsx, web/components/buttons/share-market-button.tsx, web/components/contract/creator-share-panel.tsx, web/components/groups/group-about.tsx, web/components/manalinks/create-links-button.tsx, web/pages/referrals.tsx, web/pages/styles.tsx
Style according to inga's copy link design for manalinks.
Add tooltip and checkmark to make copied state more clear
=> Re-style share link

functions/src/on-update-contract-follow.ts
=> Fix random contract follow triggers to not do extra work

common/calculate-metrics.ts, common/contract-metric.ts, functions/src/change-user-info.ts, functions/src/helpers/generate-and-update-avatar-urls.ts, functions/src/on-create-bet.ts, functions/src/scripts/backfill-contract-metrics-user-data.ts, functions/src/update-user-metrics.ts, web/components/contract/contract-tabs.tsx, web/hooks/use-contract-metrics.ts, web/lib/firebase/contract-metrics.ts, web/pages/[username]/[contractSlug].tsx
updates contract metrics onCreateBet, create and backfill contractMetrics with denormalized user data
=> Make contract metrics good for the front end

common/user.ts, functions/src/create-user.ts, functions/src/increment-streak-forgiveness.ts, functions/src/index.ts, functions/src/reset-betting-streaks.ts, web/components/profile/betting-streak-modal.tsx
=> Streak forgiveness

functions/src/replication/import.ts, functions/src/replication/transaction-log.ts, functions/src/replication/utils.ts, functions/src/utils.ts, functions/supabase/seed.sql
Continuing to productionize this work and add tools for monitoring, failure recovery, etc.
=> WIP continued Supabase improvements

common/util/promise.ts, functions/src/replication/import.ts, functions/src/replication/utils.ts, functions/supabase/seed.sql
Continuing to get this actually operating smoothly on production.
=> More Supabase fixes

functions/src/market-close-notifications.ts
=> Don't query resolved contracts unnecessarily

functions/src/replication/utils.ts
WIP because this seems like it should be a big win but I don't see it moving the graph? I don't get it. Maybe there's something I'm missing.
=> Keep Supabase connections open in memory

web/components/notifications/income-summary-notifications.tsx, web/components/notifications/notification-helpers.tsx, web/components/notifications/notification-types.tsx, web/hooks/use-notifications.ts, web/pages/notifications.tsx
=> Stop sticking income notifs to top

functions/src/replication/transaction-log.ts
This is optimizing throughput on the Supabase replication function, which is the path that wants to be as fast as possible. I might kill the Firestore transaction log entirely if I can validate that the pubsub-to-Supabase-or-failure-log path is bulletproof, which would be really nice.
=> Split Supabase replication off from Firestore transaction log record

common/util/promise.ts, functions/src/replication/import.ts, functions/src/replication/transaction-log.ts, functions/src/replication/utils.ts, functions/src/utils.ts
Just cleaning this up after my recent work.
=> Replication related refactoring

web/components/nav/bottom-nav-bar.tsx
I don't want to turn on webkit tap highlight color, it's just so ugly imo. Added this because I don't think we need immediate tap response for everything, but for the things we do I think this looks better
=> immediate response on tapping targets

web/components/user-page.tsx, web/components/widgets/image-with-blurred-shadow.tsx
=> made profile have blurred shadow

web/components/buttons/follow-market-button.tsx, web/components/comments/dropdown-menu.tsx, web/components/notifications/notification-dropdown.tsx, web/hooks/use-follows.ts
=> added dropdown items

functions/src/scripts/supabase-import.ts, functions/supabase/seed.sql, supabase-replicator/README.md, supabase-replicator/deploy.sh, supabase-replicator/package.json, supabase-replicator/src/index.ts, supabase-replicator/src/replicate-writes.ts
Everything seems to be working smoothly.
=> More Supabase stuff

supabase-replicator/supabase/seed.sql
This gets rid of the `processed` flag, which I think is unnecessary now, because there's no way an insert should get in without being successfully processed, and if the insert doesn't get in then the replicator machine should replay it.
This should fix a deadlock that we were observing under load, which I hypothesize to be caused by something like:
- Write batch A: update contract P, ..., update contract Q
- Write batch B: update contract Q, ..., update contract P
Now we always process writes to documents in a write batch in order by their document ID, so there should be no chance of a deadlock.
=> Improve Supabase replication trigger code

web/hooks/use-swipes.ts, web/lib/firebase/views.ts, web/pages/scroll/index.tsx, web/pages/swipe/index.tsx
Switching up the maniswipe UI to work by scrolling, where it snaps to each next card. Like TikTok.
=> Maniscroll

common/charity.ts
Added NAACPLDF and EWG to charities
=> Add charities

web/components/contract/extra-contract-actions-row.tsx, web/components/contract/like-button.tsx, web/components/contract/swipe-card.tsx, web/pages/swipe/index.tsx
=> Add likes to swipe card

common/transaction-log.ts, functions/src/log-writes.ts, functions/src/scripts/supabase-import.ts, supabase-replicator/supabase/seed.sql
Self-explanatory, things seem to be looking good so let's continue.
=> Replicate most of the rest of our DB to Supabase

common/transaction-log.ts, firestore.rules, functions/src/log-writes.ts, supabase-replicator/supabase/seed.sql
I want a table that I can just spam a bunch of writes at however I please and see how effectively they are replicated.
=> Add table for stress testing Supabase replication

common/envs/constants.ts
I want to make a trading bots and need bot tags, so I will not annoy people in the live feed
=> Give bot tags

web/components/activity-log.tsx
so it shouldn't list unlisted markets.
=> the live feed is a list

common/envs/constants.ts
https://manifold.markets/ZZZZZZ/will-smartbot-be-recognized-for-a-m#m9njcQQM4FPjgrbDMmJ6
=> Add me to the bot list

web/components/buttons/referrals-button.tsx, web/components/editor/mention-suggestion.ts, web/components/filter-select-users.tsx, web/components/groups/edit-group-button.tsx, web/lib/supabase/users.ts
Getting this in as a kind of proof of concept. Related to but not the same as #1288. The UI on this whole "add user to group" dialog still just kind of looks and works very badly. But now at least it doesn't also download our whole users DB when you click it.
=> Use Supabase to power "add user to group" dropdown

web/next.config.js, web/package.json, yarn.lock
I don't think there's anything big we care about here, just keeping up to date.
=> Next.js 13.0.2 -> 13.1.0

web/components/manalink-card.tsx
=> Web: Fix grammar in manalink UI

common/util/promise.ts, functions/src/drizzle-liquidity.ts, functions/src/scripts/calculate-mana-supply.ts, functions/src/scripts/clean-local-firestore-db.ts, functions/src/scripts/delete-email.ts, functions/src/update-contract-metrics.ts, functions/src/update-group-metrics.ts, functions/src/update-loans.ts, functions/src/update-stats.ts, functions/src/update-user-metrics.ts
`mapAsync` has a simpler interface and is better at sending concurrent requests faster.
=> Replace all batchedWaitAll with mapAsync

web/pages/group/[...slugs]/index.tsx
=> fixing placement of add market button

web/components/bet/limit-bets.tsx
=> improved user linking/tooltip in order book:

web/components/bet/limit-bets.tsx
=> getting rid of NO limit order resorting, is confusing when go to mobile

web/components/contract/contract-report-resolution.tsx
=> disabled flag button once flag is complete

functions/src/stripe.ts
As you can see, this function was a kind of anti-pattern that made the Stripe webhook and the loan update code worse.
EDIT: I backed out the refactoring because some stuff changed, so now this PR just fixes the Stripe webhook to be correct.
=> Remove suspicious `payUser` function, clean some things up

common/charity.ts
Added new charity: MSI Reproductive Choices
=> charity.ts: Add new charity MSI

functions/src/scripts/supabase-import.ts
This should allow us to continually make progress on importing documents even if the process fails bc we can start where we left off.
=> Process documents by timestamp

web/components/comments/dropdown-menu.tsx, web/components/contract-search.tsx, web/components/daily-stats.tsx, web/components/layout/page.tsx, web/components/nav/search-button.tsx, web/components/nav/sidebar.tsx, web/components/search/query-contracts.ts, web/components/search/query-users.ts, web/components/search/search-context.tsx, web/components/search/search.tsx, web/components/widgets/select.tsx, web/lib/util/device.ts, web/pages/_app.tsx, web/pages/contract-search-firestore.tsx, web/pages/home/index.tsx, web/pages/search.tsx
click search button in sidebar or keyboard shortcut cmd/ctrl k to bring up search modal
resolves MAN-647, MAN-500, MAN-634
=> Omnisearch

web/components/portfolio/portfolio-value-section.tsx, web/hooks/use-portfolio-history.ts, web/lib/supabase/portfolio-history.ts
waiting for the import-supabase to finish
=> Portfolio history -> supabase, from 1600 ms to 200ms

functions/src/scripts/supabase-import.ts, supabase-replicator/supabase/seed.sql, web/components/bet/bets-list.tsx, web/lib/supabase/bets.ts, web/lib/supabase/contract-metrics.ts, web/lib/supabase/contracts.ts
This is the dumbest way to move the portfolio queries over but on the plus side it only takes ~1000ms to load vs previous 3000ms-4000ms (on my profile) and it has no custom complex sql queries.
=> Move portfolio metrics queries to supabase

common/charity.ts
Addresses #1432 
https://archive.org/about/
https://archive.org/donate/
=> Add Internet Archive as a listed charity [#1432]

web/components/choices-toggle-group.tsx, web/components/new-contract-panel.tsx, web/package.json, yarn.lock
=> New switcher

web/components/daily-profit.tsx, web/components/profile/user-contracts-list.tsx, web/hooks/use-persistent-state.ts
What do you think of this persistent, revalidated state strategy? I took `setState` out of the return because I'm ignoring undefined states because when `savedValue` was read with a non-null saved value, the `useEffect` would overwrite it with undefined. In usePersistentState this wouldn't happen but I'm not sure why.
I'm going to merge this now for the improvement to the daily changed status but still curious to absorb your knowledge on this code.
=> Display hourly updated daily changed via contract-metrics sum

supabase-replicator/supabase/seed.sql, web/components/profile/user-contracts-list.tsx, web/lib/supabase/contracts.ts
=> Show unresolved markets on profile

common/charity.ts
I saw a bounty on the discord server for adding charities, and while the bounty was already claimed, there are two 501(c)3 charities I'm actively involved with that I would love to be able to donate to through Manifold. I've included them here.
=> Include Topos Institute and Haskell Foundation as available charities.

web/components/contract/contract-info-dialog.tsx, web/components/widgets/short-toggle.tsx
=> Add contract image to ... menu

web/components/contract-search.tsx, web/components/contract/contracts-list.tsx
=> Clean up small issues with the contract list

functions/package.json, web/components/contract/contracts-list-entry.tsx, web/components/contract/contracts-list.tsx, web/components/relative-timestamp.tsx, web/components/widgets/datetime-tooltip.tsx, web/components/widgets/tooltip.tsx, web/package.json, yarn.lock
The main motivation behind this was because I want the `ContractCard` to only render conditionally on hover (it's quite heavy, e.g. it subscribes to Firestore for the contract data) and I didn't see any reasonable way to use Tippy to do that.
As far as I can tell `floating-ui` is a better library and there's no reason for us to write code against Tippy.
=> Use `floating-ui` for contract list popup

web/components/contract/like-button.tsx, web/components/multi-user-transaction-link.tsx
I didn't know this existed, so it didn't work after I made my changes in #1485. Now it works.
=> Make mobile like list work again

supabase-replicator/supabase/seed.sql
These aren't super bad but they are a little bit expensive and it's easy to make them work better like this.
=> Tweak stuff related to "searching for contracts from same group" queries

supabase-replicator/supabase/seed.sql
These changes are kind of stupid (except for the index) because I am just trying to trick the planner. We need to move off JSON columns for some stuff like this I think so that it's not so fiddly.
=> Recommended contracts speedup

common/supabase/schema.ts, supabase-replicator/supabase/seed.sql, web/hooks/use-feed.ts
It sucks if this is slow so let's make it reasonable. Now it doesn't fetch all the contracts for the "default user" unless you actually don't have enough for yourself.
=> Fix up recommended contracts efficiency further

web/components/groups/group-about-section.tsx, web/components/widgets/expandable-content.tsx
=> fixed logged out and about showing twice bug

README.md, backend/functions/README.md, backend/scripts/README.md, backend/shared/src/init-admin.ts
=> Fix up READMEs

web/components/groups/group-member-modal.tsx, web/lib/supabase/group.ts
=> added search member function

web/pages/_app.tsx, web/public/opensearch.xml
https://stackoverflow.com/questions/14082568/how-to-let-google-detect-a-site-search-engine
https://developer.mozilla.org/en-US/docs/Web/OpenSearch
=> Add Opensearch (tab on chrome addy bar to search MF)

web/lib/supabase/bets.ts, web/pages/[username]/[contractSlug].tsx, web/pages/embed/[username]/[contractSlug].tsx
We need to make progress on the Firebase bill soon, so let's turn this on and see how it goes.
=> Load contract page and embed bets from Supabase again

web/lib/firebase/bets.ts, web/lib/supabase/bets.ts, web/pages/api/v0/bets.ts
Self-explanatory. The pagination approach is awkward but it will do for now.
=> Fetch bets in API via Supabase

web/package.json, yarn.lock
This doesn't have anything exciting for us, but at least there are some small QoL fixes. See https://nextjs.org/blog/next-13-2.
=> Next.js 13.1 -> 13.2

backend/functions/src/scheduled/update-recommended.ts, backend/scripts/recommend.ts, backend/shared/src/supabase/utils.ts, common/src/recommendation.ts, common/src/util/matrix.ts
This seems like a very big source of Firestore reads and it also is slow as shit (the loading process takes longer than half an hour) so let's use Supabase to make that not the case.
=> Do `updateRecommended` in Supabase

backend/functions/src/api/resolve-market.ts, backend/functions/src/scheduled/update-contract-metrics.ts, backend/functions/src/scheduled/update-group-metrics.ts, backend/functions/src/scheduled/update-recommended.ts, backend/shared/src/supabase/utils.ts, backend/supabase/seed.sql, common/src/supabase/utils.ts
Migrated `updatecontractmetrics` entirely and tidied up `updategroupmetrics` and `updaterecommended` a little bit, loading the last of their data from Supabase.
=> More Supabase migration

backend/functions/src/scheduled/update-user-metrics.ts
Self-explanatory. Now we load all the stuff in batch from SQL. I didn't rewrite all the actual calculations to be in batch since that would be a ton of work and I am sort of just trying to fight cost fires right now. This should be much faster and kill the cost.
=> Supabase-ify `updateusermetrics`

web/lib/service/analytics.ts
This Amplitude library is weirdly large, I have no idea what it does that takes so much code, but it's dozens of kilobytes even minified and compressed. So let's just load it dynamically, like we do with Sprig. (I just noticed this when I was glancing at the landing page loading profile.)
=> Dynamically import Amplitude when we want to track stuff

backend/discord-bot/src/api.ts, backend/discord-bot/src/commands/create.ts, backend/discord-bot/src/commands/index.ts, backend/discord-bot/src/commands/market-react-bets.ts, backend/discord-bot/src/commands/react-to-bet-on-market.ts, backend/discord-bot/src/commands/search.ts, backend/discord-bot/src/helpers.ts, backend/discord-bot/src/index.ts, backend/discord-bot/src/storage.ts
- adds /create function
- Deletes updating markets in memory after 2 days
- Deletes old searches if the collector has expired
=> Discord bot improvements

backend/api/deploy.sh, backend/api/src/change-user-info.ts
This was totally absurd, now it's bad but probably workable. We should prioritize un-denormalizing this data.
=> Change user info efficiency

backend/scripts/categorize.ts, backend/scripts/change-user-info.ts, backend/scripts/convert-tag-to-group.ts, backend/scripts/package.json, backend/scripts/redo-resolution-payouts.ts, backend/scripts/resolve-markets-again.ts, backend/scripts/tsconfig.json, yarn.lock
Just fixing some stuff that (mostly) I broke when I was doing the great API move.
=> Fix up scripts to build

web/lib/supabase/user.ts, web/pages/group/[...slugs]/index.tsx
I don't know if this was causing concrete problems or not, but it was ridiculous.
=> Fix static props to not load user data very inefficiently

web/pages/[username]/[contractSlug].tsx
This reverts commit 0dfd64b548d6c51d342726c8bacf7e2d8213d157.
=> Revert "replacing getContractFromSlug (#1611)"

backend/api/deploy.sh, backend/api/package.json, backend/api/src/app.ts, backend/api/src/get-supabase-token.ts, backend/shared/src/secrets.ts, backend/supabase/functions.sql, web/components/auth-context.tsx, web/lib/firebase/api.ts, web/lib/supabase/db.ts, yarn.lock
**WIP -- need to handle token refresh, subscriptions, and dev/prod security checks.**
To support Supabase RLS mostly, although it could also be useful for other things (RPCs can see your UID too.)
=> Auth to Supabase as Firebase user

backend/supabase/seed.sql, common/src/contract.ts
Self-explanatory, we want this for a variety of places where the planner is outputting crappy plans for contract queries.
=> Add native columns for many fields contracts table

backend/api/src/change-user-info.ts, backend/api/src/get-private-contract-by-slug.ts, backend/functions/src/scheduled/update-contract-metrics.ts, backend/functions/src/scheduled/update-group-metrics.ts, backend/functions/src/scheduled/update-stats.ts, backend/functions/src/scheduled/update-user-metrics.ts, backend/supabase/functions.sql, backend/supabase/seed.sql, backend/supabase/views.sql, common/src/supabase/contracts.ts, common/src/supabase/portfolio-metrics.ts, common/src/supabase/schema.ts, common/src/supabase/utils.ts, web/lib/supabase/contracts.ts
Self-explanatory, this is the point of having native columns.
=> Use native columns on contracts table when querying it

common/src/supabase/portfolio-metrics.ts
I just mucked this up in #1632.
=> Fix bug in portfolio history fetching

web/components/groups/add-contract-to-group-button.tsx
=> added lil lock icon to private group add button

native/App.tsx, native/android/app/build.gradle, native/app.json, native/ios/Manifold/Info.plist, native/lib/auth.ts, web/components/auth-context.tsx, web/components/notification-settings.tsx, web/lib/service/analytics.ts
Also should better handle links to the app after the OS has killed the webview.
=> Fix mobile sign out bug, add refresh push notification if previously denied

backend/supabase/functions.sql, backend/supabase/seed.sql, backend/supabase/views.sql, common/src/contract.ts
This should help out the planning for various trending/recommendation queries.
=> Use native column for contracts popularity score

web/components/buttons/sign-in-button.tsx, web/components/layout/page.tsx, web/hooks/use-ab-test.ts, web/lib/firebase/google-onetap-login.tsx, web/lib/service/analytics.ts, web/pages/_app.tsx, web/pages/index.tsx
Resolves MAN-74
with A/B test!
=> Add google one-tap

backend/functions/src/triggers/log-writes.ts, backend/scripts/supabase-import.ts, backend/supabase/seed.sql, common/src/supabase/schema.ts, common/src/supabase/utils.ts
These are useful for upcoming migration work.
=> Replicate user_notifications, post_comments tables

backend/functions/src/scheduled/score-contracts.ts, backend/functions/src/scheduled/update-contract-metrics.ts, backend/functions/src/scheduled/update-user-metrics.ts, backend/supabase/contracts/indexes.sql, backend/supabase/functions.sql, backend/supabase/seed.sql, common/src/calculate-metrics.ts, common/src/contract.ts
We don't need these anymore and we aren't likely to in the future.
=> Kill period unique bettors fields on contracts

backend/supabase/seed.sql, common/src/bet.ts, common/src/supabase/schema.ts
Pretty self-explanatory, we want these for a ton of reasons.
=> Add native columns for a variety of bet stuff

backend/supabase/functions.sql, backend/supabase/seed.sql, backend/supabase/views.sql, web/components/feed/feed-comments.tsx
This adds a new sql contract selection algorithm that prioritizes contracts with liked comments in users' feeds.
=> Select contracts with unseen comments

backend/functions/src/scheduled/update-recommended.ts, backend/shared/src/helpers/embeddings.ts, backend/supabase/functions.sql, backend/supabase/seed.sql, common/src/supabase/user-events.ts, web/lib/supabase/ads.ts
Planning to fully migrate this table afterwards (i.e. also writes).
=> Migrate user_events to Supabase native columns

backend/supabase/seed.sql, common/src/supabase/schema.ts, common/src/supabase/utils.ts, web/lib/firebase/users.ts, web/lib/firebase/utils.ts, web/lib/service/analytics.ts, web/lib/supabase/user-events.ts
This is a fair bit of writes and a lot of data so it's nice to get it off Firestore.
=> Migrate user_events table completely to Supabase

web/components/widgets/amount-input.tsx, web/pages/charity/[charitySlug].tsx
- Also fix a bug where clicking on the +10 button would refresh page due to it being inside a form
=> Make min charity donation +100

common/src/leagues.ts, web/components/widgets/countdown.tsx, web/components/widgets/info-tooltip.tsx, web/lib/util/time.ts, web/pages/leagues.tsx
Added some stuff to leagues.
Also modified the tooltip component so that if it has children it won't show the ugly question mark and instead added a dotted line to the text that can be hovered/clicked.
=> Improvements to leagues

backend/supabase/functions.sql, backend/supabase/seed.sql, web/lib/supabase/ads.ts
Self-explanatory. After this I will remove them from the data blob.
=> Use new user_events columns in queries and indices

web/components/quests-or-streak.tsx, web/pages/ancient.tsx
Adds an ancient markets page at manifold.markets/ancient. Also adds links to most quests to make them easier to complete.
=> Ancient markets page

backend/api/src/redeem-market-ad-reward.ts, backend/shared/src/run-txn.ts, common/src/boost.ts, common/src/txn.ts, web/components/contract/creator-share-panel.tsx, web/components/feed/feed-items.tsx
the fee is not stored on the ad, is just the same for every ad, so it'll apply to current ads
=> Reduce ad reward to M3, add a fee of M2

common/src/envs/constants.ts
I will soon start automatically trading with this alt and would like the bot tag.
=> Add MiraBot to bots list.

web/hooks/use-post-supabase.ts, web/lib/supabase/realtime/use-realtime.ts, web/lib/supabase/realtime/use-subscription.ts
Now that I have got the channel management stuff factored correctly into `useRealtimeChannel` I can reuse this code.
=> Change `useSubscription` to reuse code from `useRealtimeChannel`

common/src/envs/constants.ts
=> Add MetaculusBot to botlist

web/pages/stats.tsx
Stats now pull data directly from the API so they're always up to date. I've got a couple basic charts in at the moment, hoping to add more soon.
=> Update stats embed

backend/supabase/seed.sql, common/src/supabase/notifications.ts, common/src/supabase/realtime.ts, web/components/notifications-icon.tsx, web/hooks/use-notifications.ts, web/lib/firebase/notifications.ts, web/lib/supabase/realtime/use-realtime.ts, web/lib/supabase/realtime/use-subscription.ts, web/lib/util/local.ts, web/pages/notifications.tsx
Also introduces some new features to the realtime abstractions to support this case, e.g. `usePersistentSubscription`.
Visible functionality should be unchanged.
=> Read notifications from Supabase

backend/discord-bot/package.json, backend/replicator/package.json, package.json, twitch-bot/server/package.json, web/components/manalinks/create-links-button.tsx, web/package.json, yarn.lock
Self-explanatory. I don't think there's anything very exciting in Typescript 5, but there's no reason not to bump.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/
=> Update & deduplicate some deps, Typescript 4.9 -> 5.0

web/components/contract/contracts-table.tsx, web/components/feed/feed-timeline-items.tsx, web/components/news-article.tsx
There are some pre-existing bugs I'll figure out later
- content overflows on mobile
- news content is weird
=> made news thingy

web/components/bet/quick-bet.tsx, web/components/contract/feed-contract-card.tsx
=> tweaking smaller contract card"

web/components/contract/contract-description.tsx, web/components/contract/contract-edit-history-button.tsx, web/lib/util/isContentEmpty.ts, web/pages/[username]/[contractSlug].tsx
=> clean up buttons"

backend/api/src/add-bounty.ts, backend/api/src/app.ts, backend/scripts/add-new-notification-preference.ts, backend/shared/src/create-notification.ts, backend/shared/src/txn/run-bounty-txn.ts, common/src/notification.ts, common/src/txn.ts, common/src/user-notification-preferences.ts, web/components/contract/bountied-question.tsx, web/components/contract/contract-info-dialog.tsx, web/components/notification-settings.tsx, web/components/notifications/notification-types.tsx, web/components/widgets/amount-input.tsx, web/lib/firebase/api.ts
added award bounty functionality:
=> adding bounty functionality

web/components/contract/contract-card.tsx, web/components/contract/contracts-table.tsx, web/components/contract/feed-contract-card.tsx, web/components/contract/prob-change-table.tsx, web/components/contract/related-contracts-widget.tsx, web/components/swipe/swipe-card.tsx, web/hooks/use-contract-supabase.ts, web/pages/[username]/[contractSlug].tsx, web/pages/embed/[username]/[contractSlug].tsx, web/pages/todays-updates.tsx
This reverts commit 042d7172367043f4d5b9ffeb4ac73a91ff985c7c.
=> Revert "changing back to realtime, see if that works (#1898)"

web/pages/leaderboards.tsx
This reverts commit 9058803306baa0ed7e479774b5bda8ba1ab791ac.
=> Revert "temporarily delete leaderboards"

backend/api/src/add-contract-to-group.ts, backend/api/src/create-market.ts, backend/api/src/create-post.ts, backend/functions/src/triggers/on-create-contract.ts, backend/shared/src/update-group-contracts-internal.ts, backend/supabase/seed.sql, web/components/buttons/duplicate-contract-button.tsx, web/components/groups/contract-groups-list.tsx, web/components/groups/group-selector.tsx, web/components/new-contract/contract-params-form.tsx, web/components/new-contract/new-contract-panel.tsx, web/pages/create.tsx
=> Add multi group on create

common/src/envs/constants.ts
This is an AI bot that can generate questions and invest in markets.
=> Add Seldon Bot

common/src/group.ts, web/components/profile/user-contracts-list.tsx, web/components/supabase-search.tsx, web/pages/group/[...slugs]/index.tsx, web/pages/search.tsx
This reverts commit 313e14e09ce470f95359ae6e738423f2525d2d2f.
=> Revert "things (#1917)"

backend/api/src/award-q-and-a-answer.ts, backend/api/src/claim-manalink.ts, backend/api/src/send-mana.ts, backend/api/src/stripe-endpoints.ts, backend/api/src/validate-iap.ts, backend/scripts/backfill-stripe-purchase-txns.ts, backend/shared/src/resolve-market-helpers.ts, backend/shared/src/txn/run-txn.ts, common/src/txn.ts
=> Log and backfill stripe purchase txns

backend/api/src/get-contract-params.ts, common/src/bet.ts, common/src/chart.ts, common/src/supabase/bets.ts, common/src/util/og.ts, web/components/charts/contract/choice.tsx, web/pages/[username]/[contractSlug].tsx
this fixes issue with charts loading wayy too much data via firebase oops
=> Send compressed points through static props

common/src/envs/constants.ts
I'd like to register my account as a bot :)
=> Add bot tag for @ManaMaximizer

web/components/groups/group-options.tsx
Fixes share link in the new questions interface.
=> Fix topic links in new questions interface

common/src/envs/constants.ts
It's my bot. 
Username at https://manifold.markets/ArkPoint
Code at https://replit.com/@Bohaska/manifoldarkpoint
=> Add ArkPoint to bot list

web/pages/payments.tsx
=> Updated displaying for fine managrams

common/src/envs/constants.ts
https://manifold.markets/mirrorbot
=> add bot tag to mirrorbot

common/src/envs/constants.ts
Adding my bot user. I also have seen a few others without the bot tag, but not sure on the exact procedure there.
https://manifold.markets/ithaca
https://manifold.markets/BottieMcBotface
=> Add new bot user

backend/api/src/app.ts, backend/api/src/create-private-user-message-channel.ts, backend/api/src/create-private-user-message.ts, backend/supabase/private-user-messages.sql, backend/supabase/seed.sql, common/src/chat-message.ts, common/src/supabase/realtime.ts, common/src/supabase/schema.ts, web/components/buttons/more-options-user-button.tsx, web/components/chat-message.tsx, web/components/comments/comment-input.tsx, web/components/contract/back-button.tsx, web/components/messaging/messages-icon.tsx, web/components/messaging/send-message-button.tsx, web/components/nav/bottom-nav-bar.tsx, web/components/nav/sidebar.tsx, web/components/topics/league-chat.tsx, web/hooks/use-private-messages.ts, web/hooks/use-user-supabase.ts, web/lib/firebase/api.ts, web/lib/supabase/private-messages.ts, web/lib/supabase/realtime/use-subscription.ts, web/pages/[username]/index.tsx, web/pages/messages/[channelId].tsx, web/pages/messages/index.tsx
=> Private messages

backend/api/src/app.ts, backend/api/src/create-lover.ts, backend/api/src/update-lover.ts, backend/supabase/love/love_user.sql, web/components/widgets/choices-toggle-group.tsx, web/hooks/use-lover.ts, web/lib/firebase/api.ts, web/pages/love/signup.tsx
don't have photos working yet, but creation and updating just as a proof of concept is up on dev
=> WIP required and update forms

common/src/charity.ts
This is for https://www.thoroughbreddailynews.com who are planning to introduce their large audience to Manifold and embed our markets in their articles.
=> Add horse charities for TDN

web/pages/payments.tsx
=> Recieve Mana -> Receive Mana

love/pages/[username]/index.tsx
Convert into feet and inches for display
=> love: Format height

backend/supabase/seed.sql, common/src/supabase/schema.ts
Migrating manalinks fully over to Supabase.
=> Add native columns to manalinks table

backend/functions/src/index.ts, backend/functions/src/scheduled/repack-supabase.ts
This job is taking a long time and not getting through everything, so we need to do better.
=> Disable scheduled repack job for now

backend/supabase/seed.sql
This index is for looking up who already got loan payouts.
=> Add index to notifications table to serve loan payout code

backend/api/src/place-bet.ts, backend/functions/src/triggers/on-create-bet.ts, backend/shared/src/create-notification.ts, backend/shared/src/supabase/bets.ts, backend/supabase/seed.sql, common/src/bet.ts, common/src/comment.ts, common/src/contract-params.ts, common/src/notification.ts, common/src/supabase/bets.ts, common/src/supabase/comments.ts, web/components/bet/bet-panel.tsx, web/components/contract/contract-tabs.tsx, web/components/feed/feed-bets.tsx, web/components/feed/feed-comments.tsx, web/components/notifications/notification-types.tsx, web/hooks/use-comments-supabase.ts, web/hooks/use-feed-timeline.ts, web/lib/supabase/comments.ts
=> Bet replies to comments

love/components/profile-carousel.tsx
This PR introduces a naive lightbox effect for photos in the carousel by leveraging the existing Modal component.
=> Implement Naive Lightbox on Profile Carousel Photos

backend/shared/src/add-interesting-contracts-to-feed.ts, backend/supabase/users/create.sql, backend/supabase/users/indexes.sql, backend/supabase/users/triggers.sql, common/src/supabase/schema.ts
Good stats on this column should help the query planner in the feed code.
=> Add `created_time` native column to users

backend/functions/src/scheduled/add-trending-feed-contracts.ts, backend/shared/src/add-interesting-contracts-to-feed.ts
Obviously this is just nice to do. I want to try this and watch it for a while and see whether it still ends up running twice, or whether this in practice addresses the issue.
=> Make `addcontractstofeed` v2 scheduled function

common/src/envs/constants.ts
I am the owner of the account and am running a small scale bot off it. I would like the bot tag on it if that is ok. Thanks and have a good one
=> Add @Sayaka as a bot account

web/components/profile/loans-modal.tsx
Misspelling of hypothetical question title in loans info
=> Millionare -> Millionaire

love/components/lover-about.tsx
sophia does not have push permissions to her branch in #2156 so this PR replaces it
=> More natural descriptions (stolen)

backend/api/src/cancel-bet.ts, backend/api/src/sell-bet.ts, common/src/api-market-types.ts, docs/docs/api.md, web/pages/api/v0/bets.ts
These are simple things that address feedback from Isaac and others.
=> Misc. low-effort API improvements

common/src/chart.ts, web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/contract/numeric.tsx, web/components/charts/contract/pseudo-numeric.tsx, web/components/charts/contract/stonk.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx, web/components/charts/time-range-picker.tsx, web/components/charts/zoom-slider.tsx, web/components/contract/contract-overview.tsx, web/components/feed/feed-chart.tsx, web/components/portfolio/portfolio-value-graph.tsx, web/components/portfolio/portfolio-value-section.tsx, web/pages/embed/[username]/[contractSlug].tsx, web/pages/week/[username]/[rangeEndDateSlug].tsx
- zoom track, slider, buttons, gestures single source of truth
- gestures kept in sync with fancy calculation
- fix bug where label is wrong
- add back click & drag zoom
- add pinch zoom on touch devices
Resolves MAN-1318
=> Mega Refactor charts

common/src/envs/constants.ts
=> Add my bot name

backend/api/package.json, common/src/api-market-types.ts, web/package.json, yarn.lock
Just throwing out more gobs of crap.
=> Kill random dead dependencies

backend/api/src/app.ts, backend/api/src/helpers.ts, backend/api/src/v0/markets.ts, backend/shared/src/supabase/init.ts, dev.sh, web/lib/api/proxy.ts, web/lib/supabase/contracts.ts, web/pages/api/v0/markets.ts
Doing one as a proof of concept so we can get the organizational details and the Cloud CDN stuff (the GCP implementation of Vercel's caching) all working.
=> Port /v0/markets to api.manifold.markets

web/components/editor/embed-modal.tsx
Hey! This should make it possible to embed Streamlit apps in Manifold comments and descriptions, so that for example people can play with new ways to visualize markets.
=> Allow Streamlit embeds

backend/api/src/app.ts, backend/api/src/create-chart-annotation.ts, backend/api/src/delete-chart-annotation.ts, backend/shared/src/supabase/contract_comments.ts, backend/supabase/chart_annotations.sql, backend/supabase/seed.sql, common/src/contract-params.ts, common/src/contract.ts, common/src/supabase/chart-annotations.ts, common/src/supabase/realtime.ts, common/src/supabase/schema.ts, web/components/annotate-chart.tsx, web/components/charts/contract/binary.tsx, web/components/charts/contract/choice.tsx, web/components/charts/generic-charts.tsx, web/components/charts/helpers.tsx, web/components/contract/contract-overview.tsx, web/components/feed/feed-comments.tsx, web/hooks/use-chart-annotations.ts, web/hooks/use-comments-supabase.ts, web/lib/firebase/api.ts, web/pages/[username]/[contractSlug].tsx
=> Annotate charts

backend/api/src/update-market.ts, common/src/contract.ts, web/components/answers/answers-panel.tsx, web/components/contract/contract-overview.tsx, web/lib/firebase/api.ts
https://linear.app/manifoldmarkets/issue/MAN-1376/market-creator-should-be-able-to-set-default-sort-default-value-for
discussed with ian
=> initial update sort behavior

web/components/contract/contract-info-dialog.tsx
Fixed a whole typo (I know amazing dev work from Rucker).
=> Fix typo in contract-info-dialog.tsx

common/src/envs/constants.ts
Run by StopPunting (some manual trades were done in the past, for streak bonuses, but won't be again).
=> Add FirstBot to bots

common/src/envs/constants.ts
Blessed be the day, a new baby bot is born! Truly, any bot born on the good Lord's day must be a benevolent bot! Bless Bawt! Bless Bawt! Hip Hip! Horray!
So far, no strong strategies, but I would like to take on [this bounty](https://manifold.markets/EvanDaniel/arb-bots-for-confident-markets) with `mmm`
https://github.com/Axel-Jacobsen/mmm
https://manifold.markets/bawt
Also, I'm relatively fresh to Rust, so `mmm` might have awful, non-idiomatic code. Let me know if this is the case.
=> add bawt to bots

web/components/bet/user-bets-table.tsx, web/components/charts/minibar.tsx, web/components/contract/contracts-table.tsx, web/pages/[username]/index.tsx, yarn.lock
This reverts commit 514740c333165b75a87af850c7ba38cf3973a220.
=> Revert "make thingy not float (#2252)"

web/components/supabase-search.tsx, web/hooks/use-debounced-effect.ts
This is kind of common sense, the previous version was really spammy.
=> Add 100ms debounce to search query box on browse page

backend/api/Dockerfile, backend/api/debug.sh
Now we can attach the Chrome debugger to our API server process, so we can e.g. get a heap snapshot and debug memory leaks.
=> API deployment tweaks

backend/shared/src/helpers/search.ts
=> Fix more search queries to not blow up

backend/api/src/app.ts
Sinclair tried to unrestrict the documented public API routes, but her code wasn't working correctly because `app.options('/v0', ...)` doesn't implicitly mean "everything under v0". So they were still serving only Manifold origins in their `OPTIONS` requests.
It makes no sense to me why we would distinguish between our documented and undocumented API routes when it comes to CORS headers, so if we want our API to have laissez-faire CORS headers, let's just make the whole thing that way.
FYI @sipec
=> Unrestrict CORS origins on API routes

common/src/envs/constants.ts
They basically only bet via limit orders placed through the API
=> Mark TenShino as a bot

web/components/editor/embed-modal.tsx
discussed with james -- see QA for new embed
=> add FRED embed to allowlist and show toast when embed is not in whitelist

common/src/answer.ts, web/components/buttons/duplicate-contract-button.tsx
tested - http://localhost:3000/ManifoldPolitics/which-party-will-win-the-us-preside-26a1eb1b8ce6
=> fix duplication of other when it is bad

backend/api/src/create-user.ts, backend/supabase/user_seen_markets.sql, common/src/supabase/analytics.ts, common/src/supabase/schema.ts
=> Kill the `data` blob in `user_seen_markets`

web/components/answers/answer-resolve-panel.tsx, web/components/contract/contract-overview.tsx
Copied gradient wrapper and header from the main resolution panel so that UX matches and user can close the panel. 
Discord request: https://discord.com/channels/915138780216823849/1193668076516945950
=> [Web] Add ability to close multiple independent resolve panel

web/components/college-experimental/new-contract-college/contract-params-form.tsx
=> Descision -> Decision

common/src/envs/constants.ts
https://manifold.markets/subooferbot?r=b2g
=> Mark subooferbot as a bot

common/src/envs/constants.ts
Add the bot tag to my bot account @WrenTec
https://manifold.markets/WrenTec
=> Mark WrenTec as a bot

common/src/envs/constants.ts
Adding my bot to the list
https://manifold.markets/manakin
=> Add manakin to bot list

web/lib/service/analytics.ts
It's important for us to do this, because we need to use the Amplitude user ID when recording `user_events` and contract views in Postgres, so if Amplitude isn't loaded yet then it doesn't work right, and records events with no user ID when a logged-in user loads the page. It's possible we could rewrite our code to order everything more cleverly but the easy thing to do is just not do the fancy async loading.
=> Load Amplitude synchronously

web/components/contract/user-positions-table.tsx
If more than 4 answers on multiple choice, hide carousel and use select instead.
=> [WEB] Select Answer in Positions If Many Answers

backend/api/src/app.ts, backend/api/src/pin-comment.ts, common/src/api/schema.ts, common/src/comment.ts, common/src/contract-params.ts, common/src/contract.ts, common/src/supabase/comments.ts, love/components/comments/love-comments-button.tsx, love/pages/[username]/[contractSlug].tsx, politics/app/[username]/[contractSlug]/contract-page.tsx, politics/app/[username]/[contractSlug]/get-contract-params.ts, web/components/comments/comments-button.tsx, web/components/comments/comments-list.tsx, web/components/contract/contract-tabs.tsx, web/components/feed/feed-comments.tsx, web/hooks/use-hash-in-url-page-router.ts, web/hooks/use-hash-in-url.ts, web/pages/[username]/[contractSlug].tsx
Didn't test it yet since my local environment still scuffed.
So the pinned comment UI might need iterating on.
=> pinned comments

backend/functions/src/scheduled/weekly-portfolio-updates.ts, backend/supabase/weekly-update.sql, common/src/supabase/schema.ts, firestore.rules, web/pages/week/[username]/[rangeEndDateSlug].tsx
need to test
we don't need to backfill the old weekly updates. do we?
Resolves MAN-1408
=> Migrate weekly updates to supabase

common/src/envs/constants.ts
Going to start moving my bot-related activity to CharlesLienBot.
=> Add CharlesLienBot as bot.

common/src/contract.ts, web/components/answers/answer-components.tsx, web/components/answers/answers-panel.tsx, web/components/answers/binary-answers-panel.tsx, web/components/answers/binary-multi-answers-panel.tsx, web/components/bet/bet-panel.tsx, web/components/bet/bet-summary.tsx, web/components/bet/sell-row.tsx, web/components/buttons/warning-confirmation-button.tsx, web/components/charts/contract/binary.tsx, web/components/contract/contract-overview.tsx, web/components/contract/user-positions-table.tsx, web/components/outcome-label.tsx, web/hooks/use-save-binary-shares.ts, web/pages/embed/[username]/[contractSlug].tsx
=> [Hackathon] Special case sumToOne MC markets with 2 answers as a binary market

backend/api/deploy-api.sh, backend/scheduler/deploy-scheduler.sh
This has two benefits:
1. It's much faster. Running a build on Cloud Build typically took me about a minute and thirty seconds. Running it locally and pushing it to Google if all I changed was the code (i.e. it doesn't have to do a new `yarn install`) takes about 5 seconds. (Of course, the part where it deploys the new container didn't get any faster.)
2. As long as it's using vanilla Docker and not some Google thing, it's easy for anything to build it. For example we can easily wire it up to GitHub Actions, which we should.
You should be able to just follow the instructions to install Docker on your platform, and then follow these instructions to authenticate your local Docker to Google so that you can do `docker push` to Artifact Registry: …
=> Change deploy for scheduler, API to do local docker build

backend/functions/src/email-templates/welcome.html, common/src/group.ts, politics/components/loading/loading-user-rows.tsx, web/components/contract/related-contracts-widget.tsx, web/components/home/welcome-topic-sections.tsx, web/components/leaderboard.tsx, web/components/nav/bottom-nav-bar.tsx, web/components/nav/sidebar.tsx, web/components/supabase-search.tsx, web/components/topics/browse-topic-pills.tsx, web/components/topics/questions-topic-title.tsx, web/components/topics/topic-options.tsx, web/next.config.js, web/pages/browse/[[...slug]].tsx
=> Static topics

backend/api/src/get-ad-analytics.ts, backend/api/src/get-seen-market-ids.ts, backend/shared/src/add-interesting-contracts-to-feed.ts, backend/shared/src/create-feed.ts, backend/shared/src/helpers/embeddings.ts, backend/shared/src/helpers/seen-markets.ts, backend/shared/src/interesting-markets-email-helpers.ts, backend/shared/src/update-contract-views.ts, backend/supabase/functions.sql, backend/supabase/group_contracts.sql, backend/supabase/user_contract_views.sql, common/src/api/schema.ts, web/hooks/use-feed-timeline.ts, web/hooks/use-has-seen-contracts.ts, web/lib/supabase/user-events.ts, web/pages/admin/journeys.tsx
See https://github.com/manifoldmarkets/manifold/pull/2422.
I tested most of these queries and as expected the new version typically is a big perf improvement.
=> Migrate all reads to `user_seen_markets` to use `user_contract_views`

common/src/envs/constants.ts
https://manifold.markets/brake
=> Add bot 'brake'

.github/workflows/test.yml, common/src/supabase/contracts.test.ts
This pull request introduces unit tests for common/src/supabase/contracts.ts.
Added unit tests in common/src/supabase/contracts.ts covering:
- getContracts: Tests for empty input, correct contract retrieval, chunking over 300 IDs, and error handling.
- getContractsByUsers: Verifies correct grouping of contracts by user IDs.
- getAnswersForContracts: Ensures answers are properly grouped by contract ID.
- getContractFromSlug: Confirms null return for non-existent contract slugs.
| File          | % Stmts | % Branch | % Funcs | % Lines |
|---------------|---------|----------|---------|---------|
| **All files**     | **72.18** | **56.52** | **47.36** | **70.9**  |
| calculate     | 78.57   | 66.66    | 40      | 76.92   |
| uniswap2.ts   | 78.57   | 66.66    | 40      | 76.92   |
| …
=> Added units tests for common/src/supabase/contracts.ts

common/src/envs/constants.ts
Profile: https://manifold.markets/brontobot
Bot of: https://manifold.markets/kenakofer
=> Add BrontoBot to constants.ts

web/components/contract/user-positions-table.tsx
This shows the `invested` amount of each user under their shares/profit in the positions tab
=> Show spent mana in positions tab

backend/api/src/create-market.ts, backend/shared/src/create-notification.ts, common/src/api/market-types.ts, common/src/calculate-cpmm-arbitrage.ts, common/src/contract.ts, common/src/multi-numeric.ts, web/components/answers/numeric-bet-panel.tsx, web/components/bet/bet-summary.tsx, web/components/buttons/duplicate-contract-button.tsx, web/components/charts/contract/multi-numeric.tsx, web/components/charts/generic-charts.tsx, web/components/contract/contract-price.tsx, web/components/new-contract/contract-params-form.tsx, web/components/new-contract/multi-numeric-range-section.tsx, web/components/new-contract/new-contract-panel.tsx, web/components/widgets/slider.tsx
New bucket selector
Using precision instead of bucket count
=> Multi numeric many buckets

common/src/envs/constants.ts
Setting up a bot account: https://manifold.markets/OracleBot
My regular account: https://manifold.markets/Tyler31
This is my first attempt at a PR on a public repo; please, let me know if I've done anything wrong.
=> add OracleBot to constants

web/components/contract/contracts-table.tsx
(my local build is broken for some reason, so testing via Vercel preview)
=> Make MC answers in Browse more faint

web/lib/firebase/users.ts, web/pages/login.tsx
**Note: This change requires enabling Login with Apple for the web app within the Firebase Console before it will work, I don't have access. Hopefully its just a toggle since there is already login with apple for mobile.** 
This PR is intended to be a workaround for users that have created accounts via apple on mobile and are unable to sign in on web. It's a separate page that nothing else links to for now.
=> [WEB] Basic Apple Login

backend/api/src/app.ts, backend/api/src/multi-sell.ts, backend/api/src/place-multi-bet.ts, backend/shared/src/create-notification.ts, common/src/api/schema.ts, common/src/calculate-cpmm-arbitrage.ts, common/src/multi-numeric.ts, common/src/sell-bet.ts, common/src/util/math.ts, web/components/answers/numeric-bet-panel.tsx, web/components/answers/numeric-sell-panel.tsx, web/components/bet/bet-summary.tsx, web/components/charts/generic-charts.tsx, web/components/feed/feed-multi-numeric-bet-group.tsx
=> Multi number sell

backend/api/.eslintrc.js, backend/shared/.eslintrc.js, backend/shared/src/gcp-metrics.ts, backend/shared/src/supabase/dashboard.ts, backend/shared/src/supabase/init.ts, backend/shared/src/supabase/users.ts, common/.eslintrc.js
I want to know whether connection pool exhaustion ever causes an outage, and whether anything surprising is happening with the pool.
=> Record more Postgres connection metrics from our API

backend/api/src/app.ts, backend/shared/src/monitoring/metric-writer.ts, backend/shared/src/monitoring/metrics.ts, common/src/util/math.ts
Now we can see a latency breakdown graph by endpoint.
=> Log custom metrics for HTTP requests

backend/api/package.json, backend/api/src/app.ts, backend/api/src/broadcast-test.ts, backend/api/src/create-comment.ts, backend/api/src/create-market.ts, backend/api/src/place-bet.ts, backend/api/src/serve.ts, backend/api/src/websockets/server.ts, backend/api/src/websockets/switchboard.ts, backend/scripts/websocket-test.ts, backend/shared/src/monitoring/metrics.ts, common/src/api/websocket-client.ts, common/src/api/websockets.ts, web/hooks/use-api-subscription.ts, web/lib/api/ws.ts, web/pages/websocket-live.tsx, yarn.lock
***WIP - I literally didn't run this code yet, I just want to get it out there to give any interested parties an idea of what's going on.***
Implements:
- A websocket server on the API server that listens to connections on the path `/ws`.
- Code to manage a list of topic subscriptions per connection, which can then receive broadcast messages on those topics.
- Client code for interfacing with the above.
=> Prototype API websocket server for broadcasts

backend/api/src/add-subsidy.ts, backend/api/src/create-comment.ts, backend/api/src/create-market.ts, backend/api/src/place-bet.ts, backend/api/src/update-market.ts, backend/api/src/websockets/helpers.ts, backend/api/src/websockets/server.ts, backend/scripts/websocket-connect.ts, common/src/api/utils.ts, common/src/api/websockets.ts, common/src/envs/dev.ts, common/src/envs/prod.ts, dev.sh, web/hooks/use-api-subscription.ts, web/lib/api/proxy.ts, web/pages/websocket-live.tsx
Now things broadcast to contract-specific topics, broadcasts contain data about the broadcasted item, there are more broadcasts, broadcasts respect contract visibility, and I added a useful test script.
=> More websocket broadcast productionizing, test code

backend/shared/package.json, backend/shared/src/backfill-user-topic-interests.ts, backend/shared/src/calculate-user-topic-interests.ts, backend/shared/src/supabase/reposts.ts, backend/shared/src/supabase/search-contracts.ts, backend/shared/src/topic-interests.ts, backend/supabase/user_topic_interests.sql, common/src/feed.ts, yarn.lock
Followed these instructions: https://www.evanmiller.org/bayesian-average-ratings.html
Could be extended to https://www.evanmiller.org/ranking-items-with-star-ratings.html by using bets as higher 'star' ratings
=> Use bayseian average hit rate for user topic score

backend/functions/src/scheduled/reset-betting-streaks.ts
no longer needs 4gb and runs in 5 seconds
=> Make reset betting streak much faster/lighter

backend/api/package.json, backend/api/src/app.ts, backend/api/src/get-best-comments.ts, backend/api/src/record-comment-view.ts, backend/shared/src/helpers/openai-utils.ts, backend/supabase/user_comment_view_events.sql, common/src/api/schema.ts, common/src/secrets.ts, web/components/feed/good-comment.tsx, web/components/feed/scored-feed-repost-item.tsx, web/hooks/use-api-getter.ts, web/lib/service/analytics.ts, web/pages/comments.tsx
=> Show ~claude's~ GPT4-o's favorite and manifold's favorite comments

.github/workflows/check.yml, .github/workflows/format.yml, .github/workflows/test.yml, backend/api/src/gidx/register.ts
not shown: update vercel settings to only redeploy web and prod when `./web` or `./common` have changed, and only redeploy docs when `./docs` have changed
=> Only trigger relevant Github Workflows

backend/api/src/app.ts, backend/api/src/get-private-messages.ts, backend/supabase/private_user_message_channel_members.sql, backend/supabase/private_user_messages.sql, common/src/api/schema.ts, common/src/supabase/private-messages.ts, common/src/supabase/realtime.ts, web/components/messaging/messages-icon.tsx, web/components/messaging/send-message-button.tsx, web/hooks/use-persistent-supabase-polling.ts, web/hooks/use-private-messages.ts, web/lib/supabase/private-messages.ts, web/pages/messages/[channelId].tsx, web/pages/messages/index.tsx
Loads messages which seems to be broken w/ the supabase client
=> Move private messages to api

web/components/new-contract/cost-section.tsx
This is designed to make it clear to newcomers that cheaper tiers normally exist, just not for the Numeric question type. It can prevent misunderstandings like "wow, I really have to get out my credit card just to create my first question?"
=> Adding explanation for disabled tiers on Numeric questions.

backend/api/src/create-market.ts, backend/api/src/resolve-market.ts, backend/scripts/reimburse-broken-markets.ts
https://www.notion.so/manifoldmarkets/Market-creation-outage-d6c0ed5a001a4057bcb89f82787a5b84
=> Backfill missing liquidity and reimburse resolved markets affect by the bug

backend/api/src/place-bet.ts
instead of one by one. this seems to improve the api's stability.
=> Bulk insert bets

backend/api/src/multi-sell.ts, backend/api/src/place-multi-bet.ts, backend/scripts/compare-bet-endpoints.ts, common/src/api/schema.ts
Working on Ian's test script so that I can effectively change other bet endpoints and validate them. I need to refactor sell shares a lot so that's the priority.
=> Sell shares refactoring prep

backend/api/src/get-positions.ts, common/src/api/schema.ts, docs/docs/api.md
Resolves #2785.
Note: I have not yet been able to test this commit.
=> Add ability to filter positions by answer through the API

common/src/envs/constants.ts, web/components/bet/user-bets-table.tsx, web/pages/checkout.tsx
=> Add sweeps indicator to trades

backend/shared/src/calculate-redeemable-prize-cash.ts, backend/shared/src/resolve-market-helpers.ts, common/src/txn.ts
do you think this approach is good?
=> Record 5k limit on txn

common/src/envs/constants.ts, web/components/bet/bet-panel.tsx, web/components/bet/cashout-limit-warning.tsx, web/styles/globals.css
=> FL NY explainer

common/src/envs/constants.ts, common/src/user.ts, web/components/bet/bet-panel.tsx, web/components/buttons/button.tsx, web/components/contract/contract-overview.tsx, web/components/contract/twomba-contract-page.tsx, web/components/contract/twomba-header-actions.tsx, web/components/portfolio/twomba-portfolio-value-section.tsx, web/components/twomba/toggle-verify-callout.tsx, web/pages/cashout.tsx, web/styles/globals.css
=> add callout for unverified users

web/components/search/contract-filters.tsx, web/components/search/filter-pills.tsx, web/public/custom-components/tiers.tsx
common complaint
Copy of [#2852](https://github.com/manifoldmarkets/manifold/pull/2852) but without as many commits in history
=> Add basic market to filtering tiers

common/src/gidx/gidx.ts
Confirmed to still work fine as tested in dev
=> remove student photo id

backend/scripts/add-mana-stats-full-columns.sql, backend/shared/src/mana-supply.ts, backend/supabase/knowledge.md, backend/supabase/mana_supply_stats.sql, common/src/supabase/schema.ts
=> Include negative user balances in mana supply

native/App.tsx
This fixes the one instance I could repro, waiting to see if it does so with the other. Already pushed an OTA updated
=> Fix fragment parsing

backend/api/src/app.ts, backend/api/src/get-total-redeemable-prize-cash.ts, backend/shared/src/calculate-redeemable-prize-cash.ts, common/src/api/schema.ts, web/pages/stats.tsx
=> Add total redeemable prize stats

web/pages/embed/[username]/[contractSlug].tsx
This reverts commit fb207a934f2ce546a1074796e33b61eef288e447.
=> Revert "hacky fix (#2934)"

backend/api/src/gidx/complete-checkout-session.ts, backend/api/src/gidx/get-checkout-session.ts, backend/api/src/stripe-endpoints.ts, common/src/economy.ts, web/components/add-funds-modal.tsx, web/components/gidx/twomba-funds-selector.tsx, web/hooks/use-prices.ts, web/lib/service/stripe.ts, web/pages/checkout.tsx
=> Enable stripe purchases

backend/api/src/create-answer-cpmm.ts, backend/api/src/place-bet.ts, backend/api/src/redeem-shares.ts, backend/shared/src/helpers/user-contract-metrics.ts, backend/shared/src/supabase/bets.ts, backend/shared/src/supabase/users.ts, backend/shared/src/supabase/utils.ts, common/src/bet.ts, common/src/redeem.ts
Buylkify bet, balance, metric upserts into one batch
=> Bulk insert bets, balance updates, and metric updates

backend/api/src/place-bet.ts
=> Give (mana) unique trader bonus in sweep markets

backend/api/Dockerfile, backend/api/add-backend-service.sh, backend/api/deploy-api.sh, backend/api/ecosystem.config.js, backend/api/src/app.ts, backend/api/src/serve.ts, backend/api/url-map-config.yaml
steps in taken google console:
delete and recreate the load balancer (I think this is unecessary)
create a new backend service and copy all the settings
then run the deploy api script
=> Direct read api's to a seperate instance 

web/components/og/og-market.tsx
This reverts commit 03c837bc0418dc92c71bc066bb67a5b567b665eb.
=> Revert "restyle card (#3087)"

common/src/envs/constants.ts
https://manifold.markets/SiriusBOT?tab=summary thx in advance
=> Adds my bot 

common/src/envs/constants.ts
From Quinn: Added the name for my bot.
=> Added my bot name

package.json, yarn.lock
This reverts commit a382662aca99c052be035901cd6037c5cbe384dc.
=> Revert "deploy bugs (#3433)"

common/src/envs/constants.ts
=> Add @kbot to bot list

backend/api/src/get-site-activity.ts, backend/api/src/get-user-contract-metrics-with-contracts.ts, backend/api/src/search-contracts.ts, backend/shared/src/supabase/contracts.ts, backend/shared/src/supabase/search-contracts.ts, backend/shared/src/utils.ts, backend/shared/src/weekly-markets-emails.ts, common/src/api/market-search-types.ts, common/src/native-message.ts, native/App.tsx, native/android/app/build.gradle, native/app.json, native/ios/Manifold/Info.plist, native/ios/Podfile.lock, native/package.json, native/yarn.lock, web/components/bet/share-bet.tsx, web/components/buttons/referrals-button.tsx, web/components/buttons/user-settings-button.tsx, web/components/contract/contracts-table.tsx, web/components/search.tsx, web/components/search/contract-filters.tsx, web/components/search/filter-pills.tsx
Merge after store accepts builds
=> Make bet sharing work on android

common/src/envs/constants.ts
I am new at this, I hope I did it right.
=> Add "RISKBOT" to bots

web/components/ai-forecast.tsx, web/components/timeline/timeline-card.tsx, web/components/timeline/timeline-item.tsx, web/components/timeline/timeline.tsx
positioning is now more correct but I haven't figured out how to make the lines go behind the text box
=> recalculate timeline positionings

common/src/envs/constants.ts
=> Add 'a bot' bot

docs/docs/api.md
API Docs update to help users understand how to create a POST Bet command
=> Add POST Bet Example Usage

common/src/envs/constants.ts
It's listed at 30k+ profit in its gold league, where second place has \*checks notes\* 268.
=> Add `PugBot` to bots list
