web/lib/firebase/contracts.ts
web/pages/tag/[tag].tsx

The tags page totally broke and was returning 500s. Evidence suggests this is because the `getStaticProps` payload exceeded 5 MB, which is a [server limit imposed by Vercel](https://vercel.com/docs/concepts/limits/overview#serverless-function-payload-size-limit).
I didn't see any reason to try to somehow weasel around the limit when I could just rewrite the tags page to make a normal Firebase query that only gets the tag we're interested in, so that's what I did.
This commit requires an index on `lowercaseTags` and `createdTime`, which I made. The `firestore.indexes` file checked into the repo seems to be in some state disconnected from the actual state of Firestore, so I am ignoring it for now while I fix the problem.

Make tags page filter contracts in Firebase

---

web/components/feed/activity-items.ts
web/components/feed/feed-items.tsx
web/components/outcome-label.tsx
web/pages/[username]/[contractSlug].tsx

If a user has made a recent bet, they'll be prompted to comment on it. Otherwise, they'll be commenting with their position.
Ungrouped bets per user request in discord in the bets tab.
Added a tooltip for free response answer labels when a user comments as they can be unreadable when long.

Show comments position

---

common/charity.ts

They seem to have been HTTP for no particular reason, so now they are HTTPS.

Fix HTTP charity logo links

---

web/lib/api/cors.ts
web/package.json
web/pages/api/v0/market/[id].ts
web/pages/api/v0/markets.ts
web/pages/api/v0/slug/[slug].ts

Right now all API routes just get totally public data and require no authentication, so there's no need to apply any CORS restrictions. We can just let anyone query them from wherever we please.

Apply permissive CORS headers to API

---

common/charity.ts
web/components/charity/charity-card.tsx
web/next.config.js
web/pages/charity/[charitySlug].tsx

Move our charity images froom `<img>` to the Next.js `<Image>` components for better caching, responsiveness on mobile, and lazy loading. No more empty images!
Downsides:
1. replacing an image in a commit will take some time to propagate to clients
2. you have to the image host sites in next.config.js, so it's harder to use images from random websites. This is why I rehosted everything on imgur.
All the images are currently in this album: https://imgur.com/a/WSM6nKC
but it doesn't matter what imgur album we use. We don't need to use imgur either, Next works with everything.

Move all charity images to imgur + Next.js

---

web/components/page.tsx
web/pages/charity/[charitySlug].tsx

Make conversion to $ more clear even when donate box is super wide.
Long term, this should probably be more like the buy market UI instead.

Improve donate box UI in mid-size window

---

web/components/amount-input.tsx

Later we might want a more visible CTA and open a buy panel instead of switching pages, but this gets us 80% of the way there

Ask user to buy more mana when they have insufficient funds

---

functions/src/scripts/denormalize-avatar-urls.ts
functions/src/scripts/denormalize.ts

It seems that this was never actually fixed up for old contracts. Now all contracts have a correct `creatorAvatarUrl`. (It turns out that all comments already did have one -- I was just suspicious.)
I already ran this on dev/prod but I would be interested in anyone taking a glance at it since I have zero experience writing either Typescript or writing code against Firestore.
EDIT: Also answers already had correct avatar URLs.

Add script to denormalize avatars into other docs

---

common/answer.ts
common/comment.ts
common/contract.ts
common/user.ts
web/components/SEO.tsx
web/pages/api/v0/_types.ts

Since #127 null avatar URLs are no longer a thing in production. They are a thing in some super broken contracts on dev that are literally associated with deleted users, but those contracts deserve to be broken anyway, and if you are mad then you should delete them (or poke the database to associate them with real users).

Represent DB avatar URLs as non-null

---

web/components/bets-list.tsx
web/lib/firebase/users.ts

I am skeptical whether it is good to make these warmup requests once. Perhaps it is. But it definitely isn't good to make them dozens of times on page load (e.g. on the portfolio page in the `sellBet` case, or all over the place in the `createUser` case.)

Kill warmup spam

---

web/pages/api/v0/_types.ts
web/pages/api/v0/market/[id].ts
web/pages/api/v0/markets.ts
web/pages/api/v0/slug/[slug].ts
web/tsconfig.json

I got really fed up with the `../../../../../common/foo` business so I fixed it. Now you can import stuff from the root of the repository, e.g. `common/foo` or `web/lib/firebase/bar`.
Fixed up the API endpoint imports as a proof of concept. If you guys like this style maybe we should find/replace it in the rest of the codebase later.

Configure compiler to allow absolute imports from root

---

web/components/answers/answers-panel.tsx
web/components/feed/activity-feed.tsx
web/components/feed/feed-items.tsx

It seemed like all these wrappers and classes served no purpose.
There is one tiny user-visible change, which is that on the home page activity feed, on small screens, there is a little less right-padding on each feed item. I actually think this change is a bug fix; it means that the right and left margins are the same size, and it means that the right UI elements are right-aligned with e.g. the "create market" button at the top. So I am keeping this change.
I tested on all my browsers. I don't have an iPhone to test with. But the existence of the wrappers made no sense to me, so I don't feel it is likely to break anything.

Feed container markup cleanup

---

web/pages/_app.tsx

I noticed that when I do a deploy and I want to test to make sure everything is OK, I sit around looking at the site thinking, are my changes live yet? Now on page load it will print a helpful message in the console making it super clear what is the live code, so I don't have to wonder whether or not I got the new one.

Print out build info in console

---

web/pages/_app.tsx

Our "squash and merge" business makes big long multi-line commit messages the norm, but the first line is a more appropriate summary for this log message, rather than printing the whole thing, newlines and all.

Truncate multi-line commit messages in console build info

---

functions/src/stripe.ts

The other references to "mantic" that I could find look legit, but the
referrer in stripe.ts should probably be updated.

Update mantic.markets -> manifold.markets

---

common/user.ts
firestore.rules
web/lib/firebase/users.ts
web/pages/profile.tsx

_**Don't merge this before deploying the associated Firebase rules to prod or it won't work.**_ (They are already deployed to dev.)
The key doesn't do anything yet. I could hide it from the UI for now, but why bother? Let people think about it.
The key is stored in `/private-users/{uid}/apiKey`.

Allow users to generate an API key in their profile

---

web/package.json
yarn.lock

This is relevant to us because tree shaking was busted in our version of HeadlessUI, and now it's [fixed](https://github.com/tailwindlabs/headlessui/pull/1247), and we use very few HeadlessUI components. So we will save a few tens of kilobytes of bundle size.

Upgrade HeadlessUI to 1.6.1

---

web/components/amount-input.tsx
web/components/bet-panel.tsx

Previously, I felt this code was fishy because all the logic in `SellAmountInput` was responsible for producing the first row of "sale proceeds" UI, which was clearly not conceptually tied to the input component -- it was supposed to be part of the `SellPanel` above it. By moving this logic up, that markup got simpler, and `SellAmountInput` basically turned into nothing.
What do you think?
In the future, I think this could be further improved to throw out more code and unify some of the validation and error-handling logic between buy and sell components (which is subtly different in ways that I think are as likely accidental as intentional.)
There should be no user-visible changes.

Clean up some stuff with SellPanel and AmountInput

---

functions/package.json
functions/src/api.ts
functions/src/create-contract.ts
functions/src/place-bet.ts
web/components/bet-panel.tsx
web/components/bets-list.tsx
web/components/resolution-panel.tsx
web/package.json
web/pages/create.tsx
yarn.lock

_**Function status: these replacement functions are currently deployed on dev for testing, and not yet on production.**_
This enables these functions to serve future public API requests. Future public APIs will be converted in a similar fashion when desired.
The design of this change is to be backwards-compatible with the existing `onCall` machinery, so deploying these new versions of the functions will require no client changes. We will break compatibility to make necessary improvements (e.g. real HTTP status codes) in future steps. The most important thing about the new versions is that they now accept API keys (see #182) as an alternative authentication mechanism to the Firebase JWTs. No intentional changes were made to the function behavior except related to authentication.

Implement `onRequest` versions of `createContract`, `placeBet` functions

---

web/components/contract/contracts-list.tsx
web/components/nav/nav-bar.tsx
web/components/nav/sidebar.tsx
web/components/user-page.tsx
web/hooks/use-sort-and-query-params.tsx
web/lib/firebase/bets.ts
web/pages/[username]/bets.tsx
web/pages/[username]/comments.tsx
web/pages/[username]/index.tsx

Somewhat controversial to make all these bets public, but I think this is actually correct, in the context of radical transparency, and pragmatically all this data was available anyways. Hopefully encourages people to bet more, too -- more betting is one thing we're kind of constrained on atm.
Some proposals/ways to move forward:
P1: Ship this as-is -- it's not revealing anything that wasn't already query-able via Firebase command before
P1.5: Because this is making public things that weren't previously public, give everyone a chance to delete their account or any specific bets they didn't want to expose to the world
P2: Only you get to see this on your portfolio
P2.1: You can opt in to showing this to the world
P2.5: Show total bet count and total profit/loss for everybody else
P3: Get …

Show every user's bets on their profile

---

common/envs/constants.ts
functions/src/api.ts

This needs to be working and also the client API is about to have to generate real CORS headers for `placeBet` and `createContract` APIs, so get it into `common` instead of the `functions` package.

Fix up API CORS header processing

---

web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx

Honestly, this code related to comment and answer highlights doesn't seem to me to be working correctly? For example, if I go [here](https://manifold.markets/agrippa/who-will-visit-me-in-june), click the permalink for the first answer comment, and paste that into the URL bar, the highlight doesn't activate, presumably because no re-render was triggered. It only works if you link to that permalink from outside the SPA.
However, fixing these dependencies up doesn't work any less good than the status quo.

Add some useEffect dependencies

---

web/.husky/pre-commit
web/package.json
yarn.lock

Now that we have visual feedback on GitHub whenever something we commit is busted, we don't need to enforce this in local development anymore.
(Of course, you will still save your time and energy if you run `prettier` and `eslint` in your editor. I think we all do anyway?)

Kill Husky, lint-staged, and pretty-quick

---

.github/workflows/check.yml
common/.eslintrc.js
functions/.eslintrc.js
functions/package.json
package.json
web/package.json
yarn.lock

Now that we have this, we can do the business we discussed in #233 and enforce the import style across our code with eslint.
Note that there are a ton of recommended Typescript linting rules I haven't turned on because our codebase completely fails them all and it would be overwhelming. I will probably address them slowly over time and start turning them on at my discretion if they seem useful.

Set up `eslint` for `common`, `functions` packages

---

web/next.config.js

This doesn't save that much total bundle size (by excluding unused icons), but it also lets all the icons we do use go into their individual page chunks instead of a big cross-page chunk that everything depends upon, so it's worth writing a couple lines of configuration for.

Modularize imports of hero icons in compiler

---

functions/src/place-bet.ts

This is a hacky patch for a problem that runs more deeply: the use of
floating-point for Mana calculations, along with the associated rounding
errors.
Consider the following example:
```typescript
const balance = 1000
const bet = 5.6e-14
const newBalance = balance - bet
if (newBalance == balance) {
alert(`I placed a bet of ${bet} without changing my balance.`)
}
```
This will actually print a message, because floating-point numbers can
only represent so many digits, and thus we get 1000.0 rather than
999.99999999999994.
This is a purely theoretical attack at this point; nobody could create
enough pico-bets to actually affect their balance using this technique.
However, I believe is worth ensuring a minimum bet amount, and might
prevent other problems such as the UI showing messages like …

Require a minimum amount of 1 Mana per bet.

---

common/envs/dev.ts
common/envs/prod.ts
common/envs/theoremone.ts
web/lib/api/cors.ts
web/lib/api/proxy.ts
web/lib/firebase/api-call.ts
web/package.json
web/pages/api/v0/bets/index.ts
web/pages/api/v0/market/index.ts
yarn.lock

Now you can `POST /api/v0/markets` to create a market and `POST /api/v0/bets` to make a bet. These routes will just forward your request to the relevant cloud function and do zero intelligent work on their own.

Add Vercel routes for public write API

---

web/pages/api/v0/_types.ts

This was requested in Discord and is obviously necessary.

Add outcome type to API market descriptors

---

functions/src/emails.ts
web/components/feed/copy-link-date-time.tsx
web/components/feed/feed-comments.tsx

I added the comment id to the market url in the comment email. The variable isn't appropriately named now though, but I'm not sure how to mess with the email template and I'm assuming it's looking for the key: 'marketurl'.
I also just defaulted to always adding the manifold.markets url to the comment link as who knows what page people will be linking from: /home, /activity, etc. On local dev you'll have to replace https://manifold.markets with localhost:3000.

Fix comment links from /activity & add to emails

---

web/components/contract/quick-bet.tsx
web/components/use-save-shares.ts

Now with free response contracts the quick bet view will show a highlighted up arrow if the user has shares in the top answer. If they don't own shares in the top answer but do in other answers, it'll show the down arrow. For numeric markets it will just show the up arrow if they've bet on the market anywhere. This should probably be whether their bets are majority above or below the displayed value?

Handle free response outcomes for yes/no shares

---

common/contract.ts
common/payouts-dpm.ts
common/payouts.ts
functions/src/sell-bet.ts
functions/src/sell-shares.ts
web/components/contract/contract-info-dialog.tsx

Now that `contract.collectedFees` is [no longer secretly nullable](https://github.com/manifoldmarkets/manifold/commit/e5ce17c2ade2a1b36d69a7b049a8a249b5b09c81), we don't have to worry about it.

Clean up some mess related to nullable `collectedFees`

---

web/components/bets-list.tsx

For CPMM, it doesn't really make sense to but a sell button on every individual buy bet, so instead I put it in next to the profit.
Individual market:
Your bets in profile:
Upon clicking, it opens a modal

Allow selling CPMM binary position from bet table

---

common/contract.ts
functions/src/emails.ts
web/components/outcome-label.tsx

So, I don't actually understand the history here. All I see is that in #47, we added some code suggesting that there could be contracts with the `MULTI` outcome type, distinct from the `FREE_RESPONSE` outcome type, which would have an array of strings that were like outcomes, but weren't free response answers. Maybe they were gonna be like free response markets with a fixed list of answers set by the creator? However, we never implemented any actual code for creating these or using them, and they never came to exist. So in that case let's clean up the last tiny bit of stuff that thinks they exist.

`MULTI` contracts are not a thing

---

web/pages/embed/[username]/[contractSlug].tsx

This was not a comment, it shows up on embedded markets.
Screenshots:

Commented out code which was meant to be a comment

---

web/lib/firebase/api-call.ts

There's no reason not to do this and we are worried about performance so let's do it.

Call cloud functions directly from web client instead of proxy

---

functions/src/api.ts
functions/src/health.ts
functions/src/index.ts

Usefully for our current purposes, it can be used to either hit the database (if you are authenticated it looks up your user) or not hit the database (if you have no `Authorization` header it will reject you outright.)

Add a /health function for ease of benchmarking

---

web/pages/api/v0/_types.ts

We already had `volume7Days` and `volume24Hours`, but adding total volume lets us do e.g. external leaderboards.

Add total market volume to API response

---

web/lib/api/proxy.ts
web/lib/firebase/api-call.ts

Oops, I just didn't realize this was broken recently by my API work where I changed these to be `onRequest` instead of `onCall` functions. Now it's fixed up.

Fix API calls to hit emulated Firebase

---

web/components/feed/activity-items.ts

Before this PR, free response answers and their associated comments disappeared when all shares in the answer were sold. If it's just an answer, this is a surprising UX but not that bad. But this can also disappear an entire comment thread with great discussion, as I noticed on one of my markets recently.
I suppose the downside is that these answers take up space and are more likely to be undesired - but I think answers with M$1 of bets are much more common anyway.

Fix free response answers with 0 bets disappearing

---

functions/src/api.ts
functions/src/create-contract.ts
functions/src/index.ts
functions/src/place-bet.ts

***Deploy status: See below.***
This should dramatically improve our cold start -- and warm -- performance issues with these two functions, and if everything is working good, we can migrate other functions to work this way.
Some differences between the old and new:
- Annoyingly, v2 Cloud Functions don't allow capital letters in names. They allow hyphens, but the Javascript + Firebase CLI toolchain makes it impossible to get hyphens in there. Whatever.
- The v2 Cloud Functions have beefier CPUs, so the idle 1 minimum instance costs more money, but we don't care.
- I'm renaming `createContract` to `createmarket` while I'm at it.
Here's how this is gonna go down:
1. I merge this.
2. I `firebase deploy --only functions` on prod, without deleting old functions, creating new `placebet` and …

Migrate placeBet and createContract to v2 functions

---

docs/docs/api.md

Just wrapping this up so we can publicize these if we wish.
The whole API documentation is pretty sloppy but that's probably fine for now.

Add documentation for new API endpoints

---

web/components/feed/feed-answer-comment-group.tsx

Updates fr answers in the comments section in realtime after a bet is placed. Also only scrolls user to an input field for their bet if they made a bet while on the page, (not for previous commentable bets).

Update FR comment prob and input after bet

---

docs/docs/api.md
web/lib/firebase/contracts.ts
web/pages/api/v0/markets.ts

This is ugly, but the status quo is that this endpoint is totally broken so I am doing the simplest thing that seems sane.

Add paging to `/markets` API endpoint

---

functions/src/get-feed-data.ts
functions/src/update-feed.ts

I noticed that feed updating is frequently outright failing because it takes so long it exceeds the Cloud Function runtime limit, and it looked like it was easy to make it much more efficient, so I did that.
Previously, to update each category feed, it was loading all bets and comment data for every contract (likely 75) in the feed of every user in every batch of users (30). But even though the feeds were probably very similar -- they use lots of user-agnostic ranking data -- each user would independently query all the bet and comment data for all their contracts. Now, the batch queries bet and comment data once for the union of the contracts of all the user feeds in the batch, so that might be something not far off from a factor of 30 less queries.
I didn't measure it, but this is by far …

Make feed updating do much less work

---

web/components/feed/copy-link-date-time.tsx

This generated broken links, so it wasn't working.

Fix busted comment permalink copying code

---

web/components/feed/contract-activity.tsx

It looks like listening to contract updates via `useContractWithPreload` is essential to getting the FR comments section answer probs and the top answer probs to be in sync. This makes sense to me, is there anything I'm missing?

Must listen to contract updates for probs to update

---

functions/src/api.ts
functions/src/create-contract.ts
functions/src/health.ts
functions/src/place-bet.ts
functions/src/sell-bet.ts
functions/src/sell-shares.ts

Just picking the lowest possible hanging fruit here. After this `placebet` (e.g.) will basically be doing what looks like a conceptually reasonable thing from a performance standpoint, so then we can take a look at the graphs, see where we stand, and judge whether we want to spend more effort.
- It turns out that most API endpoints that want user info are gonna want it in a transaction anyway, so looking it up in the auth flow is not a good idea because it's wasted work.
- There was no reason for `redeemShares` to be happening in a separate transaction and re-looking-up stuff that was already looked up.

Implement really obvious optimizations on `placebet`, `sellbet`, `sellshares`

---

functions/src/update-contract-metrics.ts

I don't know if this is moving the needle on cost, but it's easier to just fix stuff to be better and look at what happens rather than try to discern it by thinking.
I guess this does half as many database queries as the previous version and reads way less data, so that should be good.

Optimize `updateContractMetrics`

---

functions/src/scripts/update-metrics.ts
functions/src/update-contract-metrics.ts
functions/src/update-user-metrics.ts
functions/src/utils.ts

Basically I wanted to add a bunch of logging so that I can see what's going on in these functions, and add a script to test it.
Based on looking at graphs so far, I think these will be our new cost culprits after `updateFeed`, and we can easily continue to make them more efficient with minimal effort. For example, if we put these two functions together it's basically going to do all the work in the same amount of time, and we aren't taking advantage of Firebase's batched update functionality either. Probably I am going to do this if it saves e.g. twenty bucks per day. (These guys basically scale linearly with the number of things in the DB, so they are only going to get more expensive.)
But I'm getting tired of feeling like I am in the dark while I am changing stuff so I am gonna start …

Improve visibility of `updateFooMetrics` functions behavior

---

docs/docs/api.md
web/lib/firebase/contracts.ts
web/pages/api/v0/_types.ts

@wasabipesto noticed inconsistencies in the market data the api returns.
I've taken a look at LiteMarket, my suggestions are in this PR.
There is more data for non-binary markets now and hopefully it's clearer what the values mean.
The total number of shares in the liquidity pool which was written to "pool" before seems to have been a relic from dpm binary markets and is not in the API anymore.
* pool: set in the same way as in the "Market Overview" from contract-info-dialog.tsx now
* removal of totalLiquidity: was only set for binary markets and its value was identical to the new totalShares in that case
This does not need to be merged right away but can serve as basis for discussion.

Refinement of LiteMarket

---

web/components/contract/contract-details.tsx
web/components/feed/feed-items.tsx

I noticed that resolved markets which haven't been traded on still show the "New" chip. This PR removes the "New" chip for resolved markets
Old:
New:

Don't show the 'New' chip on resolved markets

---

web/pages/api/v0/market/[id].ts
web/pages/api/v0/slug/[slug].ts

Self-explanatory. I don't see any virtue to this cache and it makes it totally impossible to make anything resembling a trading bot.

Remove surprising 2 minute edge caching for API market data

---

web/lib/api/proxy.ts

This fixes an issue noted [here](https://github.com/manifoldmarkets/manifold/pull/518#discussion_r899643978) because node-fetch throws an error on the client if you try to ever `fetch` using `GET` or `HEAD` with a non-null `body`, so it was never making it to Firebase.
Now trying to call the write APIs with invalid methods produces a correct 405 via Firebase.

Correctly proxy GET and HEAD requests instead of dying

---

web/components/nav/sidebar.tsx

There's currently no user-discoverable link to https://manifold.markets/stats (previously https://manifold.markets/analytics).

Add Statistics link to sidebar

---

common/contract.ts
docs/docs/api.md
web/pages/api/v0/_types.ts

Currently, binary markets have their resolution set to YES, NO, or MKT. If they resolve to MKT, there is no way to know via the API what value they resolved to (Issue #524).
This PR exposes `resolutionProbability` to the API via LiteMarket. This is a key step in being able to calculate payouts for markets.

Add resolutionProbability to LiteMarket

---

web/components/contract-search.tsx
web/components/contract/contract-card.tsx
web/components/contract/contract-details.tsx
web/components/contract/contracts-list.tsx
web/pages/contract-search-firestore.tsx

Shows "resolve time" in the market card when the "resolve time" sort option is selected.
---
Before:
After:

Show resolution time in market cards when appropriate

---

common/envs/dev.ts
common/envs/prod.ts
common/envs/theoremone.ts
web/lib/api/proxy.ts
web/lib/firebase/api-call.ts

It seems clear how these work now, so let's clean this up so that we don't have to keep adding individual v2 cloud functions here when we create them in the future.
(The `uc` region stands for `us-central1`. The ID as far as I can tell is some meaningless hash.)

Clean up definition of v2 cloud function URLs

---

web/components/contract-search.tsx
web/hooks/use-sort-and-query-params.tsx
web/pages/home.tsx

The status quo ante: When you load the homepage it does at least three (probably more in some cases) search queries to Algolia before you even touch the UI, each pulling JSON results with thousands of contracts over the wire, and maybe rendering janky search results that disappear afterward.
Two fixes to try to stem the bleeding:
1. Don't treat `undefined` lists of `followedCategories` and `follows` different than empty lists. Previously, it would do a new search every time these came in, even if it was going to be the same search. Now it will only do a new search if you actually have follows or if you filtered the categories. That still kind of sucks but at least we are fixing it for many users.
2. Don't wait a long time to load the saved search sort from local storage. Previously, we …

Ameliorate homepage search spam

---

firebase.json

I don't know of any particular reason why this is important, but keeping these on such an old version of Node is really spooky in terms of "the documentation and local development environment matching production", so let's get it as up to date as possible.
These can be redeployed in place. I currently have dev `placebet` running Node 16 as a test. When I deploy the rest I'll be keeping an eye on the dashboard to see if any errors crop up.
By the way, Vercel is on Node 14. I'll probably bump it to 16 too so that everything makes more sense.

Bump Cloud Functions Node version from 12 -> 16

---

functions/src/api.ts

The Firebase CLI has a secret feature. The feature is that it [ignores](https://github.com/firebase/firebase-tools/blob/466bdaa86de353eb090dc40006d5a1a9414de9da/src/deploy/functions/release/fabricator.ts#L340) your `concurrency` setting on functions if they have less than [2GB](https://github.com/firebase/firebase-tools/blob/466bdaa86de353eb090dc40006d5a1a9414de9da/src/deploy/functions/backend.ts#L189) of memory. So I hypothesize that upping the memory might make v2 functions scale the way I expect them to.
(I thought they already had 1 vCPU by default according to the docs, but the CLI complained that you can't have 2GB of memory without 1 vCPU...so maybe I am also upgrading the CPU?)

Bump memory on all v2 functions to 2GB

---

firestore.rules
web/components/portfolio/portfolio-value-graph.tsx
web/components/portfolio/portfolio-value-section.tsx
web/components/user-page.tsx
web/lib/firebase/users.ts
web/lib/util/time.ts
web/pages/leaderboards.tsx

Adds the portfolio graph to the portfolio page. 
[Here's a video of how it looks](
https://user-images.githubusercontent.com/6242616/174615819-af072c60-4fad-4e4b-94d5-5c34e5c5e1a0.mp4
)
Notes:
-We'll need to update the firestore security rules in production 
- I'm starting it off with the period toggle not showing, defaulting to 'allTime'. Once data gets cached we can turn it on.

[PortfolioGraph] Shows a graph of the portfolio value over time

---

web/pages/leaderboards.tsx

We've been caching values for over a day now, so we can enable the Top Bettors daily leaderboard.

[Leaderboard] Show daily 'topBettor' leaderboard

---

.github/workflows/check.yml
common/.gitignore
common/tsconfig.json
firebase.json
functions/.gitignore
functions/package.json
functions/tsconfig.json
web/next.config.js
web/tsconfig.json

This is under the "make our deployment not suck" project heading.
1. Using this [project reference](https://www.typescriptlang.org/docs/handbook/project-references.html) Typescript technology lets us do real incremental builds, so we don't have to wait ten or twenty seconds or whatever to compile the Typescript when we deploy the functions.
2. By using a separate `dist` directory to store the deployable function code, we avoid packaging random nonsense that was in the main directory, inflating the container image and wasting time. (Most egregiously, if you had a database export in the main directory.)
3. By putting the `yarn.lock` into that directory, the builder machine can more efficiently fetch dependencies.
This more or less cuts the deployment time for a function in half so far.
The …

Use Typescript project references, improve functions build/deploy

---

web/components/answers/create-answer-panel.tsx
web/package.json
yarn.lock

Addresses #533
This PR prevents duplicate Free Response answers, and also adds a warning when creating an answer that is similar to an existing one. I'm not sure of Manifold's philosophy on adding dependencies, so please lmk if the added dependency on `string-similarity` is a dealbreaker
---
Example duplicate prevention:
Example similar answer warning:

Prevent duplicate Free Response answers

---

docs/docs/api.md
web/pages/api/v0/_types.ts
web/pages/api/v0/users.ts

This is a first swing at adding a `users` endpoint to the API. It's read-only, exposing basic account info and cached values.
Basic uses at this stage include:
- Getting current balance for intelligent betting via API
- Getting total market volume for leaderboard placement
- Getting username and avatar for rendering bets
Future plans may include:
- Exposing extended data in FullUser, akin to FullMarket
- `Markets[]`, a list of all markets a user has created
- `Comments[]`, a list of all comments a user has made
- `Bets[]`, a list of all bets a user has made
- List of followers and followed accounts
- Amount received via tips
- Groups(?)
I would love feedback on styling, layout, etc. We may want to move some of this out of `_types` if we plan on adding much more. We may also want …

Add Users API endpoint

---

web/components/contract/contract-tabs.tsx
web/components/feed/activity-items.ts
web/components/feed/contract-activity.tsx
web/components/feed/feed-items.tsx
web/components/feed/feed-liquidity.tsx
web/pages/[username]/[contractSlug].tsx

Example:
Unfortunately, this only currently works when someone _adds_ liquidity to a market. The liquidity doc has it's "amount" zeroed out upon liquidity withdrawal, so liquidity withdrawals are not shown (the "add" event just disappears)

Add market liquidity addition events to bets feed

---

web/pages/link/[slug].tsx

Nitpick of the Manalink claim page title

Add "M$" to title of Manalink claim page

---

functions/src/place-bet.ts
functions/src/sell-bet.ts
functions/src/sell-shares.ts

I just didn't know about this when I last touched this code, but now I do. My guess is we can expect this to be slightly quicker than parallel `Promise.all` requests mostly because it's going to be as slow as the latency of the one network request it does, rather than as slow as the max latency of any of the network requests it does.
Kind of weird that the client side Firebase SDK straight up doesn't expose this, but that's Firebase life for you.

Use `getAll` Firestore technology to improve some code

---

web/components/portfolio/portfolio-value-graph.tsx
web/components/portfolio/portfolio-value-section.tsx
web/components/user-page.tsx
web/pages/leaderboards.tsx

Toggles on:
- All portfolio graph views except for the monthly one.
- The weekly leaderboard for "Top bettors".
Something to note, that I'm not sure if it's clear to you guys @jahooma: The portfolio graph will be public, i.e every user will be able to see any other user's portfolio over time. If that's *not* the intended functionality, please request a review and I'll hide it for all profiles except the one who's currently signed in.

Toggle weekly leaderboard and daily/weekly/alltime portfolio graph

---

functions/package.json
yarn.lock

[This is the runtime library](https://github.com/GoogleCloudPlatform/functions-framework-nodejs) that actually runs our functions and listens for requests. For some bizarre reason, if you don't include it in your dependencies, Google will download it for you in the build anyway. However, that's slower than having it in the dependencies, and it's also weird, because obviously we want to control what version it is, have it share dependencies with other stuff like every other Javascript library, etc. So let's not do that anymore.
We will also probably use it explicitly later for local development purposes.

Add `functions-framework` as explicit dependency

---

functions/src/redeem-shares.ts

Oops, I messed this up in #614 by removing where it was doing this early return. Unfortunately this means there are some weird bets for zero shares now in our DB that do nothing. I don't think that should cause any concrete problems, though.

Don't accidentally make meaningless zero bets

---

web/components/contract/contract-info-dialog.tsx
web/components/copy-contract-button.tsx
web/pages/create.tsx

Asked for by Atlas. But nice to have in general, I think!
Clicking takes you to an example like `/create?q=log%20safsdf%20duplicate%201&closeTime=1657339140000&description=What%27s%20up%20doc%3F&outcomeType=PSEUDO_NUMERIC&min=1&max=100000&isLogScale=true&initValue=10`, where the URL params are filled out:

Duplicate a question from '...' screen

---

functions/src/claim-manalink.ts
functions/src/index.ts
web/lib/firebase/api-call.ts
web/lib/firebase/fn-call.ts
web/pages/link/[slug].tsx

Straightforward, should be no visible changes.
(Background: I want to migrate our remaining v1 onCall functions to v2 because there is no reason not to and because it will be easier to then do further general backend changes, like deploying them in a single express app and making hot reloading of server code work.)

 Migrate claimManalink function to v2

---

functions/src/stripe.ts
web/lib/firebase/api-call.ts
web/lib/service/stripe.ts

Straightforward, but we will have to go into the Stripe dashboard and change the webhook URL after deploying this, so I'm marking it as a draft until I have access to do that.
(Background: I want to migrate our remaining v1 onCall functions to v2 because there is no reason not to and because it will be easier to then do further general backend changes, like deploying them in a single express app and making hot reloading of server code work.)

Migrate stripeWebhook and createCheckoutSession to v2

---

web/lib/firebase/users.ts

`setCachedReferralInfoForUser` uses the dayjs UTC extension, but doesn't initialize it, so this was broken unless some other stuff on the page happened to initialize the UTC extension first. Not sure exactly what cases this entails -- at least it happened to me when I tried to claim a manalink.

Make referral stuff not busted

---

functions/src/add-liquidity.ts

I don't understand a reason why this is useful. Since adding liquidity doesn't add or change any bets, it can't possibly make you eligible to redeem any new bets with outstanding shares. (As opposed to withdrawing liquidity.)
@mantikoros anything I'm missing?
The diff on this looks funny because of the reindentation but the only thing that changed is I took out the redemption step at the end.

Don't run share redemption after adding liquidity

---

web/hooks/use-user.ts
web/pages/link/[slug].tsx

As long as we never have a user with the id of "_" this should be fine 😬 
I can't think of a better way to fix this because of react's hook rules prevent us from simply returning early if the input is undefined

fix: let useUserById accept undefined userId

---

web/components/manalinks/create-links-button.tsx

- changing expire time to dropdown instead of calendar selection
- adding 'M$' in front of amount

minor tweaks of manalink form

---

web/components/groups/group-selector.tsx

This makes React mad because the rendering of the `ComboBox` component is setting state upstream in the `GroupSelector` component.
I don't see any reason to do it... why would it matter what the filter is when the box is closed and the filtered groups aren't showing? I can't observe any difference in behavior.

Don't `setQuery` on group selector component during initial render

---

web/hooks/use-sort-and-query-params.tsx

I'm not saying this is all completely working now, but:
- It doesn't spam warnings in the console from the fact that we are passing the whole router object into `router.push` and then trying to call URL formatting methods on it. I am slightly amazed it even worked at all -- nothing in the [documentation](https://nextjs.org/docs/api-reference/next/router#routerpush) suggests that using it like this is reasonable.
- It doesn't create a zillion history frames for each letter you type (these history frames didn't even "work", in that if you navigate back it wouldn't present the correct query.) This was really bad!

Fix some broken stuff on the homepage contract search routing

---

web/pages/_document.tsx

There's some kind of issue where the Google Fonts request for our custom fonts is not getting processed in some cases. It seems like our stuff here is rather sloppy:
- There's no reason to preconnect to the thing we are connecting to immediately afterward.
- The preconnect had no `crossOrigin` attribute, so it probably wasn't working.
- `true` is [not a valid option](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) for `crossOrigin`. We meant to write `anonymous`.
- The actual stylesheet connection had no `crossOrigin` attribute either, which is kind of weird.
So I'm just fixing it up to look right and then I will continue debugging from there if it's still broken.

Clean up font loading and see if it fixes our problem

---

web/next.config.js

This will probably fix our weird font loading problem, which I haven't exactly pinned down what the deal with is yet. See for reference:
- https://nextjs.org/docs/basic-features/font-optimization
- https://github.com/vercel/next.js/blob/canary/packages/next/pages/_document.tsx

Turn off Next.js font inlining

---

web/package.json
yarn.lock

See https://nextjs.org/blog/next-12-2.
I'm interested in doing this upgrade because future Vercel server auth stuff may find the new middleware functionality extremely useful. It's also good to get closer to being able to upgrade to React 18.
The only issue I notice is a spurious warning when running the dev server -- see https://github.com/vercel/next.js/issues/38284. Unfortunately we should probably just put up with it until 12.2.1 is released with the fix. It doesn't seem to indicate any problem except being annoying.

Update Next.js 12.1.2 -> 12.2.0

---

web/hooks/use-users.ts
web/lib/firebase/users.ts

low priority.
This makes it faster when multiple components on a page call `useUsers` - but that's not super relevant yet.
I just did this to see if it would magically fix an unrelated bug (it didn't).

migrate useUsers hook to react-query

---

web/components/auth-context.tsx
web/components/bets-list.tsx
web/components/feed/feed-items.tsx
web/hooks/use-algo-feed.ts
web/hooks/use-seen-contracts.ts
web/hooks/use-user.ts
web/lib/firebase/tracking.ts
web/lib/firebase/users.ts
web/pages/_app.tsx

See here for an [intro to React contexts](https://reactjs.org/docs/context.html).
The main motivation for this: In our previous version, every time a component called `useUser` (which called `listenForLogin`), it would call `onIdTokenChanged` with a new event handler. That meant that when the ID token did in fact change (e.g. on initial render if you are logged in, or on refresh, or on login/logout), there would be a bunch of identical event handlers running -- it wouldn't be strange for there to be 10 or 20, since we have many components on a page that may call `useUser`.
This was pretty weird and counterintuitive, and besides being tricky to think about and obviously inefficient, it caused us to for example write a strange workaround so that we could create exactly one new user in the …

Make a React context to be the source of truth for authenticated user

---

web/components/auth-context.tsx
web/components/create-question-button.tsx
web/components/nav/sidebar.tsx
web/lib/firebase/users.ts
web/pages/index.tsx

That means that if we create server-side redirects, they will trigger the redirects if appropriate (i.e. redirecting from `/` to `/home` if logging in, redirecting from random logged-in-users-only pages to `/` if logging out.) So now we can set up server side redirects when desired and not worry about also doing it on the client side in the React components anymore.

Make main login/logout buttons reload server side props

---

functions/src/scripts/backfill-comment-ids.ts

In February we updated comments to have their ID in the document and to have the creator's user ID in the comment as part of #44, but many old comments were never fixed, so they still were missing IDs, producing a variety of creative bugs.

Write script to fix old comments without IDs and user IDs

---

web/components/layout/tabs.tsx
web/components/user-page.tsx
web/pages/[username]/index.tsx

Previously, our tabs component that we used everywhere had only one mode, which would be normally called "uncontrolled" -- it kept its active index in local React state. This caused at least two problems:
- In some circumstances, a parent component might like to choose which tab is selected in some arbitrary way. But this becomes impossible to do in any principled way. This really bit me when I was making the manalinks page and I wanted to switch tabs to show the manalink you just created. (That particular case got redesigned, but obviously this is a very normal sounding desire.)
- In some circumstances, we are OK with having internal React-managed active tab state, but we want to represent it differently. For example, on the user page, we represent the active tab in the URL query string. …

Make tabs components better

---

web/pages/notifications.tsx

Not important, I just think it's easier to understand upstream that it's async when you're looking at a type signature if it returns a promise instead of returning void.

Make `setNotificationsAsSeen` return a promise

---

web/components/bets-list.tsx

This changes the bets list to not render all the individual bet details until you expand a contract. That means that there isn't an animation anymore, but the old animation was so fast that it looked worse anyway, in my opinion.
Anyway, the old way of rendering everything was taking 100-300ms on my laptop, so this is obviously the correct tradeoff direction.

Clean up rendering of user bets list

---

docs/docs/api.md
functions/src/sell-shares.ts
web/components/bet-panel.tsx
web/pages/api/v0/market/[id]/sell.ts

This is partly for the Twitch bot, partly because it's a natural API to have, and partly so that our bet panel selling works reliably* to sell exactly 100% of your shares when desired.
*Well, I'm not really convinced the server code is correct with all magnitudes of shares, but it works better than if we didn't do this.

Implement "sell all shares" functionality in `sellshares` and expose API

---

functions/src/scripts/backfill-group-ids.ts

There are missing group IDs on numerous groups in the dev database. Not sure how they got there, but now they will be fixed.
It doesn't seem like the problem exists on prod.

Backfill missing group IDs

---

docs/docs/api.md
functions/src/sell-shares.ts

This is particularly useful in the case of bots, where users may already know how they have bet, regardless of whether the bot knows, and want a very succinct command to sell all their shares.

Allow unspecfied outcome as input to `sellshares`

---

docs/docs/api.md
functions/src/get-current-user.ts
functions/src/index.ts
functions/src/serve.ts
web/lib/firebase/api.ts
web/pages/api/v0/me.ts

Use case: an app that acts on behalf of a user may want to check certain values about the current user such as their id and balance.
Note: I didn't test this because I can't run the gcloud CLI on this computer

Add endpoint for reading currently authenticated user

---

functions/src/resolve-market.ts

This is very convenient for admins since the backend has access to stuff like the Mailgun key, so it's easier to call this API than to run resolution code locally.

Allow admins to resolve any market

---

common/util/parse.ts
functions/src/create-notification.ts
functions/src/on-create-comment-on-contract.ts
functions/src/on-create-contract.ts
functions/src/on-create-group.ts
functions/src/on-follow-user.ts

commit order is a bit fucked, but this is meant to be after https://github.com/manifoldmarkets/manifold/pull/670 and #681  get merged

Notify mentioned users on market publish

---

.github/workflows/format.yml

James wants this and I guess everyone else is OK with it.
One funny thing I noticed is that I guess there's no GH workflow for running prettier on anything except on stuff other than the web client right now? I had the idea I was running it everywhere. Later I will probably turn it on for the other packages.

Add workflow to automate prettier running on main

---

functions/src/api.ts
functions/src/get-custom-token.ts
functions/src/index.ts
functions/src/serve.ts
web/components/auth-context.tsx
web/lib/firebase/auth.ts
web/lib/firebase/server-auth.ts
web/pages/notifications.tsx

In this PR, which is a successor to #593:
- We add a cloud function that accepts an ID token JWT (the one hour expiry one) and returns a custom token JWT (a different, special one hour expiry one. See [here](https://firebase.google.com/docs/auth/admin/create-custom-tokens) for some documentation.)
- The entry point to server auth functionality, `authenticateOnServer` (previously `getServerAuthenticatedUid`), will now, if you don't have a valid custom token cookie, go get a custom token and store it in a cookie, by calling this cloud function with your ID token.
- Then, it will use that custom token to sign into the client-side Firebase SDK, which is the point of all the custom token stuff.
- So now you can go nuts writing `getServerSideProps` functions that run any of our Firebase code, …

Vercel auth phase 2

---

common/comment.ts
functions/src/create-notification.ts
functions/src/emails.ts
functions/src/on-create-comment-on-contract.ts
web/components/comments-list.tsx
web/components/contract/contract-leaderboard.tsx
web/components/editor.tsx
web/components/editor/mention.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/components/groups/group-chat.tsx
web/lib/firebase/comments.ts
web/pages/[username]/[contractSlug].tsx

Continuation of #703
Issue1: on android chrome, deleting an at mention creates spooky behavior (text being duplicated, keyboard dissappearing)
- discovered by Matt P
- caused by [bug in android chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=612446). See also https://github.com/ProseMirror/prosemirror/issues/565, https://github.com/ueberdosis/tiptap/issues/677
- I fixed text duplicate issues - now delete behaves as it should. However, the keyboard still disappears on Android
- tested on Gboard and Swiftkey

Rich text in comments, fixed

---

web/components/contract/contract-description.tsx
web/components/contract/contract-details.tsx
web/components/editor/utils.ts

Before, when you append to description by editing it (including edit question or close time) it would replace an image if the image is the last node in the description. This is because `focus('end')` focuses the image itself. The fix: use [createParagraphNear()](https://tiptap.dev/api/commands/create-paragraph-near)

Make added text go after image instead of replacing it

---

web/components/auth-context.tsx
web/pages/_app.tsx

This establishes a special magic prop, `user`, which if it's present in the page props (e.g. because we wrote a `getServerSideProps` that returns it), will be the initial value in the page `AuthContext`. This will save a re-render on the client when we load the user later from either local storage and/or from the actual Firebase SDK (assuming those things don't disagree with the version that came down from the server.) It will also kind of make the server side rendering more "useful" because it will actually be able to render using the authed user.

Pass page props user to auth provider if present

---

web/hooks/use-bets.ts

This was basically causing an infinite database-spam-and-render loop on the contract page (the only place where we use the filter option is the `ContractActivity` component on that page) because the filter option was an object literal defined in the parent component. So it would call this, this would run and set the bets, it would re-render, creating a new options object, so this would run and set the bets again, and so on.

Fix broken `useBets` filter implementation

---

web/components/contract-search.tsx
web/components/contract/contracts-grid.tsx
web/components/user-page.tsx
web/pages/[username]/[contractSlug].tsx
web/pages/group/[...slugs]/index.tsx
web/pages/home.tsx
web/pages/markets.tsx
web/pages/tag/[tag].tsx

Besides avoiding re-rendering performance hits, one reason this will be nice is that SSR will now render a correct logged-in sidebar on this page and a correct customized contract search header, eliminating any loading jank. Since the homepage is what people are going to be landing on the most, it's nice to make it load as cleanly as possible.

Make homepage load user via SSR, pass it to contract stuff

---

functions/src/scripts/set-avatar-cache-headers.ts
web/lib/firebase/storage.ts

We forgot to add cache headers to any uploaded avatars, presumably because we also didn't used to give them a unique filename. But now we do, so we can cache them.

Add cache headers to avatars

---

web/components/layout/tabs.tsx

This is important for two reasons:
1. It means that DOM state doesn't get reset when you switch tabs. As a simple but important example, the comment input in the "comments" tab on contracts doesn't get cleared if you switch to the bets tab and back.
2. It means that we can store per-tab React state that doesn't get reset when you switch tabs. For example, on the contract page, we can load the bets list inside the bets tab component without having it have to reload every time you switch to the bets tab. So we will be able to make the user and contract pages load faster by pushing down more tab-specific state in this way.
This approach has a downside, which is that all the tabs will render in advance of viewing them. However, we can and should make rendering fast; for example, the really …

Change tabs to keep all individual tab components in the DOM

---

web/components/contract/contract-tabs.tsx
web/pages/[username]/[contractSlug].tsx

That's the only thing that needs it, so no point re-rendering the rest (e.g. re-rendering the chart is very expensive.)
Actually, only the bets tab needs it, but our tab design is kind of fucked, so further improvements can come later.

Move liquidity provision fetch down into `ContractTabs`

---

web/components/fullscreen-confetti.tsx
web/components/user-page.tsx
web/pages/[username]/[contractSlug].tsx

Previously, the user and contract page would do extra re-renders of the whole content area on load (and on resize) due to the `useWindowSize` hook. Now that hook serves only the `FullscreenConfetti` component.

Componentize confetti to isolate re-renders due to window size

---

web/components/portfolio/portfolio-value-section.tsx
web/components/user-page.tsx

Now that the tab state is persistent, we can easily move the portfolio history loading in here, so it doesn't have to re-render the main page when it loads.

Only load portfolio history inside user page bets tab

---

functions/src/create-user.ts
web/components/auth-context.tsx
web/components/groups/group-chat.tsx
web/components/nav/nav-bar.tsx
web/components/nav/sidebar.tsx
web/components/notifications-icon.tsx
web/hooks/use-admin.ts
web/hooks/use-state-check-equality.ts
web/hooks/use-user.ts
web/lib/firebase/users.ts
web/pages/_app.tsx
web/pages/create.tsx
web/pages/home.tsx
web/pages/links.tsx
web/pages/notifications.tsx
web/pages/profile.tsx

Previously, `AuthContext` tracked the user doc, and if you wanted the private user doc, well, you could go get it yourself.
Nowadays, literally every logged-in user page on our website needs the private user doc eventually, because it's used to serve information about notifications, which show up in the sidebar. There's no reason for the auth context to not just look it up too as soon as it knows who you are logged in as, instead of waiting until someone asks for it later, since doing two requests (for the user and private user) in parallel should be almost as fast as doing one anyway.
So now, the auth context fetches the private user doc when you log in, and SSR also will pass it through to the auth context if fetched, and the `usePrivateUser` hook gets it from the auth context.

Teach `AuthContext` to manage the private user doc

---

web/components/contract/contract-details.tsx
web/components/datetime-tooltip.tsx
web/components/feed/copy-link-date-time.tsx
web/components/relative-timestamp.tsx

These timestamps are most of the cost of rendering a big feed of comments or bets. I think basically the real culprit here is the tooltip code, which is doing a ton of work to compute where the tooltip should be, but might as well fix the easy stuff.
`dayjs(...)` isn't that expensive -- it's constructing a few objects and calling a few different things -- but it's expensive enough that we shouldn't call it thousands of extra times per render just for fun.

Make `RelativeTimestamp` a little more efficient

---

firestore.rules

The reason this is smart, is because if the Firestore rules refer to the document data, it will blow up requests that try to get or update a document that either doesn't exist or doesn't have that data (e.g. due to a bug.) So it's just better to not do that if the same data is in both the path and the document.

Tweak Firestore user rules to be more robust

---

web/components/tooltip.tsx
web/package.json
yarn.lock

Currently chats are super slow to scroll, because every single tooltip has to recalculate its position.
To fix, we only render the tooltip when it is visible, rather than using `:hover` and `:focus` css.
See also the warning in: https://floating-ui.com/docs/react-dom#updating

Improve performance of tooltip

---

common/util/array.ts
web/components/bets-list.tsx
web/components/comments-list.tsx
web/components/user-page.tsx
web/lib/firebase/server-auth.ts
web/pages/[username]/index.tsx

Efficiency changes:
1. Changed the user page to be server-side rendered, so that the sidebar loads nicely and re-renders are minimized.
2. Changed the user page tabs to load the data they need inside the tab component, rather than waiting up front for it.
3. Paginated the comments tab to reduce the rendering burden.
Functionality/presentation changes:
1. Removed the number on the tab headers. This number is fine but computing it is expensive so it's not worth doing. If you really like the number, feel free to denormalize it on the user document and then put it back into the UI.
2. Changed the comments list to sort by date, instead of sorting by "date within contract" and always presenting all comments on a single contract together. I think this is better, but it also works in a way that …

Revamp a lot of stuff on the user page to make it usably efficient

---

web/components/contract-search.tsx
web/package.json
yarn.lock

Previously, when you (for example) scrolled to the bottom of the contract search grid, this would happen:
1. The `loadMore` callback would be called.
2. It would call `setPage`, triggering a re-render of the grid. (This is obviously fishy since visually, absolutely nothing changed.)
3. The change in the `page` prop would trigger an effect that is looking at many dependencies and performs a new search query.
4. Later, your query would produce results.
5. `setHitsByPage` and `setNumPages` would be called. This would actually trigger two re-renders, because in React <18, state changes that aren't directly inside the React render code aren't batched.
Now:
1. The `loadMore` callback is called.
2. It directly invokes `queryNextPage`, instead of changing state, so no re-render happens.
3. Later, …

Simplify and fix inefficiencies in contract search component

---

web/components/contract-search.tsx

I think this change is good because typing in the search bar needs to be responsive for the search to feel good, so it sucks if that typing triggers a re-render on the whole grid of loaded contracts. Anyway, it's nice to put things in components.
The diff looks scary, but I didn't change much -- basically I just uprooted all the "figure out what search to do" code into a separate component that calls an `onSearchParametersChanged` callback to do the search with the new parameters.
(P.S. The search still isn't perfectly snappy yet. The main thing I need to fix next to make it snappy is the `useQueryAndSort` machinery, which A) literally throws out characters you type B) basically triggers re-renders on the whole page when the query parameter is updated.)
(P.P.S. I might make some …

Move search controls into separate component

---

web/components/contract/contract-card.tsx
web/components/contract/contract-details.tsx
web/components/contract/quick-bet.tsx

Rendering the contract cards is surprisingly expensive, so just cleaning up obviously unnecessary layers of cruft that has accumulated on them. Should be no visible changes.

Clean up a bunch of markup and CSS on contract cards

---

web/components/contract-search.tsx
web/components/contract/contracts-grid.tsx
web/components/editor/market-modal.tsx
web/hooks/use-sort-and-query-params.tsx
web/pages/contract-search-firestore.tsx
web/pages/group/[...slugs]/index.tsx
web/pages/home.tsx
web/pages/tag/[tag].tsx

OK, so the previous state of affairs looked like this:
1. There existed a hook called `useQueryAndSortParams` which served the query box and "sort" dropdown on contract grid search areas.
2. It's hard to explain exactly what it did because it had a bunch of flags, but basically, it would maintain some combination of React state, URL query string state, and local storage state corresponding to the most recent query and sort you did, and handed that back to the caller along with setters.
3. One problem with this code is that it was confusing.
4. Another problem was that it used the Next.js `Router.replace` API, which does a [ton of work](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/router.ts#L952), including but not limited to re-rendering the page root. …

Rewrite `useQueryAndSortParams` machinery to be faster/simpler/better

---

functions/src/create-contract.ts

Previously, if you passed an invalid group ID, it would create the contract, and charge you money, but then error out and not do any of the other things you need to do for a new contract! Very bad. Now it validates the group up front.

Bail out earlier if `createmarket` is called with invalid group ID

---

common/comment.ts
common/util/array.ts
firestore.indexes.json
functions/src/on-create-comment-on-contract.ts
functions/src/scripts/denormalize-comment-contract-data.ts
web/components/comments-list.tsx

Now we have a `contractSlug` and `contractQuestion`.
This is a big deal for the user profile, because otherwise we have to load the contract doc for every comment. Now we don't.

Denormalize some contract comment fields

---

web/components/editor/mention-list.tsx

~I think this happened after Marshall's optimizations to Avatars, though I don't know exactly why.~
This happened due to https://github.com/manifoldmarkets/manifold/commit/34e8138e5096e1ad8a4944566328703bd080c645
Solution is to simply telling react to rerender the component by providing a key

Fix user avatar in mention list not updating

---

web/components/tooltip.tsx

Headless UI's Modal component autofocuses the first focusable item inside it when opened. This is [by design for accessibility reasons](https://headlessui.com/react/dialog#managing-initial-focus). 
Ironically this means we'll have to remove keyboard focus for tooltips because this causes the tooltips to pop up unnecessarily for all users whenever the dialog is opened.
Doing this in an accessible way would involve is managing focus manually for several dialogs, which may not be possible yet as some of our modals lack a sensible element to focus by default. Or maybe disabling the autofocus unless the modal is opened via the keyboard (maybe complicated?)
I'm somewhat unhappy with this but I think doing it the unaccessible way is the right thing to do, in a utilitarian sense.

Fix tooltip popping up when modal is opened

---

common/comment.ts
functions/src/on-create-comment-on-contract.ts
functions/src/on-create-comment-on-group.ts
web/components/comments-list.tsx
web/components/contract/contract-leaderboard.tsx
web/components/contract/contract-tabs.tsx
web/components/feed/activity-items.ts
web/components/feed/contract-activity.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/components/feed/find-active-contracts.ts
web/components/groups/group-chat.tsx
web/components/tipper.tsx
web/hooks/use-comments.ts
web/lib/firebase/comments.ts
web/pages/[username]/[contractSlug].tsx
web/pages/group/[...slugs]/index.tsx

Now it works like typing for contracts; the type narrows on the `commentType` field and then it knows whether it's supposed to have contract-related stuff or group-related stuff.

Make typing for comments more fancy

---

web/components/avatar.tsx

> Now that you mention it, I might have noticed other avatar weirdness elsewhere. Like when I logged in as someone else, the old avatar was still showing. - @jahooma 
I can't reproduce, so I can't test your issue, but I think the ultimate cause is https://github.com/manifoldmarkets/manifold/commit/34e8138e5096e1ad8a4944566328703bd080c645
The moral of the story is don't replicate props as state

Make Avatar component update when avatarUrl updates

---

functions/package.json
web/components/contract-search.tsx
web/components/contract/contracts-grid.tsx
web/components/editor/market-modal.tsx
web/pages/group/[...slugs]/index.tsx
yarn.lock

This is actually kind of a huge pain to get exactly right...
- The Tailwind `columns-2` solution doesn't order them in the ideal left-to-right ordering. But [`order-[x]`](https://tailwindcss.com/docs/order#class-reference) doesn't work either
- Firefox has support for Masonry https://stackoverflow.com/a/45200955/1222351
- MaterialUI has this implemented https://github.com/mui/material-ui/pull/27439
So here's this somewhat hacky solution, which seems to work okay.
TODO: Have to fix the 1-column version - unfortunately, detecting whether we're in md: breakpoint in React/JS seems to be annoying too

Use masonry on contract cards, sorted correctly

---

functions/src/api.ts
functions/src/create-group.ts
functions/src/scripts/convert-tag-to-group.ts

There are some old tags that people liked, so it's good to make groups out of them so that people can enjoy the fruits of their effort categorizing the old contracts.
P.S. there was some stuff busted on dev by trying to use the wrong Manifold user ID, like notification generation. Whatever.

Convert tags to groups on demand

---

functions/src/on-update-contract.ts

Since descriptions are now rich text and not append-only, the previous way of calculating the changes will not work, and there isn't a simple way to fix it. For now, we just say that the market description changed without saying what in it changed.

Fix notification for updated questions and descriptions

---

firestore.indexes.json
web/components/comments-list.tsx
web/components/pagination.tsx
web/hooks/use-pagination.ts
web/lib/firebase/comments.ts

WIP. This is intended to replace the existing user comments list, user bets list, contract bets list, and maybe other things where we need paginated loading to deal with the quantity of data we are interested in.
Feedback on the general design is welcome. (Feedback on tiny details might be useless as I continue to refactor the thing.)
TODO: General improvements, good pagination UI, fixing the client filter to be smarter (i.e. it should continue to load more pages until you filled up one page size worth of stuff.) Think about react-query integration for making prev-next instantaneous. Think about the matter of live updating on individual items.

Create and use new `usePagination` hook for paginating loading

---

web/components/portfolio/portfolio-value-graph.tsx
web/components/portfolio/portfolio-value-section.tsx
web/lib/firebase/users.ts

Since the default view period is a week, it sucked to pull down the whole history.
Note that the old code sort of implied that there might be history for prior to June, but in the actual database it seems that history was removed. There was no mechanism for filtering stuff only past June, and at a glance, it seems like the history collections I can find don't contain pre-June data points. So e.g. the code that was showing the "since June" label was never doing anything.
I also re-enabled the "daily" option. Austin claimed in [this commit](https://github.com/manifoldmarkets/manifold/commit/258b2a318fa626df536ca31ce178ec6ea6af4919) that it's "broken" but I see zero evidence of that. I'm guessing he got confused by the thing where the metrics update job was busted for a few days due to OOM.

Make portfolio graph loading more efficient

---

web/components/contract/contract-prob-graph.tsx
web/pages/[username]/[contractSlug].tsx

1. The component was memoized, but the bets coming in were changing, so it was re-rendering unnecessarily.
2. The stuff it was doing was so inefficient it was taking O(tenths of a second) during render on large markets to just prepare the data set. (`dayjs` is really slow, don't use it more than you have to.)
3. It was generating interpolated graph points even before the bets loaded, which was both useless work and also ugly. This is what caused the graph to look like it was at 50% until the page loaded. Now it looks empty which I think is way better.
This substantially improves the loading jankiness of e.g. the Elon Musk market.

Fix some efficiency problems with `ContractProbGraph`

---

web/components/contract/contract-details.tsx
web/components/datetime-tooltip.tsx
web/components/feed/copy-link-date-time.tsx
web/components/feed/feed-bets.tsx
web/components/relative-timestamp.tsx
web/components/tooltip.tsx
web/pages/tournaments/index.tsx

It looks sort of ridiculous, but a huge part of the cost of rendering our lists is these tooltips, so let's do basic things to try to make them more efficient. It won't matter as much once we're paginating these lists, but it won't not matter, either.
In particular, the `dayjs` formatting is really inefficient and you probably shouldn't use it unless you have some reason to. (For example, according to my profiler -- which I believe because I read the `dayjs` code -- formatting all the timestamps for the bet tooltips in the Elon Musk market took a large part of a second on my laptop.) The normal browser API does an equally good job efficiently.

Make tooltip rendering more efficient

---

web/components/feed/copy-link-date-time.tsx

Just fixing up tiny stuff I noticed.

Clean up markup in CopyLinkDateTimeComponent

---

web/components/groups/group-chat.tsx
web/components/notifications-icon.tsx
web/hooks/use-notifications.ts
web/lib/firebase/notifications.ts
web/pages/notifications.tsx

React query has a bug for subscribing to `useFirestoreQueryData`. I found a workaround online: https://github.com/invertase/react-query-firebase/issues/25
Secondly, I realized that if Nextjs Link components navigate client-side, we can always have the latest notifications fetched if we listen for them in the sidebar with the same query.
Now there is no fetch time at all to visit Notifications page! Except for the first load in which we show a loading indicator. Also removed the local storage for notifications since they are no longer necessary.

React-query-ify notifications

---

functions/src/scripts/backfill-unique-bettors.ts
web/components/bets-list.tsx
web/components/nav/sidebar.tsx
web/components/portfolio/portfolio-value-section.tsx
web/hooks/use-contracts.ts
web/hooks/use-notifications.ts
web/hooks/use-portfolio-history.ts
web/hooks/use-prefetch.ts
web/hooks/use-user-bets.ts
web/lib/firebase/bets.ts
web/lib/firebase/contracts.ts
web/lib/firebase/users.ts
web/pages/[username]/[contractSlug].tsx
web/pages/home.tsx

From the insight that NextJS does client-side navigation when clicking Links, it means we can cache data in-memory.
This PR caches all the user bet data, including portfolio history, user bets, and the contracts corresponding to your bets using react query.
Further, we call these hooks on home and the market page to "precache" the data so that it will load instantly when navigating your user page bets tab.
To make this work, I backfilled the `uniqueBettorIds` in every contract so that we can query all the contracts you have bet on in one go.

⚡ Cache user bets tab with react query!! 

---

package.json
web/components/feed/feed-comments.tsx
web/lib/firebase/server-auth.ts
yarn.lock

Typescript 4.8 is out so let's upgrade to it and keep other related stuff up-to-date.
Typescript 4.7: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
Typescript 4.8: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/

Upgrade Typescript, ESLint, Prettier

---

web/hooks/use-contracts.ts
web/hooks/use-portfolio-history.ts
web/hooks/use-prefetch.ts
web/hooks/use-user-bets.ts

Since we (maybe?) have some reason to believe that this prefetching is hurting us due to increased memory pressure, let's at least not copy the prefetched data into state for no reason.

Fix prefetching to not populate useless state

---

web/components/answers/answers-graph.tsx
web/components/contract/contract-description.tsx
web/components/contract/contract-details.tsx
web/components/contract/contract-overview.tsx
web/components/contract/extra-contract-actions-row.tsx
web/pages/[username]/[contractSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

This was hard for me to understand because it was a big rat's nest of "if it's contract type X, show Y", so I cleaned it up by factoring out the stuff that was the same between different kinds of contracts and making separate contract type overview components for the stuff that was different.
Basically no user-visible changes (I moved some of the pixels around a tiny bit.)

Clean up contract overview code

---

web/components/contract/contract-details.tsx

I wasn't able to convince James to disable most prefetching, but at least we compromised to not prefetch groups on contracts for as long as those groups are really expensive to prefetch (i.e. right now they load all their members, etc. etc.) since this is a particularly gross thing in the way of making the home/contract user flow better.

Disable group prefetching from contract links

---

web/components/following-button.tsx
web/components/referrals-button.tsx
web/hooks/use-contracts.ts
web/hooks/use-portfolio-history.ts
web/hooks/use-prefetch.ts
web/hooks/use-user-bets.ts
web/hooks/use-user.ts
web/lib/firebase/bets.ts
web/lib/firebase/contracts.ts
web/lib/firebase/users.ts
web/pages/api/v0/user/[username]/bets/index.ts

We didn't understand how react-query worked, so we didn't realize that we needed to use the context's `QueryClient` to store the cached data. So our prefetches were having no effect.
Now the prefetching should work.

Make prefetching correctly use context cache

---

web/pages/home.tsx

Before, it was good for /home to have SSR because it was meant to kick you out if you were logged out, and SSR was the best method to accomplish that.
But now, /home basically looks the same whether you are logged in or logged out, so doing SSR auth has little benefit, and slightly slows down navigations to /home (e.g. it makes going back from contracts to the search slightly slower, and it's really good for that to be absolutely as fast as possible.)

Disable SSR on /home

---

web/components/visibility-observer.tsx

I don't think this was causing any actual problem, but it was just obviously silly to re-create the `IntersectionObserver` object whenever the ref changes.

Don't re-create visibility observer for no reason

---

web/components/auth-context.tsx

A variety of small things:
1. The `listenForUser` and `listenForPrivateUser` subscriptions that keep track of the current logged in user docs weren't handling the case where (surprisingly) they can't find the user by ID. But this case actually was coming up in the case where you (e.g. on your local dev server) have a cached user object for prod, and then log into dev, and now you have one with an invalid dev database ID. The consequence is that it would mysteriously explode on the first page load and make a scary message. Now we handle this much more gracefully.
2. Those subscriptions also weren't updating the local storage blob when your user info changes, which they should.
3. It was really weird that we called the `setCachedReferralInfoForUser` on every login even though it only …

Some changes to make auth better

---

web/next.config.js

https://nextjs.org/docs/advanced-features/source-maps
We don't really care about build time and it's frequently a pain in the ass not to be able to debug and profile the production site properly.

Enable source maps in production

---

common/comment.ts
functions/src/on-create-comment-on-contract.ts
functions/src/scripts/denormalize-comment-bet-data.ts
web/components/feed/feed-comments.tsx

This is making progress towards not forcing the comment tab to load all the bets on the contract.

Denormalize `betAmount` and `betOutcome` fields on comments

---

web/lib/firebase/contracts.ts
web/pages/tournaments/index.tsx

https://github.com/manifoldmarkets/manifold/pull/832 broke group leaderboards. The changes to contracts.ts made it so only not-resolved contracts where pulled up to build the leaderboards, which broke the Top Trader group leaderboard (every item shows 0 profit).
Example:
I'm not going to wait for a review as the changes are trivial and this should be fixed immediately.

[Regression] Fix feature-breaking bug in Group Leaderboards

---

common/calculate-metrics.ts
common/scoring.ts

Relevant task: https://www.notion.so/manifoldmarkets/Change-group-leaderboard-to-update-based-on-bet-value-in-unresolved-markets-1a55b41650a04d468225212bb49a11e7
@jahooma Please help me validate whether the math here is correct. 
Sanity-checking on Localhost seems to work. I printed out the values of investmentValues for each user, and it's what I expect. For any given contract, they match the sum of these two values, which I believe is what's expected:
Looking at some example group leaderboards, it seems to be correct as well. For the group that contains the contract from the last image (the only one I bet on):

Adds investmentValue to group leaderboard calculation

---

common/package.json
common/util/parse.ts

This is necessary for rendering the OG meta description when loading the content page, so it's in the hotspot for the user browsing flow. Profiling suggests that recomputing the ProseMirror schema every time (the behavior of the previous version) may cost on the order of tens of milliseconds. That code is [here](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/helpers/getSchemaByResolvedExtensions.ts#L23) -- I don't know if I believe the profiler but clearly we should just not do this.
I continue to update in the direction of "ProseMirror may or may not be good, but TipTap is often suspicious." It's kind of ridiculous to me that the `generateText` method they supplied took the extensions instead of the schema as an argument. Not a good design.
EDIT: Before merging this I …

Make `parse.richTextToString` more efficient

---

web/components/feed/feed-liquidity.tsx

These just looked misaligned in the UI. Now they look the same as the bets.

Fix liquidity feed display to look right

---

common/antes.ts
common/bet.ts
common/new-bet.ts
common/sell-bet.ts
functions/src/change-user-info.ts
functions/src/on-create-bet.ts
functions/src/place-bet.ts
functions/src/scripts/denormalize-avatar-urls.ts
functions/src/scripts/denormalize-bet-user-data.ts
functions/src/scripts/denormalize-comment-bet-data.ts
functions/src/scripts/denormalize-comment-contract-data.ts
functions/src/scripts/denormalize.ts
functions/src/sell-shares.ts
web/components/contract/contract-leaderboard.tsx
web/components/feed/feed-bets.tsx
web/components/limit-bets.tsx

Pretty self-explanatory. Previously we needed to get the user doc for every bet.
Changing this is more valuable than you might think, even in the world when the contract bets tab and order book (the two places where we show a lot of bets that aren't yours) are paginated, because not only is it relatively expensive to get all the whole user docs separately, it's actually relatively expensive to just create and destroy react-query queries (i.e. what we were currently doing with `useUser`.) It's quite bad to be creating dozens of them and then throwing them out when you leave the page.

Denormalize user display fields onto bets

---

web/components/contract/contract-tabs.tsx
web/components/feed/contract-activity.tsx
web/components/feed/feed-liquidity.tsx

This is just "placebo pagination" -- for now it's still loading all the bets. However, rendering bets is pretty slow, relatively speaking, because of the links and tooltips. So this is actually a nice speedup to loading and unloading on contract pages (i.e. when you press the back button and React has to clean up all the old crap) and we might as well just do it instead of waiting for "real pagination" to land.

Paginate contract bets tab

---

common/calculate.ts
common/comment.ts
functions/src/on-create-comment-on-contract.ts
functions/src/scripts/backfill-comment-position-data.ts
web/components/contract/contract-leaderboard.tsx
web/components/contract/contract-tabs.tsx
web/components/feed/contract-activity.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx

Now we don't have to load all bets on a contract to show comments on non-FR markets. At the moment, we still have to load the current user's bets to figure out which bet a comment might be associated with, which is basically OK for now.
We are still in fact loading the bets for other reasons, but this is one step closer to a post-loading-all-bets world.

Precalculate and store positions for commentors

---

web/components/feed/contract-activity.tsx

Not sure what the deal with this is, but there are comments in the DB associated with a bet for outcome X, but which have no `answerOutcome` field. They should definitely be in the thread for that bet's answer.

Make comments with bet outcome but no answer outcome appear

---

web/components/nav/group-nav-bar.tsx
web/pages/group/[...slugs]/index.tsx

Moves the groupnavbar to the top, so it doesn't feel like the bottombar is changing

Move group navbar to top

---

web/components/feed/feed-answer-comment-group.tsx

The code tracking the most recent bet time is literally dead as far as I can tell.
The code closing the reply box if the most recent bet is for another answer is very strange to me and I don't see why anyone would ever want it. The reply boxes start out closed, so on first render, this effect does nothing. Subsequently, it does something if you open some reply boxes and make a bet; it will then close any reply boxes for answers other than the one you bet on. This seems foolish to me; why would they have clicked reply if they want you to close the box? It could even lose someone's in-progress comment. I think this code is better off gone.
The motivation here is continuing to reduce the dependency of various rendering code on having access to random bets and so on.

Cleanup free answer comment stuff

---

web/components/feed/feed-answer-comment-group.tsx

I think this was back from the "feed" days, when we would sometimes render these answers in the main page feed instead of on the contract page. Now we would never want to hide this 'reply' button.

Remove old check in free answer comment rendering

---

firestore.indexes.json
functions/src/on-create-comment-on-contract.ts
web/components/comment-input.tsx
web/components/contract/contract-tabs.tsx
web/components/feed/contract-activity.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/lib/firebase/comments.ts

This is attractive because, as you can see by looking at the diff, it means that we don't have to thread down a ton of context about recent bets and recent comments into the comment posting UI, so it substantially simplifies the comment posting UI code and opens the door to further efficiency improvements.
The only functional difference between this code and the previous code is that the previous code would actually create comment documents with the same Firestore ID as their associated bet document (i.e. a comment associated with `contracts/ABC/bets/DEF` would go to document `contracts/ABC/comments/DEF`). This is cute but as far as I know we never made use of this property, and I am not sure why we would use it in the future instead of just querying by ID.

Move comment-bet association code into comment creation trigger

---

web/components/contract/contract-tabs.tsx

It's pretty bad to have to load all comments and bets to get these counts; it means we have to load everything without pagination, and means we can't render the tab control until the counts are in. (As opposed to if we leave the counts out, we can render the comments tab as soon as comments are in, and the bets tab as soon as the bets are in.) I plan on making changes shortly to contract page loading that are incompatible with having these counts.
If we really wanted these numbers, we could make some complicated triggers that track them, but I don't think they are important, so that seems like more work than it's worth.

Kill counts of comments and trades on contract page

---

web/components/contract/contract-leaderboard.tsx
web/components/contract/contract-tabs.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/pages/[username]/[contractSlug].tsx

By not rendering a tip widget in the "resolved contract top trades" box, we only need to fetch the tips for rendering the tab area, not at the top level of the contract, so we can render more sooner and re-render less later.

Don't always require tips to render comments

---

web/components/contract/contract-leaderboard.tsx
web/components/contract/contract-tabs.tsx
web/pages/[username]/[contractSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

Further cleanup. Now the comments are only required by the comments tab and the "top comment" thing on resolved markets (which is only on resolved markets, so we don't care about it as much.) As a result, we can comfortably remove the comments from the `getStaticProps` payload and load them async in the page.
Also making a dent in re-renderings.
On my laptop, this PR pretty much moves the needle on loading the biggest market pages (e.g. ACX discord market, elon musk twitter market) from "basically unusable" to "kind of OK" so that's cool.

More work on contract page and tabs

---

web/components/contract/contract-leaderboard.tsx
web/components/leaderboard.tsx
web/pages/group/[...slugs]/index.tsx
web/pages/leaderboards.tsx

Since bets now have the denormalized information that the leaderboard needs to render entries (name, username, avatar), we no longer need to load any additional data other than the bets in order to render the contract leaderboard.
Also fixed a small bug where the "top trades" logic was slightly broken in my new world where bet IDs and their associated comment IDs aren't always the same.

Improve contract leaderboard computation

---

web/components/auth-context.tsx
web/components/avatar.tsx
web/components/landing-page-panel.tsx
web/next.config.js
web/package.json
web/pages/_app.tsx
yarn.lock

I don't know of anything important here in particular, but it's nice that they stabilized the image component we use, and it might be nice to try out the SWC minifier and see if it's better than the status quo.
https://nextjs.org/blog/next-12-3
https://github.com/vercel/next.js/releases/tag/v12.3.1

Next.js 12.2.5 -> 12.3.1

---

web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx

1. There's no reason to wait for a `useEffect` before looking at the router path, so we don't need to store `highlighted` in state.
2. The permalink scrolling broke when I started loading the comments on the client, so I needed to add additional code to scroll to highlighted comments when those comments actually first render. (The answer items are available immediately, but they are in the comments tab, which doesn't load until the comments are ready, so we need to do the same thing for them.)

Fix up comment permalink stuff

---

functions/package.json
web/package.json

This was just in the wrong one for no particular reason.

Move react-masonry-css dependency to web package.json

---

web/next.config.js

This is no longer a thing, the future/image component is present by default in 12.3.
https://nextjs.org/blog/next-12-3#nextfutureimage-component-stable

Remove images config from next.config.js

---

web/components/amount-input.tsx
web/components/bets-list.tsx
web/hooks/use-is-mobile.ts

These are random things that were causing re-rendering on window resize, so they were very unpleasant. Now re-rendering on resize doesn't happen unless something actually needs to be re-rendered (e.g. layout transitions between mobile and desktop, or recommended contracts column count changes), **_except_** for the probability graph, which re-renders on every resize and makes everything feel laggy and slow. But I'm going to rewrite the whole graph shortly so I'm not going to bother fixing that.

Fix some rendering issues on contract page

---

web/lib/service/sprig.ts

didn't read our own docs carefully enough and forgot about this issue
it's causing the initial "identify the user with their id/email" call to fail
see the "html script tag" variation here https://docs.sprig.com/docs/web-javascript#values

add to queue rather than invoking sprig object directly, as it's still being setup

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/helpers.tsx

Yev pointed out a problem with the old code; if your client has a laggy clock compared to our DB, then if you got a new bet that was "in the future" according to you, the chart wouldn't extend on the right all the way to the new bet, so you wouldn't see it. Now the chart extends to `max(bet-date-max, now)`.

Fix potential clock sync issues with graph updating

---

web/components/charts/generic-charts.tsx

Pretty self-explanatory. Basically, if your mouse is perfectly on the edge then the result from `xScale.invert` might be slightly outside the bounds of the data points on the chart.

Fix an edge case with chart mouseover tooltips

---

web/components/charts/helpers.tsx

This may fix the "white chart area" bug that people were reporting to me, where part of the chart turns white while selecting a time range with the brush. I was able to reproduce a similar phenomenon using Chrome on my Linux ThinkPad and this fixed it.
I don't really have any hypothesis for what might be going wrong, I suspect it's probably some difficult-to-fathom Chrome bug. It certainly doesn't make any logical sense that this brush rectangle could have something to do with the entire fill of the chart path.

Hack up brush rendering to fix possible Chrome bug

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/pseudo-numeric.tsx

Because we put a data point with the current probability far in the future (so we can rescale the chart to a later time without regenerating the data points), it's good to clamp the time scale. Otherwise, we generate a big line way off to the right in the SVG when d3 sees the final point of data. It gets clipped, so you can't see it, but this is the kind of thing that could create glitches like in #950.

Clamp time range in history chart scales

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/pseudo-numeric.tsx

Now these don't re-render unless the actual contract properties that affect the charts change, even if something else on the contract changes.

Make binary and pseudonumeric charts re-render less on contract diff

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/numeric.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/generic-charts.tsx

This is so that if we want to experiment with changing other elements on the page (e.g. the big number up top) in response to someone hovering at different points in time on the chart, that experiment is easy to do. We'll also need it for that purpose on the portfolio graph.

Expose `onMouseOver` chart event to hook into from outside

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/helpers.tsx

TIL that `new Date(1234) !== new Date(1234)`. So we have to keep them as numbers to make `useMemo` work well. This is for the case where some stuff changes in a contract but we don't need to recompute any data points for the chart.

Fix date memoization in charts

---

web/components/answers/answer-bet-panel.tsx
web/components/answers/answer-resolve-panel.tsx
web/components/bet-panel.tsx
web/components/bets-list.tsx
web/components/button.tsx
web/components/confirmation-button.tsx
web/components/groups/create-group-button.tsx
web/components/numeric-resolution-panel.tsx
web/components/resolution-panel.tsx
web/components/warning-confirmation-button.tsx
web/components/yes-no-selector.tsx
web/pages/profile.tsx

this is so submit won't turn black, although now that I think about it closing the modal would've been a lot easier rip.
I basically just have replaced the daisy button for `ConfirmationButton`'s `openModalBtn` with our custom `Button` component, which ended up affecting quite a few other buttons.

getting rid of daisy buttons

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/numeric.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/helpers.tsx

Basically self-explanatory. This gets the sizing, padding, border, colors, and text strength the same, even though the content is a little different for now.
FYI @ingawei

Change styles on contract tooltips to be more like portfolio graph

---

web/components/charts/helpers.tsx
web/components/portfolio/portfolio-value-graph.tsx

Now they look more like the portfolio charts; the color and area fill opacity match.
Not sure what to do with the top line... making it chunkier doesn't really look good to me. Feel free to play around with it; you would just need to fiddle with the `strokeWidth` property on the `AreaWithTopStroke` `LinePath` component.
FYI @ingawei

Chart visual style adjustment

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/choice.tsx
web/components/charts/contract/numeric.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/generic-charts.tsx
web/components/charts/helpers.tsx

Now the charts can pass data through to the tooltips that aren't "a single data point", including the mouse position, so the space of technical tooltip design flexibility is greatly increased.

More refactoring to make chart tooltips more flexible

---

functions/src/scripts/contest/bulk-add-liquidity.ts
functions/src/scripts/contest/bulk-resolve-markets.ts

@akrolsmir randomly checked this in busted and broke the build.

Mark scripts as modules to avoid global name collision

---

yarn.lock

@IanPhilips tried to upgrade this in #944 but seemingly forgot to check this in.

Bump heroicons yarn.lock version to 1.0.6

---

common/util/parse.ts

opening a new pr instead of putting in #942 because I am more suspicious of this code and reverting new extension code in 942 can break things

Hide spoiler content in emails / notifs

---

web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/components/tipper.tsx
web/posts/post-comments.tsx

Similar to #999. This isn't perfect, because it still re-renders when the comments are all re-loaded from the subscription, but it does prevent re-rendering of (most, untipped) comments when the tips come in.

Change `Tipper` interface, memoize `FeedComment`

---

web/components/feed/feed-bets.tsx

This is valuable because this bets list has to re-render when the LPs come in, even though most of the content is the same bets and contract. Unfortunately it doesn't save us when we subscribe to the bets and get the same list that was in the static props.

Memoize `FeedBet` component

---

web/components/amount-input.tsx
web/components/answers/answer-item.tsx
web/components/answers/create-answer-panel.tsx
web/components/answers/multiple-choice-answers.tsx
web/components/challenges/create-challenge-modal.tsx
web/components/contract-search.tsx
web/components/contract/contract-description.tsx
web/components/contract/contract-details.tsx
web/components/create-post.tsx
web/components/expanding-input.tsx
web/components/filter-select-users.tsx
web/components/groups/create-group-button.tsx
web/components/groups/edit-group-button.tsx
web/components/input.tsx
web/components/manalinks/create-links-button.tsx
web/components/number-input.tsx
web/components/probability-input.tsx
web/components/probability-selector.tsx
web/pages/charity/index.tsx
web/pages/contract-search-firestore.tsx
web/pages/create.tsx
web/pages/date-docs/create.tsx
web/pages/groups.tsx
web/pages/home/index.tsx
web/pages/profile.tsx

Refactors all our `input input-bordered` text inputs to use a shared component. This will make it easier to restyle all of them to match our rich-text editors and `<select>` menus (although actually doing that is left as an exercise for ~inga~ later)
This fixes a ~bug~ feature in iOS safari where focusing an `<input type="text" />` with font size less than 16px will cause the browser to zoom in. This became an issue after my SEO changes (removing `max-scale=1`)

refactor text input into one component

---

web/components/editor.tsx
web/components/editor/market-modal.tsx
web/components/editor/tiptap-grid-cards.tsx
web/hooks/use-contract.ts

The previous implementation of market card embeddings worked by embedding a page that showed a market grid via an iframe.
That worked fine, but we had no way of knowing in advance what the height of the iframe should be, so it resulted in either a scrollable grid of market cards, or a grid of market cards with unnecessary padding.
This new implementation embeds the ContractsGrid react component directly, which sidesteps the issue. 
I'm not deleting the old iframe pages just yet to not break existing posts that use them (like Jack's nuclear post), but all new market grid embeds will now use this new implementation.

New implementation of market card embeddings

---

common/util/parse.ts

instead of copy the json, dfs, then pass to `generateText`, we just generate the correct text inside of `generateText`
this is now possible after #1021 since these extensions are just used for the text conversion, so we can customize them just for this.

Simplify rich text to string parsing logic

---

web/components/bet-summary.tsx

This is a test PR to see if Linear is updating the corresponding issue automatically based on the branch name.
It's working! https://linear.app/manifoldmarkets/issue/MAN-16/position-tooltip-change-based-on-outcome-you-hold

Dynamically choose outcome in Position tooltip

---

web/components/charts/generic-charts.tsx

Now the graph calls `onMouseOver(undefined)` when your pointer stops hovering it, so the number correctly resets.

Fix the "portfolio graph top line number doesn't reset after hovering on chart" bug

---

web/components/charts/generic-charts.tsx
web/components/charts/helpers.tsx

This is new in React 18 and is a nicer solution than the `nanoid` version. It also works with SSR, which is nice.

Use new React `useId` hook in chart code

---

web/components/charts/helpers.tsx

Computing the path segments is basically the expensive operation of rendering a chart (it may plausibly take up to a few dozen milliseconds if you have a market with a few thousand data points and a slow computer), so by applying `useDeferredValue` to it, we make sure that the UI stays responsive if the chart is rendering (for example, it could be rendering because the contract metadata was changed, or a bet was made, or you just zoomed it.)
It's not a big deal because the charts are pretty fast, but this may help get pinch to zoom working in a satisfying way and is a good idea anyway.

Apply `useDeferredValue` on computation of SVG chart paths

---

web/components/charts/generic-charts.tsx
web/components/portfolio/portfolio-value-section.tsx

This was super suspicious before -- because it was mutating props without using React state, there were weird interaction bugs.
Now it's pretty decent, really the only problem is that we should write some clever formatting code so that the y-axis displays an appropriate amount of significant figures on the ticks for the range of values being displayed. (EDIT: I just addressed this by making it so that you can't zoom in tighter than 4% on percentage graphs or 10 bucks on portfolio graphs.)

Fix issues with chart y-axis zooming

---

web/components/contract/contract-tabs.tsx
web/hooks/use-bets.ts
web/hooks/use-user-bets.ts
web/lib/firebase/bets.ts
web/pages/[username]/[contractSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

WIP. There are actually many many redemption bets and zero bets (limit orders with no fills, cancelled or otherwise, can be zero.) These bets have no relevance to the chart, the contract leaderboard, or the trades tab, but we are downloading them anyway. For example, on one Elon Musk market these are half of all bets. So it's a big difference.

Don't load bets we don't need on contract page

---

web/components/buttons/button.tsx
web/pages/styles.tsx

Adds a `/styles` page with all of our widgets (well, just buttons and inputs for now)
https://prod-g62bqjmme-mantic.vercel.app/styles
I had this at one of my previous companies and it made debugging widgets easier and was also just good documentation. It's kinda like Storybook, but easier to maintain

Add internal Style page

---

web/pages/api/v0/bets.ts

Spell `max-age` correctly in `/bets` API cache headers

---

common/calculate.ts
web/components/bet/quick-bet.tsx
web/components/contract/contract-card.tsx
web/components/contract/contract-details.tsx
web/components/contract/contract-mention.tsx
web/components/contract/contracts-grid.tsx
web/components/contract/prob-change-table.tsx
web/components/outcome-label.tsx
web/components/portfolio/portfolio-value-graph.tsx
web/lib/icons/triangle-left-fill-icon.tsx
web/lib/icons/triangle-right-fill-icon.tsx
web/pages/home/index.tsx

Remaining launch blocking tasks:
- @ingawei to add in extra design polish.
- Find and fix and new bugs/design issues introduced
- Fix the secrets management issue, so coverImgUrls start being stored, and use that instead of the random stock image.
- Daily mover profit/position should update when a quick bet happens.
Non launch blocking:
- Free Response markets don't yet match the figma 
- Show quickbetting arrows even when signed out, but they just redirect to the login dialog

New design for Homepage

---

common/loans.ts
functions/src/update-loans.ts
functions/src/update-user-metrics.ts

This is just some cleanup subsequent to the changes I made in #1100. There's no efficiency advantage for the code in `loans.ts` to run the loan computations in a batch, so it's cleaner for its interface to not be batched.

Refactor loan code a little bit

---

common/calculate-metrics.ts

This is necessary for a variety of future work, incl. #1122.
It would be better for it to only update metrics for resolved contracts exactly once, after resolution; we will probably add this complication soon.

Update metrics for resolved contracts also

---

common/scoring.ts
functions/src/update-group-metrics.ts

WIP. Now `updateGroupMetrics` doesn't have to load all bets, so it's basically good enough for now.

Make `updateGroupMetrics` use precomputed contract metrics

---

web/components/activity-log.tsx
web/components/comments/comment-input.tsx
web/components/comments/comments-list.tsx
web/components/editor/mention.tsx
web/components/feed/feed-comments.tsx
web/components/posts/create-post.tsx
web/components/posts/post-comments.tsx
web/components/widgets/editor.tsx
web/components/widgets/linkify.tsx
web/pages/date-docs/[username].tsx
web/pages/post/[...slugs]/index.tsx
web/pages/swipe/index.tsx

- comments in old format (string) vs json are now the same size (14px)
- @mention and link now are now the same font weight (300px)
- post editor now has between-paragraph space, just like posts
- comment editor now same font size as comments
@ingawei I don't feel opinionated about any of these changes, I just think it should be consistent. To change the styles just change the `proseClass` function in editor.tsx. Previously the styles were split across multiple components in some cases but now its more consolidated
This adds a size property to `Content` and `useTextEditor` to make styling easier and more consistent.
@mantikoros now posts are just `Content` with `size='lg'` rather than `PostContent`

Make type styles more consistent

---

common/report.ts
common/user.ts
firestore.rules
native/App.tsx
native/android/app/build.gradle
native/app.json
native/ios/Manifold/Info.plist
web/components/buttons/block-user-button.tsx
web/components/buttons/report-button.tsx
web/components/contract/contract-info-dialog.tsx
web/components/feed/feed-comments.tsx
web/components/native-message-listener.tsx
web/components/native/add-funds-ios.tsx
web/components/onboarding/group-selector-dialog.tsx
web/components/onboarding/welcome.tsx
web/lib/native/is-native.ts
web/pages/add-funds.tsx

Reports are now top-level objects in the 'reports' collection.
Iphone native app users can use the 'take a photo' option in the editor now. 
Iphone native app users must agree to the TOS and privacy policy before using the site. 
IPhone native app users can't buy mana in the app :(. 
Perhaps we should make a /reports api to hook up zapier and get discord messages when people report content?

Apple review fixes

---

web/components/new-contract-panel.tsx

https://manifold.markets/ManifoldBugs/whenever-i-go-to-create-a-new-marke
Clear market description from localStorage after creating a market

Fix MAN-204

---

common/util/array.ts
web/components/nav/bottom-nav-bar.tsx
web/components/nav/sidebar-item.tsx
web/components/nav/sidebar.tsx
web/components/portfolio/portfolio-value-section.tsx
web/pages/labs/index.tsx

- add bottom section for sign out, help
- remove "Get M$", twitter
- Get Mana added to profile - which is where people will naturally click on to add money since it has your balance
- remove from mobile nav: search, profile, charity, refer friend
- You can still get to refer a friend from add funds modal, or from share link on a market
- Charity moved to labs
- Search and profile are already in the bottom nav
- remove metamore so groups and labs won't be jealous

Overhaul nav

---

web/components/add-funds-modal.tsx
web/components/native/add-funds-ios.tsx
web/pages/add-funds.tsx

- Now clicking on the cards redirects you (if that makes sense)
- The options have also been added to the add funds modal on a separate tab
- Add funds modal is adjusted on iOS, similar to add funds page
erate tab

Clean up additional mana options, add to modal

---

common/pseudo-numeric.ts
web/components/bet/quick-bet.tsx
web/components/feed/feed-bets.tsx

The market cards for resolved pseudonumeric markets were displaying "Resolved as X%" instead of "Resolved as Y".
This PR fixes this, and also cleans up related code in bet feed (Please don't nest so many ternaries! :scream: Especially when there already is a helper function that does exactly that)

Fix market card for resolved pseudonumeric markets

---

common/calculate-metrics.ts
functions/src/update-contract-metrics.ts

You can argue in principle whether this should be included, but there's a really good practical reason not to include it, which is that it isn't included in the contract total `volume` field. So if we include it in the period volume fields, those will be out of sync with the total (e.g. they could be higher than the total which looks ridiculous.)

Don't count ante bet in 24 hour and weekly volume

---

common/calculate-metrics.ts
common/loans.ts
functions/src/update-user-metrics.ts

GitHub won't let me reopen https://github.com/manifoldmarkets/manifold/pull/1171 but here it is!
Now all the work involving bets in `updateUserMetrics` only needs bets on unresolved markets, instead of all bets ever, so that's a lot better.
- You can only have outstanding loans on unresolved markets.
- We only need to compute the "investment value" for unresolved markets, since the investment value for resolved markets is 0.
- We only need to compute contract metrics for unresolved markets, if we make sure we compute it once at resolution, since they can't change post-resolution.

Make `updateUserMetrics` only consider bets on unresolved markets

---

docs/docs/api.md
web/pages/api/v0/bets.ts

This is important so that we can deprecate returning full comments and bets by default from the `/market` endpoint.

Make API /bets endpoint be able to look stuff up by ID

---

docs/docs/api.md
web/pages/api/v0/comments.ts

Like https://github.com/manifoldmarkets/manifold/pull/1181, this is important so that people can query market data without getting a firehose of bets and comments.

Add `/comments` endpoint for querying comments by contract

---

web/lib/firebase/bets.ts
web/pages/[username]/[contractSlug].tsx

This wasn't right before because it wasn't sorting in the query, so it could end up with something that wasn't a prefix of the bets.

More accurately produce the first N bets

---

functions/src/helpers/handle-referral.ts
functions/src/on-create-bet.ts
functions/src/transact.ts

I don't think this is the worst problem we have, but clearly this bet loading was performing totally needless carnage on our Firestore reads.

Make `onCreateBet` trigger more efficient

---

functions/src/on-create-bet.ts
functions/src/on-update-contract.ts

Currently, we were revalidating in `onCreateBet`, but when you place a bet sometimes it creates a bunch of bet documents, due to filling limit orders. It's much better to only revalidate once for all of those. So now it revalidates in `onUpdateContract` if the volume went up.

Be parsimonious with contract page revalidation

---

docs/docs/api.md
web/pages/api/v0/market/[id]/index.ts
web/pages/api/v0/slug/[slug].ts

This is desirable because they are expensive to fetch and return, and many people will not want them. Callers who want bets and comments can use the `/bets` or `/comments` endpoint to query them per market.

Remove bets and comments from market read APIs

---

functions/src/score-contracts.ts

@jahooma do you think this is reasonable? If not, we can add a 3-day metric for unique bettors on the contract. But I figure maybe 7 days is just as good for this purpose anyway.

Make popularity score based on 7 day window so we don't have to load all bets

---

common/firebase-auth.ts
web/components/auth-context.tsx
web/lib/firebase/server-auth.ts

On my box, this drops it from 2.2kB to 1.7kB. But based on Nonrival's screenshot it looks like he was running into the cookie size limit of 4Kb, perhaps due to different attributes of his Google account. So let's try to make it as small as possible and see if it fixes his problem.

Try to make auth cookie smaller

---

functions/src/on-update-contract.ts

This broken invalidation surely causes many bugs, but it seems one of the worst bugs is with the description editor, which doesn't correctly handle the case where the description changes after loading the page. As a result everyone on Discord is mad, because they will change a description and the change basically won't work until someone bets.
I don't want to deal with trying to fix the bug in that editor right now, so I am doing the simplest thing that I think will make people less mad.

Invalidate contract page props on description and question changes

---

functions/src/update-contract-metrics.ts

Redemptions shouldn't affect the probability, volume, or unique bettors, so they are useless to consider in these metrics.

Don't load redemption bets in `updateContractMetrics`

---

common/contract.ts
common/new-contract.ts
docs/docs/api.md
functions/src/update-contract-metrics.ts
twitch-bot/common/types/manifold-api-types.ts
twitch-bot/common/types/manifold-internal-types.ts
web/hooks/use-contracts.ts
web/lib/firebase/contracts.ts
web/pages/api/v0/_types.ts
web/pages/contract-search-firestore.tsx

I'm going to claim we don't need this for anything, and once I replace the "unique bettors in time interval" and "probability change over time" metric computations to be more efficient (both of which I plan to do), then we will no longer need to load as many bets in `updateContractMetrics`.

Remove `volume7Days` precomputed metric

---

web/lib/firebase/bets.ts
web/pages/embed/[username]/[contractSlug].tsx

This is necessary to support "embeds pointing to the main contract page", which load the contract page static props (only including a prefix of bets) and then render the embed view afterward. Otherwise, embeds with more than 2.5k bets will just show a wrong chart forever. You can see an example on the Donald Trump market shown at https://astralcodexten.substack.com/p/mantic-monday-twitter-chaos-edition.

Load additional bets on broken embeds after initial load

---

functions/src/follow-market.ts

Follows happen whenever bets happen, so they shouldn't do extra work.

Don't bother fetching follow docs before writing them

---

web/components/activity-log.tsx
web/components/bet/bets-list.tsx
web/hooks/use-bets.ts
web/hooks/use-user-bets.ts
web/lib/firebase/bets.ts
web/pages/[username]/[contractSlug].tsx
web/pages/api/v0/market/[id]/index.ts
web/pages/api/v0/user/[username]/bets/index.ts
web/pages/challenges/[username]/[contractSlug]/[challengeSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

Now more places can use the `BetFilter` query stuff to filter out (typically) redemptions and antes in the query (e.g. the API, the activity feed, the user profile.)

More flexible bet filter machinery, use it everywhere

---

functions/src/on-update-contract.ts
web/pages/[username]/[contractSlug].tsx

Sorry @jahooma but I just can't stand the way it is so I am changing it back.
If you want to change this back, note that my fix in #1232 was wrong because I forgot that contract descriptions are complicated, so we were revalidating too often before. So you will have to write a more complicated version of that fix.

Revalidate contract page periodically again

---

web/pages/_app.tsx

Inga introduced a globals.css file that imports Tailwind in #1197 but forgot to delete this import.

Don't include an extra copy of Tailwind in our app

---

common/util/share.ts

Fixes #1161, if that's regarded as a bug worth fixing! If not, feel free to ignore this.
Testing:
- Before: ![Screenshot from 2022-11-25 22-52-56](https://user-images.githubusercontent.com/1899701/204076516-021b35e6-10c4-486b-8ea2-11451f80a457.png)
- After: ![Screenshot from 2022-11-25 22-53-04](https://user-images.githubusercontent.com/1899701/204076535-f109eb60-bbfb-4bf9-83e4-81ec4d8fc594.png)
(If you'd like unit tests for this, I'd be happy to add them! But I'll need a pointer about where to put them.)

always include current username in share-market-URLs

---

web/components/editor/embed-modal.tsx
web/components/widgets/editor.tsx

https://linear.app/manifoldmarkets/issue/MAN-157/render-tiptap-as-html-for-read-only-comments-and-description
That wasn't too bad after all
I am worried about XSS - but I thiiink this doesn't open us to any new attack vectors since `generateHTML` shouldn't generate html for unsupported tags (like `<script>`)

Render rich text server side

---

common/calculate-metrics.ts
common/calculate.ts
functions/src/scripts/update-metrics.ts
functions/src/update-contract-metrics.ts

The goal of this field is to make it easy to compute "unique bettors between time T0 and T1." (I intend to remove the contract unique bettor fields entirely in a later PR, but adding this field is the first step.)
Now we don't need to load all the bets from the last month in `updateContractMetrics`; just the bets from the last day, for the purpose of computing daily volume.
Later I may transition to maintaining this field in the `onCreateBet` trigger so that it doesn't have a 15-minute lag time, but for now let's populate it in the same place that we populate the other contract metrics, since that's easy.

Introduce `contract-metrics` `lastBetTime`, optimize `updateContractMetrics`

---

common/user.ts
functions/src/create-user.ts
functions/src/update-user-metrics.ts
web/lib/firebase/users.ts
web/pages/leaderboards.tsx

Motivation: trying to eliminate complicated and expensive batch job work. Profit rank is almost guaranteed to change for ~every user ~every time we update, so it makes us update every user doc every 15 minutes for sure.
- We no longer need to precompute the profit rank in `updateUserMetrics`.
- The leaderboards page no longer re-downloads the static props for no obvious reason.
- We no longer censor our bot from the leaderboard. (Actually, we previously didn't bother to do any metrics updates on our bot, which is pretty bizarre. It just had a bunch of out of date info in there.) If someone really loves this I can put it back in. We will need to add a field in the database like `isEligibleForLeaderboard`. I think it's much better to have it on the leaderboard.

Remove precomputed user profit rank, clean up leaderboards code

---

web/components/editor/contract-mention.tsx
web/components/editor/mention.tsx

Temporary fix. We just render these as links instead of as react components

hotfix at mention, % mention ssr

---

functions/src/change-user-info.ts

This fixes a bug where people could enter invalid display names and propagate those invalid names across all the denormalized stuff. (It wasn't super obvious because we also sanitize this on the client.) It also fixes gratuitous inefficiency. Note that all this code is still incorrect -- it will race to update denormalized data in any case where you quickly update your info twice in succession. It's just a little less bad.

Somewhat improve `changeuserinfo`

---

web/pages/charity/index.tsx

When you put stuff in the static props of a page in the sidebar, it gets downloaded on every page load everywhere, so it really needs to not have a bunch of junk.

Remove txns from charity page static props

---

common/contract.ts
common/new-contract.ts
functions/src/create-market.ts
functions/src/create-notification.ts
twitch-bot/server/src/manifold-api.ts

Prevent contracts created through Twitch (either the dock or directly from chat) from sending market resolution emails.

Twitch no resolution emails

---

web/components/charts/contract/binary.tsx
web/components/charts/contract/index.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/contract/contract-leaderboard.tsx
web/components/contract/contract-overview.tsx
web/components/contract/contract-tabs.tsx
web/hooks/use-user-contract-metric.ts
web/lib/firebase/bets.ts
web/lib/firebase/contract-metrics.ts
web/pages/[username]/[contractSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

It looks like this halves the large graphs' (e.g. will donald trump tweet, will destiny get to 600k subs) data from ~4mb to ~1.5mb. We lose the avatar url on the graph tooltip but the probability that you see an avatar you know is probably ~1% anyways so this seems fine. This works great for embeds bc you don't likely know the avatars either.

Use points instead of bets on binary & pseudonumeric graphs (inlcuding embeds). Always include user in contract leaderboards

---

web/pages/worldcup.tsx

I've added two markets for each match, who will win and who will be man of the match (free response to guess the best player of the game).
I've posted the game chronologically and added dates which might be useful to add as subheaders on the site.

Add knockout stage markets to worldcup tournament page

---

functions/src/update-contract-metrics.ts
functions/src/update-group-metrics.ts
functions/src/update-user-metrics.ts

Ramping these up more slowly will give time for the write triggers and replication to spin up new Cloud Run instances to handle the writes.

Throttle writes in `update-*-metrics`

---

functions/package.json
functions/src/index.ts
functions/src/update-contract-metrics.ts
functions/src/update-group-metrics.ts
functions/src/update-loans.ts
functions/src/update-user-metrics.ts
functions/src/utils.ts
yarn.lock

The new `firebase-functions` SDK makes it easy to make scheduled v2 functions, so we don't need to do the weird thing where we have a v1 proxy function invoking a v2 function anymore.

Upgrade `firebase-functions` SDK, eliminate unnecessary proxy functions

---

functions/src/replication/transaction-log.ts
functions/src/utils.ts

Now it can handle arbitrary sized sets of failed writes without blowing up due to OOM or timeout.* Also `processPaginated` will be useful elsewhere.
*If there are really a lot, it could time out, but that's fine since it processed lots of them and it will get back to work in a minute processing more.

Make write replayer not fail if there are too many writes

---

web/components/notifications-icon.tsx
web/components/notifications/notification-helpers.tsx
web/hooks/use-notifications.ts
web/lib/firebase/notifications.ts
web/pages/notifications.tsx

We still download your unseen ones, which sucks, but I guess at least we don't download all your unseen ones too. Sigh.
Please don't write code that fetches hundreds of documents on every page load in order to show a little number in a bubble! I believe in you!

Don't download 300 notifications to display notifications icon

---

firestore.rules
web/hooks/use-user.ts
web/pages/recommended-markets.tsx

Result of my hackathon project. Shows recommends markets similar to those you've bet on and viewed (via their contract page), showing 100 markets by similar creators, similar groups, similar bettors' interests, but won't show you markets you've already bet on or viewed. Austin brought up the point that perhaps we shouldn't reshow you markets you've scrolled past too many times. Could be an interesting addition to add. Using this page we could start logging markets you've seen and not show them more than 2/3 times. 
It could go on the homepage and should probably have an infinite scroll.

Recommended markets page [WIP]

---

web/pages/[username]/[contractSlug].tsx
web/pages/embed/[username]/[contractSlug].tsx

Previously:
- The embed page would query the most recent 10k bets in `getStaticProps`.
- It would pass down to the client either: (for choice contracts) all the bets, or: (for other contracts) both the most recent 100 bets plus chart points for all bets.
- Regardless of what it got, the client would use `useBets` to make a subscription and extend its lists of bets and points to newer bets and points.
- The client would go on to render either a small embed card or a large embed chart. Notably, the embed page has no purpose for bets unless it's specifically rendering a choice contract chart.
Now:
- The embed page still queries all the bets.*
- It only passes down either (for choice contracts) all the bets, or (for other contracts) all the points.
- It doesn't call `useBets` -- I don't think …

Load only what we need on embed page

---

web/components/notifications/notification-types.tsx

got rid of market description when nested

fixed liked

---

supabase-replicator/package.json

It's convenient to have this so that I don't have to remember the Supabase project ID or anything.

Add `yarn regen-types` script for Supabase type generation

---

web/components/widgets/pagination.tsx
web/pages/notifications.tsx

This has been annoying me recently: when I go back in the app after exploring an older notifications page I don't go back a page, instead I go to where I was before I was on the notifications page. I'm curious if I'm the only one annoyed, though.

Track notifs page in query

---

functions/package.json
package.json
web/package.json
yarn.lock

Should have no user-visible changes, unless one of the transitive dependency upgrades has a bug and randomly breaks something.
Just a quick audit for unnecessary cruft. This change throws out about 100M of crap from `node_modules` on my box, so I guess it should probably stave off disaster for the build machine for a little bit.

Tidying up some dependencies

---

common/envs/dev.ts
common/envs/prod.ts
common/supabase/utils.ts
functions/src/utils.ts
supabase-replicator/src/index.ts
supabase-replicator/src/replicate-writes.ts
web/lib/supabase/db.ts
web/lib/supabase/users.ts

WIP. The backend seems solid, so working on getting some client code using Supabase out the door.
There's one annoying issue which is that `postgrest-js`'s [clever Typescript code](https://github.com/supabase/postgrest-js/blob/master/src/select-query-parser.ts#L146) isn't clever enough to know that JSON column access operators exist, so whenever we access our data blobs using a `select` Typescript barfs. I will probably send a patch upstream, but in the meantime until it's merged we might have to turn off the clever Typescript stuff.

Initial Supabase client scaffolding

---

supabase-replicator/supabase/seed.sql

This supports using `.explain()` on queries with `supabase-js`. https://supabase.com/blog/postgrest-v10#explain

Enable `explain` on Supabase queries via HTTP API

---

common/envs/constants.ts

can't have the og destiny user not be trustworthy (also needed more people to edit group tags for destiny markets)

added yaboi as trustworthy

---

functions/src/index.ts
functions/src/mark-all-notifications.ts
functions/src/serve.ts
web/lib/firebase/api.ts
web/lib/firebase/notifications.ts
web/pages/notifications.tsx

The previous version of this was very bad in the case that someone had a lot (e.g. thousands) of unread notifications, because it would load them all as a prereq to marking any of them as seen. This version is much more efficient (since on the server we can load the document refs without the data) and it still works once you trigger it even if you navigate away from the page, as opposed to "never getting to" the part where it actually marks them as seen.

Implement server-assisted "mark notifications as seen" functionality

---

web/components/numeric-resolution-panel.tsx

This fixes [bug #1083](https://discord.com/channels/915138780216823849/943628693958459462/1059514377532887090) by not disabling the "Resolve" button if the user has selected to cancel the market.

Web: Fix N/A resolution button for numeric markets

---

common/transaction-log.ts
functions/src/log-writes.ts
functions/src/scripts/supabase-import.ts
supabase-replicator/src/replicate-writes.ts
supabase-replicator/supabase/seed.sql

Problem: We have numerous documents in Firestore at paths like `/groups/{groupId}/groupMembers/{memberId}`, which have two properties:
1. Important information (the group ID) is encoded in the parent path segment of the document, which isn't necessarily present in the document contents.
2. The document ID is not unique in Firestore; rather, the (parent ID, document ID) pair is unique.
Solution: Supabase will now represent these in tables with a composite primary key, e.g. `(group_id, member_id)`. The importing and replication is all fixed up to do this.

Properly replicate collection groups of stuff into Supabase

---

common/envs/constants.ts

The goal of @Botmageddon is to try and scam the bots out of Manifold tokens.
The reason I need multiple accounts is to create the illusion of momentum.
These two accounts are my partners in crime.
In the meantime, I have exploited the unique trader bonus on the accounts which I know goes against the [Community Guidelines](https://help.manifold.markets/community-guidelines). I have donated all of the bonuses [here](https://manifold.markets/charity/ai-impacts). Feel free to remove the donations if you wish to.
So, in summary, please don't ban me and add these two bots to the list.

Add two more of my bots

---

web/components/portfolio/portfolio-value-section.tsx

resetting y axis when changing from profit to portfolio graph zoomed in

---

web/components/buttons/confirmation-button.tsx
web/components/buttons/warning-confirmation-button.tsx

This addresses two concerns:
1. Having the main action button be gray on gray while "cancel" is yellow is totally bizarre, e.g. it made gwillen think that it might be disabled. Now it's blue like our normal buttons. Still not a fan of the yellow but whatever.
2. It's important that you can't click the "submit" button twice and accidentally make your bet twice.

Fix the "warning, you are making a big bet" UI to be less error-prone

---

supabase-replicator/supabase/seed.sql

This will make it easier to be confident what is going on when you are e.g. replicating new tables.

Log document kind and write kind on replication failures

---

web/lib/supabase/referrals.ts

The GIN index on our JSONB column helps speed up `contains` queries (which end up producing SQL like `to_jsonb(data) @> '{"referredByUserId":"foo"}'`) but doesn't help speed up `eq` queries (which end up producing SQL like `to_jsonb(data)->>'referredByUserId' = 'foo'`.)
So as long as we have the data in this JSON column, we should prefer `contains`.

Adjust referrals query to use `contains` so it hits index

---

supabase-replicator/supabase/seed.sql

1. I didn't appreciate this until now, but it seems that if you are writing a small function that you are going to call a lot in SQL, it's good for it to be `language sql`, because then it's eligible for inlining. There's a great Stack Overflow answer explaining some differences between `language sql` and `language plpgsql` [here](https://stackoverflow.com/a/24771561).
2. Added an index on `user_events` by `user_id` and `name` to accelerate "have I viewed this market" query and because it just seems like an obviously useful index to have.
Together these changes bring the performance of the thing from about 80ms to about 30ms for my user.
I also fixed a bug, which is that if you asked for `get_recommended_contracts('myid', 10)` you wouldn't actually get 10, because it was first getting the …

Tweak recommendation SQL to be a little better

---

functions/src/scripts/supabase-import.ts
functions/src/utils.ts
supabase-replicator/supabase/seed.sql

There are ~10 million user events right now so it's good to import them efficiently. Also, don't import the old fake user events in `private-users`.

Fix up importing events related stuff

---

functions/src/create-market.ts

Reasons I think this is ridiculous:
1. It's mixing up valuable, accurate information that we can use for recommendations or UI (groups that informed humans assigned to markets) with trash-quality information, thereby ruining the signal of the accurate information.
2. People constantly complain about the poor quality of the suggestions on Discord and I have yet to hear that someone liked it.
3. The implementation makes it impossible to intentionally create a market with no group, which is a reasonable action to be able to do.
4. The implementation performs poorly (it downloads the whole groups DB to send the names to OpenAI, which is a few dozen megabytes, and then it waits on the response from OpenAI, all serially), degrading the user experience of an operation that's critical to the …

Stop producing AI-generated market groups

---

supabase-grafana-agent/Dockerfile
supabase-grafana-agent/README.md
supabase-grafana-agent/agent.yaml
supabase-grafana-agent/fly.toml
supabase-grafana-agent/run.sh

Relatively self-explanatory, we have a fly.io app now that forwards the Prometheus metrics from Supabase to Grafana Cloud so we can look at them on a dashboard like this:
Q: What is Prometheus?
A: [Prometheus](https://prometheus.io/) is an very standard OSS tool that scrapes metrics from different sources on a box and then provides them in a standardized format for external tools to consume. Our Supabase instance [exposes](https://supabase.com/docs/guides/platform/metrics) a Prometheus-compatible metrics endpoint.
Q: What data does Prometheus export?
A: It exports a huge shitload of data about the OS on our Supabase instance and about Postgres stats.
Q: What is Grafana?
A: [Grafana](https://grafana.com/) is a very standard OSS tool that ingests time series data and creates a nice webpage …

Check in config for fly.io Grafana agent process

---

web/components/search/search-context.tsx

This was broken on Firefox and Edge because it was continuing to trigger the built-in browser Ctrl-K functionality.
(It might piss off people who use those browsers that we are overriding their stuff, but that's what we signed up for when we decided Ctrl-K should do special stuff on our website.)

`preventDefault` on Ctrl-K shortcut

---

common/events.ts
common/tracking.ts
web/components/contract/contract-mention.tsx
web/components/daily-stats.tsx
web/lib/supabase/contract-metrics.ts
web/lib/supabase/user-events.ts
web/pages/home/index.tsx

- Highlights your daily profit once a day until you click it
- sidenote: this doesn't add a new prop onto the `user` object, but instead checks your relevant events today via supabase to see if you've done it yet!
- Brings up a modal that you can order by % contract prob change or profit, defaulting to ordered by profit.
- Previously, the daily profit button got 100 contract metrics and 100 contract metrics whenever it was rendered, now it just uses the user's cached daily profit.
- The modal only gets the contracts & metrics from supabase if it's opened

Get daily profits in modal, highlight when unseen today

---

web/components/contract-search.tsx
web/components/profile/user-contracts-list.tsx
web/pages/group/[...slugs]/index.tsx
web/pages/search.tsx

Adds a sort "relevance" which is the same as not having a sort (pure algolia search, trending if empty)
Aside from that, if user sets a sort then algolia will search with that sort.
The previous UI where the filters disappear when typing was very magic, but I think instead we should have omni be very magic while market search be powerful

Market search and filter/sort at the same time

---

supabase-replicator/supabase/seed.sql

The most important change here is the introduction of the index by user ID and created time -- without this index the user bets API was totally broken.

Change contract_bets indexes to be more appropriate

---

common/group.ts
common/supabase/utils.ts
web/components/buttons/referrals-button.tsx
web/components/filter-select-users.tsx
web/components/groups/edit-group-button.tsx
web/components/portfolio/portfolio-value-graph.tsx
web/components/portfolio/portfolio-value-section.tsx
web/components/search/search.tsx
web/hooks/use-group.ts
web/hooks/use-portfolio-history.ts
web/hooks/use-referrals.ts
web/lib/firebase/groups.ts
web/lib/supabase/bets.ts
web/lib/supabase/contract-metrics.ts
web/lib/supabase/contracts.ts
web/lib/supabase/groups.ts
web/lib/supabase/portfolio-history.ts
web/lib/supabase/reactions.ts
web/lib/supabase/referrals.ts
web/lib/supabase/user-events.ts
web/lib/supabase/users.ts

Introducing two new helpers:
- `selectFrom(db, tableName, ...fields)`, which selects the fields in `fields` from the `data` JSON blob in `tableName`, and produces a query returning `Pick<TData, TKeys>` where `TData` is the type of the blob (e.g. `User`, `Contract`) and `TKeys` is the union of the fields.
- `selectJson(db, tableName)`, which just selects the whole `data` blob and produces a query returning `{ data: TData }` where `TData` is the type of the blob.
These should cut down a lot on the type wrangling associated with querying the JSON blob.
The main limitation is that these helpers don't provide an interface to also select other stuff, like computed fields, or joined tables, or whatever. (They could, they just don't.) So they will only help with queries that are just selecting a …

Implement fancy Typescript stuff for Supabase queries

---

web/pages/api/og/market.tsx

Not fetching the fonts every time should make it substantially faster (assuming it reuses the same process for a lot of the function invocations.) And I guess doing it in parallel should make it faster even if it doesn't reuse the same process.

Improve OG image generation

---

supabase-replicator/supabase/seed.sql

1. These functions weren't using any index -- the GIN index on the top-level JSON data doesn't "reach in" and index the contents of arrays and objects inside of it. You have to create an index on individual sub-objects that you want to query by. So they were really slow.
2. `immutable` on `get_time` was just wrong and would result in the wrong time being used in some cases. Please see the documentation [here](https://www.postgresql.org/docs/current/xfunc-volatility.html) to understand these annotations.
3. Cleaned up some unnecessary cruft. (The part of the cleanup where I rearranged the `jsonb_array_elements` stuff was necessary to even use the index.)

Fix contract group search SQL

---

common/envs/dev.ts
common/envs/prod.ts
common/supabase/utils.ts
functions/package.json
functions/src/scripts/supabase-import.ts
functions/src/supabase/init.ts
functions/src/supabase/utils.ts
supabase-replicator/src/index.ts
web/lib/supabase/db.ts
yarn.lock

This library lets us connect to Postgres directly, so that we can write arbitrary SQL on the backend and run it more efficiently than we can do stuff when only using the HTTP API.

Introduce `pg-promise` library, use for imports

---

functions/src/scripts/fix-busted-ids.ts
functions/src/sell-bet.ts

It makes no sense and makes our API hard to use, since the API exposes the ID in the data blob, not the Firestore document ID.

Fix duplicate bet IDs

---

web/hooks/use-native-messages.ts

I noticed console logging on manifold.markets and thought that might not be intended.

Removed logging "Received native event"

---

web/components/buttons/follow-button.tsx
web/components/charts/contract/binary.tsx
web/components/charts/contract/pseudo-numeric.tsx
web/components/charts/generic-charts.tsx
web/components/charts/time-range-picker.tsx
web/components/choices-toggle-group.tsx
web/components/contract/contract-card.tsx
web/components/contract/contract-details.tsx
web/components/contract/contract-overview.tsx
web/components/outcome-label.tsx
web/components/portfolio/portfolio-value-section.tsx
web/hooks/use-portfolio-history.ts
web/lib/util/time.ts
web/pages/embed/[username]/[contractSlug].tsx

Resolves MAN-371
- just binary and pseudonumeric for now
- ended up not adding 1H as most markets don't have hourly updates
- I'm not happy with the look of having the entire thing be disabled with just "ALL" selectable when you create it
also includes some a few style changes / refactors to the market header to make it look nicer
- thinner close date, market tags
- add group cta more prominent when there are no groups
these don't really belong in this PR but at this point I can't be bothered to untangle it out

Add 1d1w1m switcher to market page

---

functions/src/log-writes.ts
supabase-replicator/deploy.sh
supabase-replicator/package.json
supabase-replicator/src/index.ts
supabase-replicator/src/replicate-writes.ts
supabase-replicator/src/utils.ts

Aiming to work towards solving any problems causing spotty replication, and make the replication more stable under load.
1. Add logging to the Firestore triggers and replicator so that we can track individual event and document write IDs. This way if we ever see that a write didn't get all the way to Supabase, we can go back and see where it got lost.
2. Talk directly to Postgres in the replicator. This should be more efficient and removes the Cloudflare HTTP proxying as a potential point of failure.

Replication robustness

---

common/contract-details.ts
common/pseudo-numeric.ts
web/components/bet/bet-panel.tsx
web/components/bet/limit-bets.tsx
web/components/bet/quick-bet.tsx
web/components/bet/sell-panel.tsx
web/components/buttons/duplicate-contract-button.tsx
web/components/contract/contract-card.tsx
web/components/contract/contracts-list-entry.tsx
web/components/contract/contracts-list.tsx
web/components/feed/feed-bets.tsx

Just fixing up some small bugs:
- The list now shows something useful instead of empty space on non-binary contracts.
- The hover highlight now doesn't have gaps between the items.
- There's a couple pixels of left-right padding, which makes the highlight look better.
- The user avatar link is un-broken.
- The vertical alignment is fixed up.

Search list tweaks

---

web/components/buttons/report-button.tsx
web/components/contract/contract-tabs.tsx
web/components/contract/like-button.tsx
web/components/feed/feed-answer-comment-group.tsx
web/components/feed/feed-comments.tsx
web/components/widgets/editor.tsx
web/components/widgets/loading-indicator.tsx
web/components/widgets/user-link.tsx

Comment rendering is a large culprit making the "search and look at contracts and go back to the search" user flow feel slow.
The big fix here is that previously we were loading all the lists of likes for all the comments in tiny Firestore subscriptions when we rendered each like button, but now we only load them when you hover the button to see the tooltip.

Clean up stuff and performance issues related to comment list

---

web/components/contract/contracts-list.tsx

I think the idea of having a quick bet tool in this list is perfectly reasonable, but unfortunately:
1. The quick bet widget is very expensive for performance because every one of them subscribes to a bunch of contract-specific stuff from Firestore. So its presence is hurting the browsing workflow.
2. When the widget is presented in a popup over to the right of the item that disappears if you mouse out of the list entry, it's going to be ridiculous to expect anyone to mouse over and use it.
So until point number 2 is resolved I don't think it makes sense to pay the price in point number 1.
My suggestion would be to add quick bet arrows inline with the list entry.

Disable quick bet on contract list popup

---

web/components/auth-context.tsx
web/components/contract-search.tsx
web/components/daily-profit.tsx
web/components/notification-settings.tsx
web/components/widgets/collapsible-content.tsx
web/components/widgets/editor.tsx
web/hooks/use-follows.ts
web/hooks/use-group.ts
web/hooks/use-is-mobile.ts
web/hooks/use-notifications.ts
web/hooks/use-persistent-state.ts
web/hooks/use-save-binary-shares.ts
web/hooks/use-saved-contract-metrics.ts
web/hooks/use-user.ts
web/lib/firebase/users.ts
web/lib/native/is-native.ts
web/lib/util/local.ts

Previously, every time you called `safeLocalStorage` we would do our "test" to see if an exception flew out, so it was frequently doing that hundreds or thousands of times in a page load. There's no point in doing that because for a given interpreter session either `localStorage` is gonna be there or it isn't.

Make local storage wrapper not inefficient

---

firebase.json

It's comfy to upgrade this because it means that the runtime environment is closer to what we are running on our box. Also, Node 18 has some good convenience stuff like built-in `fetch`.
I'm going to bump the Vercel Node to 18 too.

Bump function runtime from Node 16 to Node 18

---

backend/functions/package.json
backend/functions/src/api/claim-destiny-sub.ts
backend/replicator/package.json
backend/scripts/place-many-bets.ts
backend/shared/package.json
backend/shared/src/dream-utils.ts
backend/shared/src/helpers/generate-and-update-avatar-urls.ts
backend/shared/src/utils.ts
web/lib/api/proxy.ts
web/package.json
yarn.lock

Node 18 [includes `fetch`](https://nodejs.org/de/blog/announcements/v18-release-announce/#fetch-experimental) in the standard library, so now that we are on Node 18 we don't need to use `node-fetch` on Vercel or Cloud Functions anymore.

No need for node-fetch anymore

---

web/lib/api/proxy.ts

Since #1511 it seems like this is causing some trouble with our proxied API routes where `fetch` thinks that our body length doesn't match the `Content-Length` header. It's not clear to me why that is the case, but it seems like just not proxying that header (and thereby sending a correct one for sure via the `fetch` internals) is easy and safe, so I am just going to do that and fix the thing.

Don't proxy `Content-Length` header to backend

---

backend/supabase/seed.sql

`pg_vector` provides a `vector` data type that provides efficient storage over large multidimensional vectors and fast indexes for looking up vectors ordered by e.g. cosine similarity to a target vector. You can see [this Supabase blog post](https://supabase.com/blog/openai-embeddings-postgres-vector).
`pg_repack` provides a way to do the equivalent of `cluster` and `vacuum full` (i.e. keep tables in an efficient physical order) without locking, so we can do it regularly. This should greatly improve the performance of common operations on large tables like `contract_bets` and `user_seen_events`. See the documentation [here](https://github.com/reorg/pg_repack).

Add `pg_vector` and `pg_repack` extensions

---

web/lib/api/proxy.ts

This fixes a bug I made in #1511 because I didn't understand that in some cases next.js will hand us a `NextApiRequest` that is an `ReadableStream` with the request contents in and of itself, rather than having a `body` property.
The `duplex: 'half'` thing is a small change required by the built-in fetch vs. our previous fetch implementation in cases that the `body` of the fetch request is a `ReadableStream`. See https://github.com/nodejs/node/issues/46221 and linked issues.

Really fix proxy code to work with built-in fetch

---

web/pages/index.tsx

The landing page loading used to feel really janky. This tries to fix it up a little by having the footer not appear until the content is loaded (so then it doesn't get yeeted to the bottom when the content loads) and by having the width stay consistent throughout loading.

Fix bad feeling loading stuff on landing page

---

backend/functions/package.json
backend/replicator/package.json
backend/shared/package.json
common/package.json
common/tsconfig.json
package.json

I guess someone wrote some code doing this even though it doesn't build correctly, so probably I should just make it build correctly.

Make absolute import of `common` work in `common`

---

web/components/auth-context.tsx
web/components/comments/comment-input.tsx
web/components/new-contract-panel.tsx
web/hooks/use-user-bets.ts
web/lib/util/local.ts

Now this covers the case where accessing the property throws (I think this happens when a security policy restricts local storage use in Chromium) and it covers the case where `set` and `remove` don't work (I don't know of a case where this happens, but it makes sense that it could happen for "not allowing trackers to set stuff" reasons.)

Make `localStorage` access safer

---

web/components/landing-page-panel.tsx
web/lib/icons/squiggle_horizontal.tsx
web/lib/icons/squiggle_horizontal_flipped.tsx
web/lib/icons/squiggle_vertical.tsx
web/lib/icons/squiggle_vertical_flipped.tsx
web/lib/icons/start_quote copy.tsx
web/lib/icons/start_quote.tsx

This was producing a bunch of console warnings since `width|height='inherit'` is not a thing.

Tidy up landing page markup

---

web/next.config.js

I noticed some stuff here that could be tidied up while I was poking around trying out Turbopack.
The font thing comes from https://github.com/manifoldmarkets/manifold/pull/668. I read in one of the Next changelogs since then that the issue was fixed, so I think we're good to go back to the default behavior.

Clean up a couple things in `next.config.js`

---

backend/functions/src/scheduled/update-recommended.ts
backend/scripts/recommend.ts
common/src/recommendation.ts

One column per contract instead of splitting off a second set of columns for each swiped contract (and more columns for groups).
Also, followed groups will shape your results better: we count some markets within the group as bet on by you to juice things. Should be especially helpful for new users.

Simplify recommendation algorithm

---

backend/functions/src/api/create-user.ts
web/components/auth-context.tsx
web/pages/admin/test-user.tsx

This creates a new endpoint at admin/test-user where admins can create as many test users as they'd like. All you have to do is set the proper value in local storage, then sign out, revisit this page (it will automatically generate a new email address variant for you), type a password and hit submit. You'll be redirected to the home page after `createuser` finishes.
If you'd like to log in to the gmail account the information is in the bitwarden under `manifoldtestnewuser@gmail.com`

Create as many new test users via email as we want

---

common/src/supabase/utils.ts

I accidentally broke this in #1509, breaking swipe stuff that relies on these being up to date with the markets you see.

Fix up replication of seen markets to work right

---

backend/replicator/Dockerfile
backend/replicator/src/index.ts
backend/replicator/src/replicate-writes.ts
backend/supabase/seed.sql

Now the replicator can use [`pg_repack`](https://reorg.github.io/pg_repack/) to repack (cluster and vacuum full) all the DB tables without locking on demand. I will probably wire this up to run nightly. This should be a great boon towards speeding up queries by predictable criteria on our larger tables.

Replicator can do repacking of DB tables on demand

---

web/components/contract/related-contracts-widget.tsx
web/pages/[username]/[contractSlug].tsx

This was busted before, it would load all the related contract stuff in both individual widgets (which is not a cheap amount of stuff to load.)

Fix loading of related markets on contract page to not load twice

---

backend/functions/src/scheduled/update-group-metrics.ts

Self-explanatory. This was loading 500k contract metrics documents (plus other stuff) so it's a nice chunk of reads to cut. Obviously it's also faster and simpler.

Compute group leaderboards in SQL

---

backend/functions/src/scheduled/update-stats.ts
backend/supabase/seed.sql

This is mainly for cost saving purposes.
I'm not sure what the future of this code. Plausibly, it should just have SQL queries that squirt out the final numbers. But possibly people will appreciate the flexibility of loading in the datasets and poking at them in Javascript. Of course, there is some scaling limit at which that will cease to be reasonable.
So right now I am opting to just change very little (it loads the same information into the same data structures and does the same processing, it just loads it from Supabase instead of Firestore.)

Load most of the data in `updatestats` via Supabase

---

backend/functions/src/api/create-group.ts
backend/functions/src/triggers/on-update-group.ts
backend/scripts/convert-tag-to-group.ts
common/src/group.ts
twitch-bot/common/types/manifold-internal-types.ts

This is unnecessary and was running for every group when group leaderboards were recomputed.

Remove group `mostRecentActivityTime`

---

backend/functions/src/scheduled/update-group-metrics.ts

Now the rows will be numbered 1 per row, even if there are ties. (Tie breaking is I guess random, which is fine.)

Correctly produce exactly the top 50 in `updategroupmetrics`

---

backend/functions/src/index.ts
backend/functions/src/scheduled/score-contracts.ts
backend/functions/src/scheduled/update-contract-metrics.ts
backend/functions/src/scheduled/update-group-metrics.ts
backend/functions/src/scheduled/update-recommended.ts
backend/functions/src/scheduled/update-stats.ts
backend/functions/src/scheduled/update-user-metrics.ts
backend/scripts/update-metrics.ts

- Now that they don't take ten minutes, there's no need for them to be v2 functions, so we don't need the weird wrapper function stuff.
- These functions don't need nearly as much memory now, probably because of the Supabase stuff (Firestore document fetches return extremely inflated blobs of crap.)

Clean up some stuff with metrics functions

---

web/components/notifications/notification-dropdown.tsx

This is fetching a huge amount of data for large contracts.
Since they got the notification, we can reasonably assume as a default that they are following the market.

Don't fetch contract follows in notification dropdown

---

backend/replicator/deploy.sh

Empirically, we didn't need what we were using, so we can use less. (This is an always-on service so it really costs money.)

Slim down replicator resources

---

backend/functions/src/scheduled/backup-db.ts
backend/functions/src/scheduled/update-loans.ts
backend/functions/src/scheduled/update-user-metrics.ts
backend/replicator/package.json
backend/scripts/calculate-mana-supply.ts
backend/scripts/clean-local-firestore-db.ts
backend/supabase/seed.sql
common/src/supabase/portfolio-metrics.ts
common/src/supabase/schema.ts
common/src/supabase/utils.ts

The goal is to make the `user_portfolio_history` table have normal columns rather than a JSON blob and to migrate it completely away from Firestore. You can view this as a test run for future tables.
The plan is like this:
1. Alter the table to make the JSON data blob nullable and add new nullable real columns. Create any indexes we want with the native columns.
2. Create a `before update or insert` trigger on the table that, if it sees a JSON blob, populates the real columns with the contents of the blob. If it doesn't see a JSON blob, it does nothing.
3. **Now: all new rows will have their native columns populated.**
4. Run `update foo_table set id = id where some_real_column is null`, running the trigger a lot.
5. **Now: all rows will always have their native columns populated.**
6. …

Change portfolio history to be native Supabase table

---

common/src/supabase/portfolio-metrics.ts
common/src/supabase/utils.ts

Irritatingly, when we get this back from Postgres using the supabase-js library, it comes out not as an ISO8601 string, but as an ISO8601-but-no-timezone string, and then Javascript assumes it's in local time when we do `Date.parse`. So we have to make it look like an ISO8601 string to make `Date.parse` know that it's UTC.
I will be looking into how to address this more reasonably.

Fix timezone handling on user_portfolio_history.ts column

---

backend/functions/src/scheduled/update-user-metrics.ts
common/src/calculate-metrics.ts

Pretty self-explanatory, we can just make this query more efficient by doing the profit calc in SQL.
I thought I could speed this up by putting together the different historical profit queries, but I didn't see much benefit.

Make `updateUserMetrics` pull down less data for profit calcs

---

backend/supabase/functions.sql
backend/supabase/seed.sql

I like doing this because 1) this was responsible for a decent chunk of our total load 2) it's really nice to have the stuff on the home page load snappily.
What is going on here is bad statistics on JSON columns biting us again. Basically, as it was, the planner was deciding:
- OK, so they want the top N scoring contracts that satisfy this big complicated criteria (can't be closing soon, binary, etc.)
- That looks like a big complicated criteria. I bet most of the contracts will not satisfy it. If I start going down the list of scores looking up contracts by ID, I will probably end up looking up a shitload of contracts before I have N of them that satisfy the criteria.
- So it would be faster to just scan the whole contracts table, figure out which ones satisfy the criteria, and then go …

Improve efficiency of `get_recommended_contracts`

---

common/src/native-message.ts
native/App.tsx
native/android/app/build.gradle
native/android/app/src/main/AndroidManifest.xml
native/app.json
native/components/auth-page.tsx
native/ios/Manifold/Info.plist
native/ios/Podfile.lock
native/lib/auth.ts
native/package.json
native/yarn.lock
web/components/native-message-listener.tsx
web/hooks/use-native-messages.ts
web/pages/_app.tsx

- Sends web client logs to native for easier debugging
- Stores firebase users in native local storage and queries them on app load to pass them to the client. This seems to result in faster user re-sign-in time on the client. Perhaps an even better version would be to pass the user as a cookie to the server, but the react native webview cookie stuff is finicky and not easy to get working. Will try this PR first and if sign in is still laggy I'll add the user via cookie.

Faster native sign in

---

backend/supabase/seed.sql

I think it's good to keep this slimmed down. I believe that everything in this publication is getting streamed to our Supabase Realtime server, which adds load to our Supabase, which we are basically paying for. So we shouldn't stream stuff we don't need (i.e. we should only stream stuff we are actually subscribing to on the client somewhere.)

Only stuff we actually need in `supabase_realtime` publication

---

backend/scripts/fix-popularity-scores.ts

It bothers me that I can't say how these got broken, but I will fix them and then look later to see if they are broken again. This currently affects 243 contracts on prod.

Fix stringified popularity scores

---

docs/docs/api.md

The api code uses the url parameter "order", not "sort", so this documentation did not match the functionality. Given that the rest of the api docs uses "order", "order" is probably the preferred choice here.

Fix positions endpoint docs: sort -> order

---

.prettierrc
.vscode/settings.json
backend/supabase/bets/rls.sql
backend/supabase/bets/view.sql
backend/supabase/contracts/create-question-fts-col.sql
backend/supabase/contracts/functions.sql
backend/supabase/contracts/indexes.sql
backend/supabase/contracts/rls.sql
backend/supabase/functions.sql
backend/supabase/groups/functions.sql
backend/supabase/groups/rls.sql
backend/supabase/posts/rls.sql
backend/supabase/seed.sql
backend/supabase/views.sql
web/package.json
yarn.lock

I couldn't find a nice postgres formatter that didn't do nonsense like always putting `select` on its own line
There's https://github.com/nene/prettier-plugin-sql-cst ... but it doesn't work for postgres syntax 😔
So I just went the path of least resistance and added the most used prettier sql plugin. (Which kinda doesn't make sense to put in `web/` but oh well).
I actually liked the most recent formatter that @ingawei was using more, but I don't feel like making everyone get the sqltools vscode extension

Add .sql to prettier

---

web/components/portfolio/portfolio-value-section.tsx

Switching the location of these buttons so that:
- Profit and Portfolio Value are adjacent, since they are correlated
- Balance is adjacent to the "Get M$" button

Switch location of balance graph and portfolio value graph

---

common/src/supabase/contract-metrics.ts
web/components/contract/user-positions-table.tsx
web/lib/contracts.ts
web/lib/firebase/contract-metrics.ts

Supabase was struggling slightly to keep up with this on the whales vs. minnows market. This should get way better when the user contract metrics migration is done, but for now, just offload this to Firestore.

Get contract metrics position counts from Firestore for now

---

backend/supabase/seed.sql
common/src/supabase/schema.ts
web/lib/firebase/utils.ts
web/lib/supabase/ads.ts
web/lib/supabase/user-events.ts

WIP. Stuff I am doing:
(I will do a bit more in a later PR.)

Clean up data and schema of user_events table

---

backend/api/src/supabase-search-contract.ts
backend/supabase/functions.sql
backend/supabase/seed.sql

- improves fuzzy search in omni search by giving more prefix matches including stop words like 'will', 'i', 'he', 'which', etc. This does make going back and forth from fuzzy to full text a bit jarring though, as fuzzy seems more accurate rather than general. Will have to see what users say.
- group and creator normal searches are now more like the above prefix matching searches as they typically have less content so the general 'full text search' isn't as necessary/useful.
- the first commit in this PR actually merged a user's recent markets (bets,likes) into the omni search results but then I realized that there's no easy way to rank results retrieved via different types of searches (e.g. full text vs prefix matches). So I erased that work so that I could add it to a separate section of …

Search tweaks

---

web/components/groups/add-member-modal.tsx
web/hooks/use-group-supabase.ts
web/hooks/use-supabase.ts

Pretty self-explanatory, this provides `useSupabasePolling(q)` which re-runs the query given repeatedly and returns the results, and optionally takes deps that restart the polling (e.g. if the query is based on a user ID and they just logged in.)
I updated a couple places where we were using realtime for groups and just re-fetching everything every time to use this instead, as a proof of concept.

Implement basic Supabase polling stuff

---

backend/api/src/sell-shares.ts

Currently if a user tries to sell shares they down own on a CPPM-1 market using an API, they will get the following result:
```
POST https://manifold.markets/api/v0/market/[marketId]/sell body='{"outcome": "NO", "shares": 1}'
--> 400 {"message": "You can only sell up to undefined shares."}
```
This Pull Request changes this error message to:
```
POST https://manifold.markets/api/v0/market/[marketId]/sell body='{"outcome": "NO", "shares": 1}'
--> 400 {"message": "You don't have any [outcome] shares to sell."}
```

If the user is trying to sell shares they don't own return an error 400 You don't have any shares to sell

---

backend/api/src/place-bet.ts
backend/api/src/sell-shares.ts
docs/docs/api.md

Currently an API call `POST /v0/market/[marketId]/sell` returns a `{"status": "success"}`, while a call `POST /v0/bet` returns a full `Bet` object.
This Pull Request changes the return type of the `sell` handler to a also be a full `Bet` object, with an additional `"status": "success"` field for backwards compatibility.
It also updates the API documentation `/docs/docs/api.md` to reflect this change.

Return a full Bet from /api/v0/market/marketId/sell, and not just status success

---

backend/discord-bot/src/commands/about.ts
backend/discord-bot/src/commands/index.ts
backend/discord-bot/src/helpers.ts
backend/discord-bot/src/leaderboard.ts

Zenbu, (ACX mod) requested a few features:
- adds /about command
- allows users to confine all bot-related activity to the thread the market was linked/created/searched for in

Acx discord

---

common/src/leagues.ts
common/src/supabase/realtime.ts
common/src/supabase/utils.ts
web/hooks/use-bets-supabase.ts
web/hooks/use-comments-supabase.ts
web/hooks/use-contract-supabase.ts
web/hooks/use-group-supabase.ts
web/hooks/use-post-supabase.ts
web/lib/supabase/db.ts
web/lib/supabase/realtime/use-live-stream.ts
web/lib/supabase/realtime/use-realtime.ts
web/lib/supabase/realtime/use-subscription.ts

This introduces two hooks:
1. `useLiveStream` opens and manages a channel and returns a live-updated stream of inserts on the chosen table. Useful for live feed kind of stuff and maybe the contract page bets.
2. `useSubscription` opens and manages a channel and returns a live-updated snapshot of the chosen table subset by merging a fetched snapshot with changes that come in, like subscribing to a Firestore query. Useful for most of the random stuff we want to use subscriptions for.
Some relevant facts:
1. When you call `db.removeChannel`, the websocket will be disconnected iff it has no more channels. So if all active channels are configured (as in this PR) to remove themselves when the tab is hidden, that will suffice to disconnect the websocket and not count against our connection cap. …

Write code for basic Supabase realtime functionality

---

backend/scripts/supabase-import.ts
backend/supabase/seed.sql
common/src/supabase/utils.ts

This is urgent because old `user_seen_markets` writes which are conflicting with the broken primary key stuff are currently wedging replication.
- Added autogenerated ID primary column -- the existing primary key didn't make sense for it to be unique.
- Dropped the GIN index. This table is relatively large and GIN indexes are beefy. We have no use for it.
- Dropped `fs_updated_time`.
- Turned off replication on `user_seen_markets` since we are not writing to Firestore anymore.

Clean up some stuff on the `user_seen_markets` table

---

backend/supabase/functions.sql
common/src/supabase/schema.ts
web/hooks/use-users.ts
web/lib/firebase/contracts.ts
web/lib/supabase/users.ts
web/pages/[username]/index.tsx

Now this is much more efficient, which is nice, but really this is important because this was using the contract `uniqueBettorIds`, which we are preparing to throw out. CC @IanPhilips

Query "similar users" in following dialog via Supabase

---

web/components/bet/bet-button.tsx
web/components/bet/bet-dialog.tsx
web/components/bet/bet-panel.tsx

Now we don't look up all the limit order bets and user balances for them in your feed when you hit the homepage; we will only query them if you click "bet yes" or "bet no" and it pops up the bet preview dialog.

Don't query limit order bets until you open the `BetDialog`

---

web/components/charts/helpers.tsx
web/components/sized-container.tsx

In some cases the `SizedContainer` would be of size zero during initial page render, and rendering zero-sized charts was A) a waste of time B) causing warnings to fly out. So let's not do that.

Fix issues with rendering zero-sized charts

---

backend/supabase/seed.sql
common/src/supabase/utils.ts

This was left over from when I was doing some work testing replication reliability. There's no point to it any more.

Clean up Supabase `test` table

---

backend/functions/src/scheduled/update-contract-metrics.ts
backend/supabase/functions.sql
backend/supabase/seed.sql

- Previously, this would get all the current probabilities for all contracts redundantly in each "historical snapshot" query for each time period, which was redundant.
- Now there is a covering index that has the probabilities in it, so the historical snapshot queries can do an index-only scan.
CC @IanPhilips since you were interested in this.

Improve efficiency of `updateContractMetrics`

---

common/src/envs/constants.ts

Removing bot tag from firstuserhere as I am no longer using automated trading from the API

Removing bot tag from firstuserhere

---

common/src/envs/constants.ts

I'm going to do automated trades from the "burkebot" account now, and use my existing account just for web/UI trades.
I had a "check" account before I got labeled a bot and would be great to have that back.

common/src/envs: add different bot user for Kevin

---

common/src/api-market-types.ts

I couldn't find any way to get the groups of a market in the API

Add groupSlugs to FullMarket

---

common/src/envs/constants.ts

To be used as jskf's bot account.
https://manifold.markets/arrbit/will-this-account-be-tagged-as-a-bo

Add bot tag to @arrbit

---

backend/api/src/send-mana.ts

Fix for https://manifold.markets/derikk?tab=managrams, where managrams with multiple destinations can leave the user with negative mana balance:

Fix mana-printing bug

---

backend/functions/README.md

Hi folks,
The path to secret keys in functions' documentation is incorrect (the file is absent).
I'm trying to fix that.

Fix the path to the list of secret keys in the functions' documentation

---

backend/functions/src/scheduled/update-stats.ts

This should allow for more timely updates to the stats page after they are written to Postgres.

Revalidate props on stats page after DB update

---

backend/scripts/add-reactivated-to-league.ts
backend/shared/src/generate-leagues.ts
backend/supabase/functions.sql
backend/supabase/seed.sql
backend/supabase/users/create.sql
backend/supabase/users/indexes.sql
backend/supabase/users/rls.sql
backend/supabase/users/triggers.sql
backend/supabase/views.sql
common/src/supabase/schema.ts

- also reorganizes user sql stuff from seed to supabase/users
```sql
alter table users
add column name text;
create
or replace function users_populate_cols () returns trigger language plpgsql as $$ begin
if new.data is not null then 
new.name := (new.data)->>'name';
new.username := (new.data)->>'username';
end if;
return new;
end $$;
update users
set fs_updated_time = fs_updated_time;
alter table users
alter column name set not null,
alter column username set not null;
create index if not exists users_name_idx on users (name);
create index if not exists users_username_idx on users (username);
drop index users_name_gin;
drop index users_username_gin;
drop index user_profit_cached_all_time_idx;
drop index users_instance_id_email_idx;
drop index users_instance_id_idx;
-- drop index …
```

Add name column to user

---

web/components/contract/feed-contract-card.tsx
web/components/feed/feed-contract-card-description.tsx
web/pages/[username]/[contractSlug].tsx

Just an idea I think we could try out, basically if a description has images/embed (visually stimulating content), we add the description to the feed card and make it really big so that it can read more like a post:
examples:

expand description if have images/embed

---

common/src/api-market-types.ts

Partial fix for https://discord.com/channels/915138780216823849/1158506775784460408.

Include `slug` field in all API market responses

---

docs/docs/api.md
web/pages/api/v0/managrams.ts

Most of the time I will only be interested in new managrams, so would be nice to be able to query that directly.
(Sorry for commit spam. Don't see an option to squash the commits in the github interface.)

Add `after` filter to `GET /managrams`

---

backend/functions/src/scheduled/update-stats.ts

I noticed the d1 stat on https://manifold.markets/stats makes no sense in the context of recent traffic. It dips on the 8th when the NYT article was released, and then spikes back up the day after. Clearly we expect it to be normal-ish on the 8th and dip on the 9th.
The problem seems to simply be using the wrong denominator. We want retained DAUs (number active yesterday who were also active today) as a fraction of yesterday's DAUs, not today's.
I haven't tested this typescript code, I wouldn't know how, but I have been doing the equivalent in Python and the D1 stat makes a lot more sense with the right denominator (final day here is Oct 9th):

Fix incorrect denominator on d1 stat

---

common/src/manalink.ts

Since getting the bot tag requires admin intervention I think the waiting period is not necessary here. If someone (me) wants to build something cool using managrams, they should not be blocked by this!
Also removed the Manifest ticket exception, which doesn't do anything anymore.

Allow bot accounts to use managrams immediately

---

backend/scripts/supabase-import.ts
backend/supabase/seed.sql
common/src/supabase/schema.ts
common/src/supabase/utils.ts

Self-explanatory. Uses RLS for reads. I plan to get reads migrated over and then probably instead of using RLS for writes, I will make API endpoints for writing to `private_users` from the client.

Replicate `privateUsers` -> `private_users` table

---

backend/supabase/txns.sql
common/src/supabase/schema.ts
common/src/supabase/utils.ts
web/components/charity/charity-card.tsx
web/lib/firebase/txns.ts
web/lib/supabase/txns.ts
web/pages/charity/index.tsx

Previously the charities page loaded all txns from Firestore (twice, lol) in order to tally everything up and display the page. Now it loads the information using a Supabase RPC.

Use Supabase to load charities page

---

web/lib/supabase/txns.ts

For some reason this happened during a Vercel build and it killed the build? Very unclear why.

Make `getDonationsByCharity` not die on `null` response from `rpc`

---

web/hooks/use-feed-timeline.ts

This is wasting time and causing error spam in our Postgres logs when it attempts to query for undefined news IDs.

Don't mess stuff up when there are no new feed items

---

backend/supabase/seed.sql
common/src/supabase/schema.ts

This isn't a subcollection in Firestore, it's a JSON array in the manalink object. So we need to populate it in Supabase in the trigger that extracts the JSON from the manalink objects.
We can get the info we need about the claims, like the user that claimed the manalink, by joining the txns.

Populate `manalink_claims` table from claims in manalink data

---

love/components/filters.tsx

As a gay man I wanted to be able to filter the profiles to other gay men, so I added the ability to filter on users's preferred genders. 
The filtering on the checkboxes will be the intersection of all selections. This will support people only wanting to look for bisexual people. 
1. Load page, see all profiles
2. Check "Interested in -> Male". Now I only see profiles that are interested in men.
3. Also check "Interested in -> Female". Now I see the intersection of profiles interested in men and interested in women.
4. Uncheck all boxes. Now I see all the profiles again.

love: Add filter for interested in

---

love/components/filters.tsx

> In the search filter, the "relationship style" options are all unchecked by default and if you check them, they're ANDed together - only users that have checked all of those options will be displayed. That is counterintuitive. If I check "monogamous" and "polyamorous", I'm expecting users who checked either, not the much smaller number of users that checked both. They should be ORed together, and all checked by default.
> 
> chrisjbillington, https://discord.com/channels/915138780216823849/1166835928518631454/1168154982676181073

Make filters more sensible for multiple values in "relationship style"

---

backend/functions/src/scheduled/update-user-metrics.ts
backend/supabase/seed.sql
common/src/supabase/schema.ts

The portfolio history table is 100M rows, so replacing this big ass text ID with a normal ID (and likewise again in the primary key index) saves us gigabytes of DB space.

Replace bulky Firestore portfolio ID with small ID

---

backend/supabase/user_events.sql

`user_events` is large, so it's important to keep these indexes under control.

Clean up extra `user_events` indexes

---

backend/functions/src/scheduled/update-user-metrics.ts

Today I saw that invocations of `updateUserMetrics` were overlapping, which is really bad, so let's make that not happen.

Slow down `updateUserMetrics`

---

backend/shared/src/add-interesting-contracts-to-feed.ts
backend/supabase/users/indexes.sql

For some reason I don't fully understand, the optimizer can't see through this `u.id = any(array[...]::text)` clause, so it does a scan on the USM table every time because it thinks there's basically no filter.
Changing it to use a (more normal) `u.id in (...)` clause works fine.
FYI @IanPhilips

Make user embeddings fetch optimize better

---

web/components/bet/user-bets-table.tsx
web/pages/[username]/index.tsx

**Problem:** The UX on mobile when clicking into a profile is confusing because there is no way to get back out of the profile. Most modern phones will have auto-hid the browser bar thus making it very tricky to go back to the page you were just on. 
To solve for this I have added a sticky header to the top of user profile on mobile with a back button and relocated the More Options menu here as well. As you scroll down the page it shows the username in the header as well. 
**Before:**
**After:**
(Page on first load)
(Scrolled shows username and the bumped down sticky table headers)

Add Back Button to Profile on Mobile

---

love/components/filters.tsx

This PR adds a select next to the filter button to allow users to switch ordering between `Recently Active` and `Newly Registered`. I also included a change to the display of filters to make them 2-column on desktop for easier scanning. 
New Order By select:
Two-column filters on desktop:
One-column filters on mobile:

Add `Order by` to Profiles View

---

web/components/feed/feed-comments.tsx

When users reply to a comment with NO bets, it should be indicated by a red arrow going down, not up.

Red arrow go down

---

love/components/lover-profile-header.tsx
web/components/user/user-handles.tsx

On Android, linking to e.g. https://twitter.com/ManifoldMarkets when opening in app opens up the profile automatically, but linking to https://twitter.com/@ManifoldMarkets returns a failed search method.
Reproducible on https://manifold.love/TomboyTesting. 
System info:
Google Pixel 6
Android 15, October 5, 2023 security update (pixel 6 build/UP1A.231005.007)
Chrome browser 118.0.5993.111
Twitter app 10.13.1-release.0 and 10.14.0-release.0

removing @s from link to Twitter

---

backend/functions/src/scheduled/clean-old-rows.ts

FYI @IanPhilips per some sampling I don't think this will clean that many rows (e.g. it cleaned 80k for 500 I tried it on) but it beats the current non-working version and seems reasonable. We might want to figure out whether we should trim down the rows being generated? It seems like there are more than there ought to be -- 225m for 50k users is 4k per user. If those are mostly over two weeks, it seems pretty spammy.

Make feed cleaning script much simpler and faster

---

backend/functions/src/scheduled/add-trending-feed-contracts.ts
backend/shared/src/firestore-lock.ts

It seems that even though this is just a normal v2 scheduled function, it gets invoked multiple times as a matter of course. I think this may be by design in GCP (i.e. it's not guaranteed only once) so we should just deal with it.

Implement locking system for `addcontractstofeed`

---

web/pages/[username]/index.tsx

On profile pages, there is a random gap that appears to the left of the header which I've removed. I also replaced the stacked usernames in the top bar with just the username + badge because having all of it appear there is redundant.

Clean up header on profile pages

---

package.json
web/next.config.js
web/package.json
yarn.lock

The only catch here is that we need to use a fork of `@supabase/realtime-js` that kills the `websocket` dependency, but it will likely be in master pretty soon. See here: https://github.com/supabase/realtime-js/pull/263

Turn on turbopack for `yarn dev`

---

backend/shared/src/dream-utils.ts
web/components/editor/image-modal.tsx

Dreamstudio [deprecated some engines](https://platform.stability.ai/docs/features/api-parameters#engine) and so a new one must be specified.

Specify engine in Dream API Call

---

web/components/bet/limit-order-panel.tsx

The limit order screen reads "Value" instead of "Probability" on numeric markets

Probability  -> Value

---

package.json
yarn.lock

Now upstream uses the [fixed up websocket stuff](https://github.com/supabase/realtime-js/pull/263), so we don't need to use my fork in order to get Turbopack to work anymore.
@sipec because I think you had some kind of difficulty that I didn't understand with the fork dependency. Now it will be gone.

Use upstream @supabase/realtime-js 2.9.0

---

backend/shared/src/supabase/init.ts

Should mitigate memory leakage in the backend, see [this issue](https://github.com/supabase/supabase-js/issues/926) and the relevant code in `SupabaseAuthClient` [here](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L2105).

Set `autoRefreshToken` false when creating backend `SupabaseClient`

---

backend/shared/src/helpers/search.ts

Just fixing some errors I noticed in the logs:
1) The code would produce an unsyntactical query if `term` was entirely special characters, since the bailout for empty strings was before the special character removal.
2) The code would produce an unsyntactical query if there were special characters at the start or end of the string guarding spaces (like `foo !`) because the trimming was before the special character removal.
Now I can't see any reason it should obviously produce an unsyntactical query.

Fix bugs in `constructPrefixTsQuery`

---

backend/api/src/supabase-search-contract.ts
backend/api/src/supabase-search-groups.ts
backend/api/src/supabase-search-users.ts
backend/shared/src/supabase/sql-builder.ts

If you call pg-promise's formatter multiple times on SQL strings (either directly or implicitly by passing parameters to e.g. `db.map`), you may end up with bugs where the first format introduces formatting language syntax to the second format. For example, in the cases I fixed here, we were doing something like:
```typescript
const where = pg.as.format('where foo = $1', [query]);
const sql = 'select * from bars ' + where + ' order by $1';
const result = await db.many(sql, [sort]);
```
This will throw a template syntax exception given the query string `i have a $5 bill`.
Note that `db.many(sql, [])` is different from `db.many(sql)` or `db.many(sql, null)`. The first invokes the template formatting engine; the second does not.
The best way to handle this is to never write code that runs …

Fix bugs with double formatting in some searches

---

docs/docs/api.md

Now we are happy for people to actually move, since the new one is an API-compatible implementation of the old one.

Update the API docs to refer to `api.manifold.markets`

---

web/lib/api/proxy.ts

Previously when this code was running on the non-edge-runtime stuff I don't know what the type of `req.body` was, but presumably the old version made sense.
Now, `req.body` always seems to be a `ReadableStream`, so we can pass it [directly to `fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#body) instead of calling `JSON.stringify` or whatever to dick around with it.

Just hand `req.body` `ReadableStream` directly to `fetch`

---

backend/shared/src/supabase/contracts.ts

e.g "Will BTC close higher on blah date than blah date"
Very good [coverage of the relevant markets](https://manifold.markets/browse?q=%22close%20higher%22&s=score&f=all&ct=ALL) and few (if any) false positives matching on "close higher"
As suggested by Ian on discord
(I have not tested if this actually works, just copying the "daily-coinflip" code)

Make daily/weekly/etc stock/crypto price markets non-predictive

---

backend/api/src/markets.ts
backend/functions/src/triggers/on-update-contract.ts
backend/shared/src/importance-score.ts
backend/supabase/contracts/indexes.sql
backend/supabase/groups/groups.sql
backend/supabase/seed.sql
common/src/api/market-types.ts
common/src/api/schema.ts
common/src/contract.ts
common/src/supabase/schema.ts
docs/docs/api.md

`lastUpdatedTime` used to mean `max(lastBetTime, lastCommentTime)`. Now it also covers other user-salient edits to contract properties.
In addition, the new `/markets` parameters will allow API users to easily get "fresh" markets from the API without having to constantly poll everything in the universe.

Make `lastUpdatedTime` on contracts more useful, improve API

---

common/src/secrets.ts
web/lib/supabase/admin-db.ts

Loading secrets in various Vercel server-side handlers is costing us about twenty bucks a day on GCP.
Let's not make a habit of doing this, because it will just get more and more expensive as our traffic grows and as we use our secrets in more code. It's easy to just put the secrets in Vercel.
I think the cost is probably driven completely by this and the stuff we do in local dev is a matter of pennies, so we can keep doing easy mode "load everything when you run anything" style locally.

Be more parsimonious with runtime secret loading

---

backend/api/src/get-related-markets.ts
backend/supabase/contracts/indexes.sql
backend/supabase/seed.sql

This is still a substantial source of load, so it's worth making it as good as we can reasonably do at the moment.
This implementation is nicer because it ends up with a plan that is basically "for each group slug, do a single index scan on contracts to pick up the top N for that slug." That isn't clearly possible to do with a single index when the "group IDs to contracts" mapping and "importance score ordering" were in two tables. So the denormalized `group_slugs` field is helping us out.
The `btree_gin` extension is necessary to use a GIN index on columns like `importance_score` with scalar values.
It would make sense to further improve this code to do more of the work in SQL -- then we wouldn't have to spit out as many contracts from the middle step (in the expectation that they will …

Further improve `get-related-markets` query

---

backend/shared/src/supabase/answers.ts
backend/shared/src/update-contract-metrics-core.ts

This is slow and it's not doing anything -- it only ever replicated one answer in a month (which doesn't mean it was addressing a real problem, because the pattern of "query answers, then after you get them, go look at firestore to see if there are any you didn't get" will find false positives that were just added to Firestore in the last few seconds.)
FYI @IanPhilips -- my understanding is that you did this to try to debug some answer replication stuff, but clearly the result was that this was not the bug.

Remove code to replicate answers from `updateContractMetrics`

---

backend/functions/src/index.ts
backend/scheduler/src/jobs/index.ts
backend/scripts/update-metrics.ts
backend/shared/src/update-group-metrics-core.ts

It's really cozy to pause this stuff if I am doing heavy DB maintenance so I want to move it to the scheduler, which has a "pause" button.

Move `updateGroupMetrics` to scheduler

---

backend/scheduler/src/jobs/clean-old-tombstones.ts
backend/scheduler/src/jobs/index.ts

In case you forgot, these are markers that indicate a Firestore document was deleted, which is relatively rare in our DB. Once all the writes prior to a delete have been replicated, the delete tombstone isn't needed anymore.
It's nice to keep this table clean because every replicated write has to check this table in order to protect itself from race conditions between replicated updates and deletes, so let's clean up the old ones.

Add job to clean up old replicator tombstones

---

backend/shared/src/update-contract-metrics-core.ts
backend/supabase/contract_bets.sql

There was no reason for this to be two queries, and the answer part of the queries wasn't working well because the covering index hadn't been updated with the `answer_id` to help it out.
FYI @IanPhilips

Fix suspicious `updateContractMetrics` historical probs query

---

web/components/widgets/pagination.tsx
web/hooks/use-pagination.ts
web/lib/supabase/txns.ts
web/pages/charity/[charitySlug].tsx

Proximate issue: the charity page was trying to load a ton of user IDs from PostgREST using an `in` clause, which produced a too-long URL, so it couldn't load them, and long charity pages (e.g. GiveWell) were 500ing.
Generally speaking we need to make more things that are both paginated (i.e. they don't load every single one up front) with data from Supabase, but also can update on the client with new stuff that was just added, instead of sitting around waiting seconds to hear back from the database that the new thing appeared (e.g. when you make a bet on a contract page, it should tack it onto the front of the paginated list of all bets, and when you make a comment, it should tack it onto the top of the list of all comments.) This is starting to move in the direction of making that easy …

Add some pagination infrastructure, paginate donations on charity page

---

backend/api/src/get-ad-analytics.ts
backend/supabase/user_seen_markets.sql
common/src/supabase/schema.ts

This is like, a big table, so it's worth fixing up to be efficient.
After this we can migrate writes and ditch the `data` column. And after that we can migrate the table to be one-row-per-user-market as is our plan.

Use native columns in `user_seen_markets`

---

web/components/contract/bountied-question.tsx

Users reported multiple double or triple bounty submits while the site was lagging. This will prevent multiple submits while actively submitting.

[WEB] Guard Adding Bounty While Submitting

---

backend/scheduler/src/jobs/clean-old-feed-rows.ts
backend/supabase/user_feed.sql

Unlike the old version, this is actually efficient enough that the old feed rows should successfully get cleaned.

Use much more efficient version of `clean-old-feed-rows`

---

web/components/notifications/income-summary-notifications.tsx

This PR adds the outcome to trader bonus notifications on multiple choice markets. 
Happy to change the format or colors if you would prefer, just let me know.

[WEB] Show Outcome on Multi Trader Bonus Notifications

---

web/components/new-contract/new-contract-panel.tsx

URL params are coming in after the page has rendered and thus required selecting the market type on duplicate market, even though its already in the params. This useEffect keeps local state in sync with the params coming in, allowing users to skip selecting market type if its provided.

[WEB] Skip Market Type on Duplicate Market

---

backend/supabase/seed.sql
backend/supabase/user_reactions.sql
common/src/supabase/schema.ts
common/src/supabase/utils.ts

Can do this in a few hours, doesn't matter when exactly
Tasks
```sql
drop index user_reactions_data_gin;
drop index user_reactions_type;
drop index user_reactions_content_id;
```

Clean up reaction migration

---

love/pages/_document.tsx
love/public/init-theme.js
web/hooks/use-theme.ts
web/pages/_document.tsx
web/public/init-theme.js
web/styles/globals.css

There are currently two problems with dark theme. This PR fixes both of them.
When a user is using dark theme on their device and opens the website for the first time, the website show light theme despite showing "Auto" in the side bar.
You can reproduce by deleting site data and reloading the site.
The device is set to dark theme in this recording:
https://github.com/manifoldmarkets/manifold/assets/8357970/f84e1467-a9da-4a2e-9609-86619146512d
You can see in this recording, only after clicking the theme toggle button 3 times and cycling back to "Auto" does the website show dark theme.
This is caused by the `useTheme` hook setting the initial value of `localStorage.getItem('theme')` to `"loading"` but `init-theme.js` not recognizing that value. This is fixed by checking for that value and …

Fix dark theme

---

web/components/topics/topic-selector.tsx

mattyb said in discord:
> when there’s 4 “Apple”s, limiting to 5 feels way too low
> if tags were clearly organized, and lacking dupes, this would be fine (imo)
> but i can’t tell which Apple I’m using, and thus need them all.
> 
> If there was “Apple (30 Markets)” and “Apple (350 markets)” this would also be better
We don't have market stats, but we do have follower stats.

Show number of followers when adding a topic

---

backend/api/src/get-supabase-token.ts
backend/shared/src/supabase/init.ts
common/src/supabase/utils.ts

Per Supabase we need to switch to this in the next week because the old pgbouncer URL (`db.instance.supabase.co`) is getting shut off.
See https://supabase.com/blog/supavisor-postgres-connection-pooler for some marketing material.
Should be no big deal.

Switch backend code to connect to Supavisor pooler

---

backend/replicator/src/replicate-writes.ts
backend/scripts/find-deep-docs.ts

This was busted in a crazy way. If you use the Firestore server SDK to write a document with more than 20 levels of nesting, you get an error like this:
```
Error: Value for argument "data" is not a valid Firestore document. Input object is deeper than 20 levels or contains a cycle.
at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:258:15)
at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13)
at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13)
at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13)
at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265: …
```

Store failed writes in replicator in a way that is robust to nesting

---

common/src/chart.ts
common/src/contract-params.ts
common/src/supabase/bets.ts
politics/components/contract/contract-card.tsx
web/components/charts/contract/zoom-utils.ts
web/components/contract/feed-contract-card.tsx
web/components/contract/related-contracts-widget.tsx
web/components/feed/feed-chart.tsx
web/components/us-elections/contracts/which-party-card.tsx
web/lib/supabase/feed-timeline/feed-market-movement-display.ts

If we grab by created time, it will either bunch up at the start or the end if there's enough trades. For instance, here https://discord.com/channels/915138780216823849/1210629468130123836 users point out that the charts on manifold.markets/calibration are wrong in this way
This is something that the old code using `getBetPoints` did correctly, by ordering by id rather than created time
@IanPhilips I don't understand why you add two points for every bet, with a millisecond difference. I am also not sure why `leadingBetTime` is needed. So idk if ordering by id would break that calculation.

Spread out the points we grab for feed chart

---

common/src/supabase/bets.ts
common/src/supabase/utils.ts

Our `convertSQLToTS` helper will by default write `null` into Javascript properties that have `null` in the corresponding SQL row, but we have many Typescript types that have optional properties that don't accept `null`. That can lead to JS objects that violate the Typescript types, which can easily produce bugs.
In this case, `calculateUserMetrics` was doing a `groupBy(bets, 'answerId')` on bets, and a mix of bets with `null` and `undefined` answer ID would produce a broken grouping, which would then blow up the bulk insert later on.
By creating the JS objects to have `undefined` instead of `null` we avert this problem.
Note that the analogous problem still exists elsewhere in our codebase. I just wanted contract metrics to work.

Fix broken contract metrics updating

---

web/hooks/use-pagination.ts
web/pages/charity/[charitySlug].tsx

This is mainly designed to make the pagination stuff capable of handling the case where you have a mix of things you are adding to the front manually (e.g. when you make a bet) and live updates to the rest of the list (e.g. bets and updates you are receiving over the wire.) It keeps track of your manually added "prefix" separately from the rest of the items, so that it doesn't get wiped out if the rest of the list changes. This should make it appropriate for using in some new places.
The implementation is also cleaned up in general and documented.

Substantially improve `usePagination` machinery

---

backend/supabase/contracts.sql
backend/supabase/contracts/indexes.sql
backend/supabase/views.sql
common/src/supabase/schema.ts
web/hooks/use-contract-supabase.ts
web/lib/supabase/contracts.ts

Just glancing at it briefly I found these handful of contracts table indexes that are either no longer used, unnecessary, or redundant with other indexes on the table.
- Popularity score is no longer used.
- The index on visibility is pointless given that there is also an index with only visibility-public IDs and is of questionable utility anyway.
- The index on unique bettors serves only the partner progress page, which is easy to serve with the existing index on created time instead.
- The index on close time etc. isn't adding value over our existing index on just close time.
- The index on importance score and resolution time isn't adding value over the existing index on importance score.
- The calibration page index isn't relevant to the calibration page (whose query is mostly about …

Clean up contracts table stuff

---

common/src/api/schema.ts

This will be a big improvement for some of our API users, and we don't really have a problem with load or bandwidth cost right now anymore on the API, so why not dial down the caching.

Change most public APIs to cache for 5 seconds instead of 15

---

web/lib/supabase/users.ts

`getContractsCreatedProgress` checks for markets where `data->>uniqueBettorCount` is ≥20, but it should be checking `data->uniqueBettorCount`.
`->>` casts the count to a string, which results in the unique bettor count being lexicographically compared to "20", when it should be numerically compared to 20. As a result, the query includes all markets where the first digit of the bettor count is 2 to 9. (e.g. bettor counts of 5 and 50 are included, but 1 and 100 aren't).
cc @jahooma

Compute partner progress for ≥20 trader markets correctly

---

backend/api/src/create-user.ts
backend/api/src/record-contract-view.ts
backend/supabase/user_contract_views.sql
common/src/supabase/schema.ts

There are especially some cases where we care what page views someone has done lately, and don't care about relatively "cheap" card views. So I think it's good to have this more detailed info about recent views.

Make separate timestamp columns for each kind of contract view

---

backend/supabase-grafana-agent/agent.yaml
backend/supabase-grafana-agent/run.sh

Just wiring this up because something weird happened on dev and the obvious first step is to increase visibility.
There's a little dropdown on the top left of the Grafana dashboard that lets you switch between dev and prod now.

Get metrics for Grafana from dev DB

---

backend/scheduler/src/jobs/update-stats.ts
common/src/util/math.ts
web/pages/admin/reports.tsx
web/pages/calibration.tsx
web/pages/charity/index.tsx
web/pages/home/index.tsx
web/pages/newbies.tsx
web/pages/news/index.tsx
web/pages/stats.tsx

Besides planned downtime, it seems bad to not be able to deploy the website if the backend is having problems... Probably we should just catch errors from all of these as a matter of course.

Catch errors from random `getStaticProps` that talk to DB, API

---

backend/api/src/record-contract-view.ts

We have this logic in `record-contract-view` for the new views table that counts all views in one minute as being just one view. This makes sense for logged-in users to avoid spamming the count if they refresh and so on. But for logged-out users, we have no reason to believe the views are the same person, so it makes no sense. Let's count each view for them.

Record all views for logged-out users

---

web/components/comments/comments-list.tsx
web/components/widgets/pagination.tsx
web/hooks/use-pagination.ts
web/lib/supabase/txns.ts
web/pages/charity/[charitySlug].tsx

I was interested in doing this because Ian mentioned that he tried to use the `usePagination` stuff here but had a hard time.
I modified `usePagination` to be easier to use for `limit`/`offset` style queries like the comments list API, and fixed some small bugs I noticed (e.g. if you went back and forth from the end of the list it would fire off a duplicate query for the next page.)
The end result is a less buggy comment list (the old one did stuff like flashing "No comments yet" before first load, and wiping out the list in between loads) and a better `usePagination` for adapting to later stuff elsewhere.
By the way, I note that this used to check for being authorized for no obvious reason? You don't need to be authorized to call this API and get comments.
FYI @IanPhilips

Tidy up user comments list code

---

backend/functions/src/triggers/on-update-contract.ts
backend/scripts/delete-group.ts
backend/scripts/merge-all-dupe-names.ts
backend/scripts/merge-groups.ts
backend/shared/src/supabase/utils.ts

- nonpredictive, non-predictive -> Unranked
- DGG, dggL, Destiny.gg Stocks, Daliban HQ -> Destiny.gg
- Musicians -> Music Artists 
- Donald Trump, Trump Legal Defense -> Trump
- Trump conviction -> Trump indictments
- United Kingdom -> UK
- USA, #america -> United States
(maybe these synonyms should be keywords on the group for search! or go the whole AO3 route and let multiple names point to the same tag...)
```
twitch-ad6be7215259 twitch
-unranked nonpredictive
-unranked nonpredictive
nonpredictive-7760d7a025a1 nonpredictive
nonpredictive-20971ec2bf35 nonpredictive-profits
nonpredictive-d7f37225e3b6 nonpredictive
unsubsidized-1df19678470d unsubsidized
spain-6086cefc2bdd spain
spain-df5197aa9fca spain
spain-24f3808c4276 spain
mr-beast-0b1d3e75b4b9 mr-beast
destinygg-cc254c41a061 …
```

The Merge: add scripts to merge and delete groups

---

backend/api/src/app.ts
backend/api/src/delete-group.ts
common/src/api/schema.ts
web/components/topics/delete-topic-modal.tsx
web/components/topics/topic-options.tsx

I haven't really thought about _who_ should be able to delete groups. should be same "mod level" as renaming groups probably, but for some reason that is manifold admin / group admin only right now

Add ability to delete groups with no markets

---

backend/shared/src/resolve-market-helpers.ts

Helps fix the bug where you can't delete independent MC markets because their resolution type is MKT even if they are all resolved

Set resolution for independent MC to CANCEL if it's cancelled

---

web/components/buttons/referrals-button.tsx

There shouldn't be a dollar sign here:
The code does `${formatMoney(REFERRAL_AMOUNT)}` as if it was in a format string, but it's actually in a JSX markup expression which doesn't require a `$` there.

Say "for M̶250" not "for $M̶250"

---

web/components/buttons/referrals-button.tsx

This PR is identical to #2577, which was (accidentally?) reverted by @jahooma in d3483dfba19f601a34bd1cfadfe446e48e529f80.

Say "for M̶250" not "for $M̶250", again

---

backend/api/src/add-subsidy.ts
backend/api/src/create-answer-cpmm.ts
backend/api/src/create-market.ts
backend/api/src/create-user.ts
backend/shared/src/helpers/add-house-subsidy.ts
backend/shared/src/resolve-market-helpers.ts
backend/shared/src/supabase/liquidity.ts
backend/supabase/contract_liquidity.sql
common/src/add-liquidity.ts
common/src/antes.ts
common/src/liquidity-provision.ts
common/src/supabase/schema.ts
common/src/supabase/utils.ts
common/src/util/random.ts
firestore.rules

This no longer reads/writes contract transactionally, so the recorded pool (and p?) may be off if someone bets at the same time. That doesn't matter since we don't use those fields.
Somewhat more concerning - I think the _subsidyPool_ could be off if someone adds a subsidy the same time that the house tries to add a subsidy. We could avoid this by making the pg.tx `SERIAL` but idc

Migrate liquidity to supabase

---

backend/shared/src/create-notification.ts

If you make small bets or bets at 1% or 99%, the bet may end up profitable, while `Math.round(profit) === 0`. In that circumstance, the mobile notification will say "Resolved: {YOUR BET}. You **lost** M0, outperforming N others!" when it should say something like "Resolved: {YOUR BET}. You **made** M0 (+0.5%), outperforming N others!"
This changes `sendNotificationsIfSettingsPermit` to round profit only at display using `formatMoney`, rather than on computation, so the `profit > 0` check is correct even for profit in (M0, M0.5).
And an additional note—this is my first time contributing, and I don't have everything set up, so I haven't tested the mobile notification code path. I would appreciate if one of the devs could run this before committing. I think it's all correct, but wouldn't …

Fix mobile notifications for profits rounding to 0

---

backend/scripts/delete-private-groups.ts

I've already N/A'ed all remaining multi, canceled all private bounties, and closed all private polls. Also, everyone who asked to keep their private markets / groups has already had their markets turned unlisted and their group turned curated.
so running this script should just take care of private groups once and for all
- comments are deleted
- remaining markets get N/A'ed
- contracts and answers get redacted
- private groups are literally deleted

Delete all private groups

---

backend/api/src/add-topic-to-market.ts
backend/api/src/create-market.ts
backend/api/src/helpers/on-create-market.ts
backend/shared/src/update-group-contracts-internal.ts

The most important thing is that running the create market txn and create liquidity antes happen in the same transaction
I was considering *just* putting the finance stuff in the same tx, and leaving create group etc out of it, but i think that if the client shouldn't get an error if the create market succeeds. we could put things in a continuation i suppose, but it seems unnecessary performance wise

Do all of create market within a transaction

---

backend/api/src/on-create-bet.ts
backend/api/src/place-bet.ts
backend/shared/src/short-transaction.ts
common/src/api/schema.ts
common/src/bet.ts
common/src/calculate-cpmm-arbitrage.ts
web/components/bet/bet-panel.tsx
web/components/bet/limit-order-panel.tsx

This has the client calculate its deps, letting us avoid the case where the API bricks bc it can't get a pg connection from the pool bc of too many concurrent website users. This doesn't handle the case where the API server is being hammered from bots/API users and runs out of connections trying to simulate the deps. We could use the cache from the bet-cache branch if we think this case is worth handling now with the extra complexity.

Have client calculate dependencies and pass to API

---

docs/docs/api.md

Official instance shows
```
{"message":"Error validating request.","details":[{"field":"limit","error":"Number must be less than or equal to 1000"}]}
```

api.md: Update /v0/comments limit parameter default

---

backend/api/src/create-market.ts
common/src/api/market-types.ts
common/src/util/random.ts
web/components/new-contract/contract-params-form.tsx
web/components/new-contract/new-contract-panel.tsx

This is related to the bug discussed at https://manifoldmarkets.notion.site/Market-creation-outage-d6c0ed5a001a4057bcb89f82787a5b84
I'm intending to mitigate the effect of any future bugs by preventing duplicate contract creation.
This change is NOT properly tested on the backend because I don't have a suitable dev environment set up (is this possible?) but maybe the magic Vercel PR validation environment will help.

Adding an idempotency key for contract creation.

---

backend/api/src/get-user-portfolio-history.ts
backend/api/src/unresolve.ts
backend/scripts/add-cash-balance-column.sql
backend/shared/src/create-user-main.ts
backend/shared/src/get-user-portfolio-internal.ts
backend/shared/src/helpers/portfolio.ts
backend/shared/src/supabase/portfolio-metrics.ts
backend/shared/src/supabase/users.ts
backend/shared/src/txn/run-txn.ts
backend/shared/src/update-user-metrics-core.ts
backend/supabase/user_portfolio_history.sql
backend/supabase/user_portfolio_history_latest.sql
backend/supabase/users.sql
common/src/calculate-metrics.ts
common/src/portfolio-metrics.ts
common/src/supabase/portfolio-metrics.ts
common/src/supabase/schema.ts
common/src/supabase/users.ts
common/src/user.ts

[manicode]
Overall, the changes are focused on implementing a separate cash (prize money) system alongside the existing mana system. Here's a summary of the key changes:
1. Database schema updates:
- Added new columns to user_portfolio_history and user_portfolio_history_latest tables: cash_balance, cash_investment_value, and total_cash_deposits.
- Updated the users table to include total_cash_deposits.
- Modified SQL functions and triggers to handle the new cash-related columns.
2. Backend changes:
- Updated portfolio calculation functions to handle cash metrics separately.
- Modified transaction handling to account for cash transactions.
- Updated user metric calculations to include cash-related data.
3. API and type updates:
- Updated API endpoints to include cash-related data in …

Calculate prize cash portfolio metrics

---

backend/api/src/place-bet.ts
common/src/fees.ts
web/components/bet/fees.tsx
web/components/contract/creator-fees-display.tsx

- we will be providing liquidity for all the sweepcash markets rather than the creator anyways
- a sweepcash bonus would prevent us from sweepifying a market made by some creators - creators outside of the US for instance. doing a currency conversion would be fine, but more effort than its worth
we should definitely revisit the unique trader bonus though

Remove creator fee for sweepstakes

---

web/components/bet/bet-panel.tsx
web/components/bet/feed-bet-button.tsx
web/components/bet/limit-order-panel.tsx
web/components/bet/quick-limit-order-buttons.tsx
web/components/comments/comment-actions.tsx
web/components/comments/comment-input.tsx
web/components/contract/contract-table-action.tsx
web/components/us-elections/contracts/conditional-market/conditional-market.tsx
web/components/us-elections/contracts/party-panel/binary-party-panel.tsx
web/components/usa-map/house-table-helpers.tsx

Skipping the answers for now, since state wouldn't be accurate anyways.
Resolves MAN-1529 part 2

track bet intent and bets in Amplitude

---

backend/shared/src/generate-leagues.ts

Maintain the shuffled array for league randomization. See: issue #3055

Make league generation randomized

---

web/hooks/use-persistent-in-memory-state.ts
web/hooks/use-persistent-local-state.ts
web/hooks/use-state-check-equality.ts

react always rerenders when you call `setState`. so once upon a time, someone wrote a hook that checks if the thing has changed before calling setState. nevermind whether this use case is common or whether the overhead of adding a ref is worth it. I honestly don't know! there are many places we send requests to the server or db on the first render of a component, so while  _rerendering UI_ is very cheap, rerendering at all may not be? did anyone actually profile this??
anyways, to do the equality check you need to have an `if(state != newState)` before you call `setState()` which means you can't consistently do `setState((capturedState) => ...` correctly since the state inside the setState may differ from the state outside it, but what you really want to condition on is the inside state …

EQUALITY IS INCOMPATIBLE WITH CAPTURING THE STATE

---

backend/api/src/create-market.ts

Context: [bounty](https://manifold.markets/ian/make-answers-created-during-market).
Simple/minimal fix. 
Previously: for higher tier markets, `ante` would be capped at `unmodifiedAnte` (i.e. numAnswers * 100 for MC). 
Now: for independent MC, `ante` is allowed to scale with the full `totalMarketCost`. For other question types, functionality is unchanged.

Independent MC created with full starting liquidity per answer

---

web/public/opensearch.xml

The OpenSearch search engine specification has mismatched open/closing tags, which makes it invalid XML and thus doesn't work. This PR fixes the XML, making it valid.

Fix OpenSearch XML

---

backend/api/src/hide-comment.ts
backend/shared/src/supabase/contract-comments.ts
comment-deletion-feature-summary.md
common/src/api/schema.ts
common/src/comment.ts
common/src/supabase/comments.ts
web/components/comments/comment-header.tsx
web/components/comments/comment.tsx
web/lib/supabase/comments.ts

A new 'delete' option was added to the comment dropdown menu, allowing admins and mods to completely remove comments from view.
Key changes include:
*   The `Comment` type in `common/src/comment.ts` was extended with `deleted`, `deletedTime`, and `deleterId` fields.
*   The `hide-comment` API in `common/src/api/schema.ts` was updated to accept an `action` parameter (`'hide'` or `'delete'`).
*   The `hide-comment` API implementation in `backend/api/src/hide-comment.ts` was modified:
*   The 'delete' action is restricted to admins and mods only.
*   It prevents deletion of admin/mod comments.
*   It updates the new `deleted` fields in the database.
*   Frontend components in `web/components/comments/comment.tsx` (`FeedComment`, `ParentFeedComment`) now return `null` if a comment is marked …

Add delete option for comments for admins/mods

---

backend/api/src/get-user-last-active-time.ts
backend/api/src/routes.ts
common/src/api/schema.ts
web/components/user/user-hovercard.tsx

A new API endpoint, `get-user-last-active-time`, was introduced to retrieve a user's most recent activity.
*   **API Schema:** Defined in `common/src/api/schema.ts` as a `GET` endpoint, requiring authentication, with `LIGHT_CACHE_STRATEGY`, and returning `lastActiveTime: number | null`.
*   **Backend Implementation:** A new file, `backend/api/src/get-user-last-active-time.ts`, was created.
*   It queries the `user_contract_views` table for the `greatest` of `ts_to_millis` from `last_card_view_ts`, `last_page_view_ts`, and `last_promoted_view_ts`. `coalesce` handles null timestamps.
*   Access is restricted to the queried user or an admin, ensuring data privacy.
*   **Route Registration:** The new handler was imported and registered in `backend/api/src/routes.ts`.
*   **Frontend Update:** …

Update user hovercard to include last active time
